### ISSUE TITLE
Submitting scrobbles fails on Android 4.3

### ISSUE THREAD

**Issue by iletunic** [tgwizard/sls#104]
On Galaxy Note 3, scrobbles are remaining in the local queue. Clicking the "Scrobble now" button does nothing. The following error appears in the log:

java.lang.SecurityException: Permission Denial: get/set setting for user asks to run as user -2 but is calling from user 0; this requires android.permission.INTERACT_ACROSS_USERS_FULL

Adding android.permission.INTERACT_ACROSS_USERS_FULL to AndroidManifest.xml fixes the problem, and everything works fine now.

**Comment by HumbleBeeBumbleBee** [comment]
@iletunic Did you want to make a commit for this?

**Comment by iletunic** [comment]
Hey...

That was ages ago, I think it works fine now or it was fixed in the
meantime.

Cheers,

On Thu, Apr 30, 2015 at 8:58 PM, HumbleBeeBumbleBee <
notifications@github.com> wrote:

> @iletunic <https://github.com/iletunic> Did you want to make a commit for
> this?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/tgwizard/sls/issues/104#issuecomment-97927554>.
>



-- 
Ivica Letunic
http://www.letunic.com
P:+49-6221-387-8534 M:+49-172-847-7510

**Comment by HumbleBeeBumbleBee** [comment]
Super!!!
Hey ilentunic could you CLOSE this issue then please.
