### ISSUE TITLE
PowerAMP is recognized as both "Poweramp" and generic "Android Music Player"

### ISSUE THREAD

**Issue by softroke** [tgwizard/sls#119]
SLS recognizes PowerAMP as not only "Poweramp" but also generic "Android Music Player."
When I turn off any scrobble option in PowerAMP setting, It gives back to SLS as generic "Android Music Player" so it scrobbles without of my control.
Now, only way to stop scrobble from PowerAMP, is unchecking "Android Music Player" in SLS setting. However, I also use Google Play Music so it conflicts.

Am I only one with this problem?
I guess it needs more adjustment about detecting PowerAMP.
Here is my device details. It is not rooted and I did not applied any custom rom something.

Device: Google Nexus 4
OS: Android 4.4.2
SLS: 1.4.6
PowerAMP: 2.0.9-build-548
Google Play Music: 5.4.1409N.1014766

**Comment by HumbleBeeBumbleBee** [comment]
Please continue discussion in #200

**Comment by HumbleBeeBumbleBee** [comment]
This problem requires clash code like scrobbledroid has.

**Comment by HumbleBeeBumbleBee** [comment]
@softroke 
You should be able to disable PowerAmp's scrobble settings.
Using the default android music player seems to work better.

**Comment by HumbleBeeBumbleBee** [comment]
This is fixed in the next version.
PowerAmp should only be recognized as PowerAmp.

https://github.com/HumbleBeeBumbleBee/SLSmanager/blob/master/SQLite.md

That should clarify everything.
