### ISSUE TITLE
Scrobble "Album artist" instead of "Artist"

### ISSUE THREAD

**Issue by Perlence** [tgwizard/sls#120]
Hello,

I think it would be really great if there was an option to choose either to scrobble "Artist" name or "Album artist", as it's two different fields. Of course, if players distinguish those fields and are able to share this info with SLS.

Thank you.

**Comment by HumbleBeeBumbleBee** [comment]
After reading @metanota 's detailed response I feel it's very unlikely SLS will be able to implement such a useful, yet inapplicable, feature and will therefore close this issue.
@Perlence Thanks for the idea!
@metanota Thanks for the clear response.

**Comment by dror3go** [comment]
Hi @HumbleBeeBumbleBee, @metanota 

3 years later - how are we doing Android-wise with this issue?
Just wanted to highlight that this issue prevents users from properly scrobbling albums with various artists, such as Double Fantasy ([1](https://www.last.fm/music/John+Lennon/Double+Fantasy) or [2](https://www.last.fm/music/Various+Artists/Double+Fantasy)), among many others.

**Comment by EvilBollWeevil** [comment]
@metanota 
> 
> I've checked several android music players and didn't found one that could send info about both 'ARTIST' and 'ALBUMARTIST' tags. So it seems to be undoable feature for now from my point of view. Discuss :)

There are many. Google Play Music, Poweramp, Medoly to name a few. AIMP's developer says that SLS doesn't ask ALBUMARTIST tag and that is why AIMP doesn't send it.
Also, there are scrobblers, that scrobble this tag correctly, but there aren't many. Scroball does with Poweramp and GP Music. But it is still very unstable and it's a pain to use it.
There is an almost unknown and very simple player called Medoly which can scrobble through a plug-in. And this is most stable player/scrobbler bundle I've ever used to use. I've scrobbled dozens of Various Artists albums with Medoly and it didn't lose any scrobble. The only problem is that it don't have any sound effects and pretty complicated to navigate.
So, there IS a way to scrobble ALBUMARTIST tag correctly

**Comment by a93-39a** [comment]
@EvilBollWeevil 

I will implement the feature. Afterwards, it will be up to them to implement album_artist broadcasts.

**Comment by EvilBollWeevil** [comment]
Thanks. As far as I know, AIMP already imlemented it.

**Comment by a93-39a** [comment]
Ok it's going to be available in the next release.
I fixed the API.

I used Orange Squeeze to test and verify it's functionality.
https://www.orangebikelabs.com/products/orangesqueeze/broadcast-intents
