### ISSUE TITLE
Scrobbler doen't recognize apps

### ISSUE THREAD

**Issue by darkravenann** [tgwizard/sls#121]
On play market it is said that both Vanilla Music Player and Poweramp are supported, but the scrobbler doesn't recognize that they are installed on my device and play music at all.  It will only scrobble from default player which I hate using. Scrobbler v1.4.6, Vanilla Music v0.9.23, Poweramp v2.0.9 full. Hope you can solve the issue somehow.

**Comment by HumbleBeeBumbleBee** [comment]
@darkravenann did @tgwizard  resolve this for you?

**Comment by HumbleBeeBumbleBee** [comment]
VLC supports scrobbling now too, in case you prefer a good open source alternative.
