### ISSUE TITLE
SLS does not recognize Google Play Music app

### ISSUE THREAD

**Issue by TAKosice** [tgwizard/sls#123]
I have installed Google Play Music app and then SLS. But SLS says that only 1 music app is detected and does not recognize Google Play Music. In list of known apps only Android Music Player stands (and this is not installed).
Google Play Music version is 5.4.1409N.1014766.
Android version: 4.0.3.

**Comment by HumbleBeeBumbleBee** [comment]
Please continue discussing this in #94

**Comment by HumbleBeeBumbleBee** [comment]
@TAKosice are you reporting Google Play Music not working?

**Comment by HumbleBeeBumbleBee** [comment]
Please continue discussion in #200
