### ISSUE TITLE
Ignores some songs

### ISSUE THREAD

**Issue by tugboatcaptain** [tgwizard/sls#129]
When playing music some songs will be sent to the scrobble cache/scrobbled, other songs won't. It's not always the same songs that get ignored, it appears to be random. It makes it kind of useless. Worked just right until a few weeks ago. Tried updating and reinstalling. I'm using the default android music player on an android 2.3.7 device.

**Comment by HumbleBeeBumbleBee** [comment]
@tugboatcaptain 
If you could build and test https://github.com/tgwizard/sls/tree/testing-149
That would be great.
Otherwise, I can email you the .apk or host it somewhere where you could download, install and Test it!
Thanks!

**Comment by HumbleBeeBumbleBee** [comment]
@tugboatcaptain 
https://drive.google.com/file/d/0B9lPaMaVVtiJYTVVVDR4YkU1QUU/view?usp=sharing
This is a beta testing version. Let me know if it solves your problem.
It has a different key so you'll have to uninstall and setup SLS again.

**Comment by HumbleBeeBumbleBee** [comment]
Has this issue been resolved?
Lost scrobbles are because
* Metadata is wrong
* Time is wrong
* Track was scrobbled too late
or something is wrong with the app.

**Comment by HumbleBeeBumbleBee** [comment]
http://www.last.fm/group/Universal+Scrobbler/forum/117620/_/2067597

**Comment by HumbleBeeBumbleBee** [comment]
Try this version.

https://drive.google.com/open?id=0B9lPaMaVVtiJaGwwdkt0UjBNVHc

I am going to close this issue for now.
