### ISSUE TITLE
add support for Andrew Apollo

### ISSUE THREAD

**Issue by SHMAUS-Carter** [tgwizard/sls#131]
Scrobbleing with Apollo is very hit/miss it often gets the now playing but hardly ever Scrobbles.

**Comment by HumbleBeeBumbleBee** [comment]
Is this Apollo with CyanogenMod CM ?
If so could you please share some more detailed information.
* Phone
* CM/android version
* SLS version
* Music App & version

Is there anything common about when SLS does scrobble (or does not scrobble). 
Anything that is obvious to you?

https://drive.google.com/file/d/0B9lPaMaVVtiJYTVVVDR4YkU1QUU/view?usp=sharing
This is a beta testing version. Let me know if it solves your problem.
It has a different key so you'll have to uninstall and setup SLS again.

**Comment by SHMAUS-Carter** [comment]
https://f-droid.org/repository/browse/?fdfilter=apollo&fdcategory=Multimedia&fdid=com.andrew.apollo
