### ISSUE TITLE
add support for Beats Music

### ISSUE THREAD

**Issue by lorddev** [tgwizard/sls#132]
Beats is not supported. Nothing shows up in the scrobble cache/history.

**Comment by HumbleBeeBumbleBee** [comment]
@lorddev Could you specify the application?

**Comment by HumbleBeeBumbleBee** [comment]
@lorddev I assume this is the app you are referring to [Beats Music](https://play.google.com/store/apps/details?id=com.beatsmusic.android.client) ?

**Comment by HumbleBeeBumbleBee** [comment]
I have sent an email to support@beatsmusic.com requesting they broadcast song information so SLS can scrobble music played in Beats Music.
