### ISSUE TITLE
Support n7player

### ISSUE THREAD

**Issue by duszek00** [tgwizard/sls#14]
Please add support for n7player:
https://play.google.com/store/apps/details?id=com.n7mobile.nplayer&feature=search_result#?t=W251bGwsMSwxLDEsImNvbS5uN21vYmlsZS5ucGxheWVyIl0.

**Comment by HumbleBeeBumbleBee** [comment]
n7player supports scrobbling 
`Options>Playback` `Turn on scrobbling (check)`
`Options>Playback>Choose scrobbler>Simple Last.fm`
