### ISSUE TITLE
Support 8tracks

### ISSUE THREAD

**Issue by stacia** [tgwizard/sls#142]
Would love to scrobble from 8tracks. I can see the tracks playing on my lockscreen so it's probably exposing some things you could use.

**Comment by inverse** [comment]
This should be closed - see #167

**Comment by HumbleBeeBumbleBee** [comment]
I cannot confirm this.
8tracks is working on Samsung S5 SLS v.1.4.8.
<3 8tracks :) new music, easy on the processor, scrobbles :)

@stacia Have you tried 8tracks? Does SLS report your 8tracks listening habits?
Otherwise, please close.
