### ISSUE TITLE
Certain track frequently scrobbling incorrectly

### ISSUE THREAD

**Issue by bannus** [tgwizard/sls#145]
I've been using this app for several years, and I've noticed a strange bug. A certain track (Saint Christopher by Bibio) gets scrobbled at random times when I'm not listening to music. I would guess it happens once every few weeks. Unfortunately, I had built up so many plays of this song (~50?) that I deleted most of the scrobbles from [my last.fm](http://www.last.fm/user/bannusv/library/music/Bibio/_/Saint+Christopher).

It just happened again this morning before I woke up. Are there any logs I can find to see why SLS thinks this track should be scrobbled?

**Comment by bannus** [comment]
Haven't tested this extensively, but it seems to happen immediately when my phone restarts. I just restarted my phone, and as soon as it powered on, I saw the 'now listening' notification on my last.fm page.

**Comment by HumbleBeeBumbleBee** [comment]
@inverse Does @metanota 's #149 fix this?

**Comment by HumbleBeeBumbleBee** [comment]
@bannus 
If you know how download and build the .apk
Please use this branch https://github.com/tgwizard/sls/tree/testing-149
Otherwise you can use the latest .apk here.
https://drive.google.com/file/d/0B9lPaMaVVtiJLVlLendjSmxRZDA/view

**Comment by bannus** [comment]
Unfortunately my Android phone broke and I'm using an old iPhone, so I can't try out the fix. Additionally, looking at the description, it doesn't seem obvious to me that the fix would be related to this problem.

**Comment by HumbleBeeBumbleBee** [comment]
Thanks @bannus, if you get a new Android maybe you could try it.
So far it is about 50/50 for people testing our updates.
One user reports that it fixed their issue, another reports that it made it worse.

**Comment by HumbleBeeBumbleBee** [comment]
For anybody who has a similar problem.
https://drive.google.com/file/d/0B9lPaMaVVtiJYTVVVDR4YkU1QUU/view?usp=sharing
This is a beta testing version. Let me know if it solves your problem.
It has a different key so you'll have to uninstall and setup SLS again.

**Comment by HumbleBeeBumbleBee** [comment]
The latest version can be found here https://github.com/tgwizard/sls/releases/tag/v1.4.9
It will include fully working Spotify support on 8/11/2015.

**Comment by HumbleBeeBumbleBee** [comment]
I just realized this is a duplicate. Please continue discussion in #79.
