### ISSUE TITLE
Remove markers/flags from album name

### ISSUE THREAD

**Issue by jeofrey** [tgwizard/sls#146]
Hi,

If album name has flags/markes with chars []()...
e.g.
- Let It Be [REMASTERED][FLAC][88Khz-24bit]
- Let It Be [CD]
- Let It Be [HD]

then those flags are scrobbling to server.

Is it possible to implement some simple user defined filter rules to remove album flags and scrobble only album name?

**Comment by HumbleBeeBumbleBee** [comment]
If it's local music I would suggest https://picard.musicbrainz.org/
Otherwise, your issue will be considered as a `feature` soon.

**Comment by metanota** [comment]
Currently album's name value to scrobble takes from the "album" tag, so either you should properly name your albums as @HumbleBeeBumbleBee proposed or name the app name that scrobbles online albums in that way.

I don't think that allowing to define a custom filter rules by users is the good idea.

**Comment by HumbleBeeBumbleBee** [comment]
I will be closing this issue soon @jeofrey.
It's great that you're sharing your ideas though. Thank you!
>If it's local music I would suggest https://picard.musicbrainz.org/
If you like streamed music I'd suggest 8tracks. New music, customizable, easy on the processor, scrobbles.
