### ISSUE TITLE
add support for Subsonic

### ISSUE THREAD

**Issue by HeadcaseFargone** [tgwizard/sls#147]
Any chance of added support for the Subsonic client?

https://play.google.com/store/apps/details?id=net.sourceforge.subsonic.androidapp

**Comment by HumbleBeeBumbleBee** [comment]
I have sent an email to both email adresses on Google Play requesting they broadcast song information so SLS can scrobble music played in each of their Android apps.

**Comment by daneren2005** [comment]
Is there any reason to have this?  DSub already has an option to submit to Last.FM via Subsonic as well as there is a Last.FM app which will scrobble as DSub plays.  Also I'm not sure what broadcasts you are looking for as I already am broadcasting DSub specific ones and the generic media players ones.

**Comment by HumbleBeeBumbleBee** [comment]
@HeadcaseFargone @radiosilence You have an official message from the developer! (A somewhat rare occurrence for SLS.)

**Comment by daneren2005** [comment]
Ah, so is Libre.FM support what you guys want from this?

**Comment by HeadcaseFargone** [comment]
I wasn't aware of DSub when I posted this request. I don't think it was so feature-rich back then anyway. I'm good now, thanks.

**Comment by HumbleBeeBumbleBee** [comment]
It seems mostly everybody is satisfied, so I will be closing the issue soon.

**Comment by HumbleBeeBumbleBee** [comment]
@HeadcaseFargone 
[subsonic-debug.zip](https://github.com/tgwizard/sls/files/369512/subsonic-debug.zip)
@radiosilence 
[DSub 5.1.9-debug.apk.zip](https://github.com/tgwizard/sls/files/369523/DSub.5.1.9-debug.apk.zip)

Try those.
