### ISSUE TITLE
add support for TuneIn

### ISSUE THREAD

**Issue by goodevilgenius** [tgwizard/sls#15]
Please add support for TuneIn Radio. (https://play.google.com/store/apps/details?id=tunein.player and https://play.google.com/store/apps/details?id=radiotime.player)

Most stations appear to report the currently playing track and TuneIn Radio displays it.

**Comment by NicoleTheLizard** [comment]
+1 for "Please add this."

**Comment by 1oh1** [comment]
Yeah, TuneIn support would be awesome. Currently I have to resort to Last.fm Scrobbler Chrome extension and stream TuneIn on the desktop to scrobble songs.

**Comment by spigot** [comment]
+1

**Comment by quasar** [comment]
Any news on that?

**Comment by HumbleBeeBumbleBee** [comment]
I contacted TuneIn support
android-support@tunein.com
>July 21
>Thank you for your email. This is a quick confirmation to let you know that we've received your email, and will be working as quickly as possible to get back to you. 

They still haven't got back to me.

**Comment by quasar** [comment]
I have an app that pushes songs titles from TuneIn well..into push messages. Don't you have access to that info too?

**Comment by HumbleBeeBumbleBee** [comment]
@oddtwelve I am not sure what you mean. Could you please explain a little more detail?

**Comment by oddtwelve** [comment]
Okay, I have this app on my phone and other devices
https://play.google.com/store/apps/details?id=com.pushbullet.android (not
advertising). It somehow gets "artist - title info" and makes a push
notification. I'm not too familiar with android platform, maybe I granted a
special permission for this app, but if they can. can't you get "artist -
title info"?

**Comment by HumbleBeeBumbleBee** [comment]
Yes, it's being considered, but here is link to a similar discussion.
https://github.com/tgwizard/sls/issues/87#issuecomment-98155075

**Comment by vladgolubev** [comment]
Any updates on the topic so far?

**Comment by HumbleBeeBumbleBee** [comment]
@vladgolubev Sorry, no. You can also send emails to them. There is only so much that can be done on this end.
