### ISSUE TITLE
Feature: scrobblings view

### ISSUE THREAD

**Issue by moshpirit** [tgwizard/sls#150]
Would be really nice if we could see our profile on the app and all our scrobblings.

**Comment by HumbleBeeBumbleBee** [comment]
https://play.google.com/store/apps/details?id=dan.wilkie.last.charts

Have you tried this app?
I think it's  good.
If SLS made one it would probably be a standalone app.

**Comment by HumbleBeeBumbleBee** [comment]
I have decided to close this for now. I may reopen it some day if somebody else asks for it too. However this is supposed to be a simple scrobbler. It has lots of support right now and that app above does everything you need.
