### ISSUE TITLE
Not working on Nokia X2_DS

### ISSUE THREAD

**Issue by danialbehzadi** [tgwizard/sls#153]
Nokia X2_DS is using the default android player (com.android.music) version 4.3, but SLS can not discover it. I tried to fully remove that and install vanilla version 4.2.2_r1.2 of the player from f-droid, but that doesn't help either. So I tried to install another music app and I installed "Just player" form f-droid which is told to be working with sls, but it couldn't detect that app too.

**Comment by HumbleBeeBumbleBee** [comment]
@danialbehzadi  have you tried Vanilla Music v.0.9.99 ?

**Comment by danialbehzadi** [comment]
The problem is actually resolved

After Adding an account, let the player play a track to the end and start playing the next song. if you let it done this without human interrupt, The SLS will start to scrobble from this second track..
Let's close this.
