### ISSUE TITLE
Songs won't scrobble on repeat 

### ISSUE THREAD

**Issue by babss92** [tgwizard/sls#155]
When I repeat songs on android L with google music player, the app does not scrobble the repeated songs. Is there a salution for this problem ?

**Comment by HumbleBeeBumbleBee** [comment]
#149 generally solves this problem. :)

**Comment by HumbleBeeBumbleBee** [comment]
@babss92
If you know how download and build the .apk
Please use this branch https://github.com/tgwizard/sls/tree/testing-149
Otherwise you can use the latest .apk here.
https://drive.google.com/file/d/0B9lPaMaVVtiJLVlLendjSmxRZDA/view

**Comment by HumbleBeeBumbleBee** [comment]
@babss92 
https://drive.google.com/file/d/0B9lPaMaVVtiJYTVVVDR4YkU1QUU/view?usp=sharing
This is a beta testing version. Let me know if it solves your problem.
It has a different key so you'll have to uninstall and setup SLS again.

**Comment by HumbleBeeBumbleBee** [comment]
Hello @dror3go 

There are two major issues with doing this and two major compatibility issues.

SLS provides support for a variety of applications.
OR
SLS provides support for single track repeat and more structured scrobbling.

Some of these applications don't share track duration (well).
and
Some of these applications don't tell SLS when the track is paused or completed, so SLS cannot find out when the track officially started or finished.

I am manually going through all the applications to see which ones don't work with a more compatible scrobbling service.

The Queue method works for now.

**Comment by HumbleBeeBumbleBee** [comment]
I have tested a few solutions for this problem, however most of them cannot be done with creating serious compatibility issues.

**Comment by HumbleBeeBumbleBee** [comment]
Try Shuttle Player!!!

**Comment by HumbleBeeBumbleBee** [comment]
Moving to #324 so users see this immediately  in bugs list.
