### ISSUE TITLE
Only scrobbles as active process? 

### ISSUE THREAD

**Issue by Sagehorn** [tgwizard/sls#158]
Is it normal that sls only scrobbles when it's opened manually as a task? I'd thought it would already work when activated in the player. But with google music player, shuttle or poweramp nothing happens. Is that a bug? Otherwise it would be cool if i could autostart sls. But thats doesn't seem possible too...

**Comment by tomchiverton** [comment]
This hint about making sure SLS is excluded from power management just like your music player could do with being in the app store description or something 
Been fighting this for a while on my Z1 with the stock player.

**Comment by HumbleBeeBumbleBee** [comment]
Hi @Sagehorn this is a more serious issue than I understood previously.
I'd like to implement this if possible.
Could you please share instructions for the manual solution and hopefully some pictures too. As many details as you can, please. 

If I can't implement this, I will need to find out what devices this bugs affects and notify users on github or Google Play who use these devices on how to manually fix the problem.
I will also add some documentations above the [Apps Section](https://github.com/tgwizard/sls#apps) in the README.md file.

**Comment by tomchiverton** [comment]
Android 4.x based instructions : http://developer.sonymobile.com/2013/11/26/power-management-explained-sony-xperia-z1-and-xperia-z-ultra/

**Comment by HumbleBeeBumbleBee** [comment]
So you had to add Simple Last.fm Scrobbler to the list of "Apps Active In Standby" ?

**Comment by tomchiverton** [comment]
Yup 
-- 
Tom
