### ISSUE TITLE
add support for ES Explorer

### ISSUE THREAD

**Issue by ghost** [tgwizard/sls#159]
add EZexplorer support

**Comment by HumbleBeeBumbleBee** [comment]
@Antinatalist could your provide a link to the application?
The closest I have found is https://play.google.com/store/apps/details?id=com.estrongs.android.pop
Is this what you meant?

**Comment by Antinatalist** [comment]
Yes, that is app i meant

**Comment by HumbleBeeBumbleBee** [comment]
I have sent an email to contact@estrongs.com requesting they broadcast song information so SLS can scrobble music played in ES for Android.

**Comment by Antinatalist** [comment]
and how about that now?

**Comment by Antinatalist** [comment]
Ive tested, ez explorer is not seen as supported player.

What file explorer with audio support is supported?

**Comment by Antinatalist** [comment]
any help?

**Comment by HumbleBeeBumbleBee** [comment]
They have yet to message me back.

**Comment by Antinatalist** [comment]
interesting :D
