### ISSUE TITLE
Last.fm profile doesn't receive sent data, "Scrobble Now Button"

### ISSUE THREAD

**Issue by zbycz** [tgwizard/sls#16]
harry121...@gmail.com wrote:

What steps will reproduce the problem?
1. Open pre-installed music player for Xperia/Android and play some titles
2. Send cached titles with simple lastfm scrobbler

What is the expected output? What do you see instead?
The app tells me that I am logged in with the right profile link and everything and displays my played songs in the statistics of lastfm but when I visit my profile the songs aren't there.

What version of the product are you using? On what operating system and
what device?
I am using the latest version and I have got a Sony Ericcson Xperia Arc S with Android 2.3 as operating system.

**Comment by HumbleBeeBumbleBee** [comment]
@zbycz Has this problem been fixed in the newest version? v1.4.8

**Comment by zbycz** [comment]
Sorry, I no longer use it.
