### ISSUE TITLE
add support for VK

### ISSUE THREAD

**Issue by mapcuk** [tgwizard/sls#160]
Is possible to add support of [vk.com app](https://play.google.com/store/apps/details?id=com.vkontakte.android)?
It is not a player itself, it's social network client for vk.com (50 000 000–100 000 000 installations)
People usually uses it also as a music player.
From comments of SLS on [Play](https://play.google.com/store/apps/details?id=com.adam.aslfms&reviewId=Z3A6QU9xcFRPSDRSazE2X3BZVkdYMV9yNC1FQXNTWGE4SkJzUldoRE5TeUc1bHpDZWtZMXJDczJzeUJNVk5ibmtib0J4aVp0ekZCZVhlUGJVYkRrS1FGZG9r) some users would be glad if vk.com is supported by SLS.

**Comment by HumbleBeeBumbleBee** [comment]
I have sent an email to support@vk.com requesting they broadcast song information so SLS can scrobble music played in VK for Android.

**Comment by 39dotyt** [comment]
Any updates relating this issue?

**Comment by HumbleBeeBumbleBee** [comment]
They haven't responded to my email. If you can find a better contact email other than google play I will use it.

**Comment by 39dotyt** [comment]
They have developers portal here https://vk.com/dev where there is a link for questions about applications: https://vk.com/support?act=new_app. Seems like you should be registered here to sent questions, so I have just send them a message with a link to this issue.

**Comment by 39dotyt** [comment]
@HumbleBeeBumbleBee seems like they have really stubborn support.

First of all they asked me to wait. So it was like they are going to discuss this with developers or with someone who is in charge. But later they answered that they **will** pass this request to the developers and maybe they will fulfill it. After this response the question was marked as resolved (by them, lol) and I am not able to leave any other comments to it now.

I hate stuff like this.

But the good news are: new major release is upcoming, so maybe broadcasting will actually be implemented. I see this as a very easy thing to do.

**Comment by HumbleBeeBumbleBee** [comment]
Not all the music App Developers are helpful about this. I have plenty of conversations that didn't go anywhere by contacting developer support via email.

It seems they have some kind of [API](https://vk.com/dev), maybe hope there for scrobbling.

**Comment by 39dotyt** [comment]
@HumbleBeeBumbleBee if i'm not mistaken, there is a documentation for their web-service API, not for the mobile application.

**Comment by HumbleBeeBumbleBee** [comment]
@39dotyt You are right... guess we just wait for them to add support.
