### ISSUE TITLE
HTTPS can be used in some literals

### ISSUE THREAD

**Issue by wolfmd** [tgwizard/sls#161]
Running a security scan against the source code of this project has shown that HTTP has been used where HTTPS can just as easily be implemented. This can be resolved by changing the 'http://' to 'https://' in the URL string literals. Using HTTPS increases the security of credentials transmitted between the device and server as well as guaranteeing there is no middle-man attacker feeding malicious data to the user. 

bcomtgwizardsls/src/com/adam/aslfms/service/NetApp.java:29:
bcomtgwizardsls/src/com/adam/aslfms/service/NetApp.java:33:

While not major in this project, it's still good code policy to move toward HTTPS-first design.

**Comment by HumbleBeeBumbleBee** [comment]
https://github.com/tgwizard/sls/blob/master/src/com/adam/aslfms/service/NetApp.java#L29
https://github.com/tgwizard/sls/blob/master/src/com/adam/aslfms/service/NetApp.java#L33
@wolfmd I think it's great you pointed this out. I will be sure to test and change it ASAP

**Comment by HumbleBeeBumbleBee** [comment]
Merged :)
