### ISSUE TITLE
How does scrobbling work while listening to multiple tracks in an interlaced way?

### ISSUE THREAD

**Issue by klint** [tgwizard/sls#163]
Hi all
I am listening to long podcasts with JRT RocketPlayer but there are some issues with scrobbling (podcasts are often not scrobbled). Before I go to the RocketPlayer team, I just would like to understand something.
Is the way the APIs work ok with listening to a part of a track, moving to another track, then resuming the first one, and at the end resuming the second one... for instance? (this is typically the way you listen to long podcasts...)
Or is it expected that tracks are being played in sequence (like for short songs)?
Thanks

**Comment by klint** [comment]
It depends on the instant when the player will send the COMPLETED status, right? As far as I understood, the player will do it either at the end of a track or when switching to another track. 
Maybe we have to ask the player dev to send a COMPLETED status for only at the end of the track, in case of a podcast. Then, the 4 minutes option could work (it only needs the last piece of listened podcast to be more than 4 minutes...). 
But in this case, how would the SLS API detect that it is a podcast?

**Comment by klint** [comment]
By the way, is the "maximum duration" of 4 minutes rule actually implemented in SLS? Because if it is already, then it could work just by asking the player to send the COMPLETED status only at the end of a track, couldn't it?
And if it isn't, maybe an option to enforce it could help?
By the way, happy new year to you all :)

**Comment by HumbleBeeBumbleBee** [comment]
@klint Is it scrobbling at 4 minutes? I have scrolled through the source but I didn't find anything about scrobbling after 4 minutes.
I think the 4 minute feature needs to be added.

**Comment by HumbleBeeBumbleBee** [comment]
https://github.com/tgwizard/sls/blob/118eb79c879440620c97235fd2462ab042d38767/app/src/main/java/com/adam/aslfms/service/ScrobblingService.java#L54
