### ISSUE TITLE
Doesn't always scrobble using PlayerPro

### ISSUE THREAD

**Issue by TASSDevon** [tgwizard/sls#164]
Android 4.3 on Sony Xperia SP
Latest version of PlayerPro (+ DSP Pack) and Simple Lastfm

I have no idea when exactly songs don't get scrobbled unfortunately. They do get "now listening" (as I can see in the simple lastfm app and on the lastfm website) but sometimes they don't get actually scrobbled, I tried changing the scrobble when @ X percent from 50 to 100 without much effect.

Some additional info:
- I use the lockscreen widget where I sometimes pause/resume and skip to a next track
- I have a homescreen widget which I sometimes use
- I sometimes select music from within the app
- I have the microservice running so music plays automatically when I connect to a BT device or insert a 3.5mm jack

Do tell me if you want me to test something, I'll be happy to help resolve this issue!

**Comment by HumbleBeeBumbleBee** [comment]
@TASSDevon Are you able to build and test the latest master? 
https://github.com/tgwizard/sls
Just provide an email otherwise. I can email you the .apk.

**Comment by HumbleBeeBumbleBee** [comment]
The should be fixed in the next version 1.4.9 once it's released.

**Comment by HumbleBeeBumbleBee** [comment]
@TASSDevon 
https://drive.google.com/file/d/0B9lPaMaVVtiJYTVVVDR4YkU1QUU/view?usp=sharing
This is a beta testing version. Let me know if it solves your problem.
It has a different key so you'll have to uninstall and setup SLS again.

**Comment by HumbleBeeBumbleBee** [comment]
The latest version can be found here https://github.com/tgwizard/sls/releases/tag/v1.4.9
It will include fully working Spotify support on 8/11/2015.

**Comment by HumbleBeeBumbleBee** [comment]
@TASSDevon The above link will give you the latest package for testing (.apk)
