### ISSUE TITLE
Not scrobbling all tracks in cache

### ISSUE THREAD

**Issue by marasm76** [tgwizard/sls#165]
I have been having this problem for some time now. I only scrobble when I am on wifi, so the scrobble cache gets rather large. I usually scrobble when I get between 200 and 400 tracks in the cache. I almost always check my last.fm account before and after scrobbling, to make sure they all made it. They usually don't all make it. I use Poweramp for my music on my Motorola Photon Q with Android 4.2.2 Cyanogenmod.

I just had 231 tracks in the cache, so I connected to wifi and scrobbled them. I checked my total play count before and after scrobbling, and after a little math I figured out only 129 made it to last.fm. I don't know where the other 102 tracks went, but they didn't get scrobbled.

Has anyone else had this problem? Is it a known problem? It's been happening to me for a year or two now, and I've finally had enough and decided to ask or point it out.

**Comment by glaeran** [comment]
I can confirm this for me. But also for some reason songs are not scrobbled at all. 

Short info about my device and bla bla. So I'm using HTC One M7 with PowerAMP as my music player. Music itself is pretty much something "daily" for me, so I assume at least ~100 scrobbles should be done daily. However, what I noticed today [will ofc try to update if problem presists] - all the scrobbles from today's morning simply doesn't exist on my LastFm profile. The earliest one from today is ~18.30 but I started to listen around ~17.50 (and for sure I didn't start with the track which is scrobbled at first place). Using standard settings on Scrobbler.

Also I'm using JuiceDefender to reduce the ammount of battery usage, so whenever I turn on the screen, net is started up, when screen goes dark - it goes off. SImple. Maybe App is trying to send the scrobbles while net is started up, but it doesn't detect while net goes off and simply moves on (so techincaly it's trying to scrobble, but since connection goes down it doesn't stop it and mark track as scrobbled).

Not sure about the logic of the program, but sounds like scrobbling using Wi-Fi is the only way for me atm to do it properly.

**Comment by glaeran** [comment]
Really fast update from me. So far I should've around 6 tracks in my scrobble list, but.. 

1) chosen manually from playlist not scrobbled
2) next one from the random list scrobbled (played in 100%)
3) after few tracks forwarded - next one played in around 98% wasn't scrobbled 
4) next ones where randomly (selected, forwarded, chose by PowerAMP) even they were played in 100%not scrobbled. 

I changed my settings a little bit allowing scrobbles to be passed only via WiFi,also my setting for song duration is 50%. In the time of problem I wasn't connected to any network. 

Looks like app has problems after choosing song manually or after forwarding. I'll put on some additional tests soon and let you know about the result.

**Comment by HumbleBeeBumbleBee** [comment]
Hi @marasm76. This is a serious bug. I don't usually store that many scrobbles on a device before scrobbling. I will try to mimic your problem and discern what is causing it.

Hi @glaeran, please continue to explain your issue. I don't really know how to replicate your issues yet. You could try changing in `Options>When to scrobble` as "When you press the scrobble now button"

**Comment by marasm76** [comment]
@HumbleBeeBumbleBee Thanks for looking into the problem. 

I'll provide an update.

For the last month or two I have been scrobbling at or below about 200 tracks. If I were to guess it would be on average around 150. I have not been having any dropped scrobbles. Each time I scrobble they all make it. To be honest I can't remember if the app updated, but I think it did, so I am not sure if the problem has been fixed.

Probably three months ago I did a sort of test or experiment. I scrobbled at 50, 100, 125, 150, 175, and 200 total tracks. I think I may have gone above 200, but I can't remember. I should have written down my results, but I am pretty sure the missing tracks problem was mostly above 175.

I am planning on letting the cache fill up again, as a sort of test to see if it has been fixed. The phone I use isn't used as a phone; its sole purpose in life is music playback. The only internet connection it has is when I turn the wifi on. I'd rather let the scrobble cache grow large and scrobble everything in one large chunk once or twice a month, rather than every week.

I'll put it on random for a day or two and get up to 300 and try to scrobble. I'll report back at the end of the weekend, if not sooner.

**Comment by HumbleBeeBumbleBee** [comment]
Hi @marasm76 it's great you are having less dropped scrobbles. So far in my testing I haven't had any dropped scrobbles. I will make the cache exorbitantly large and test what happens. 

I am also going to patch the following [line](https://github.com/tgwizard/sls/blob/master/app/src/main/java/com/adam/aslfms/service/NetApp.java#L29) to HTTPS which may help your scrobbles reach their destination.

You could connect your android device for debugging when you connect to wifi that would great!
[How to install and use adb Windows](http://www.howtogeek.com/125769/how-to-install-and-use-abd-the-android-debug-bridge-utility)
[How to install and use adb Windows xda-dev forums](http://forum.xda-developers.com/showthread.php?t=2141817)
[How to install adb Mac](http://esausilva.com/2010/10/02/how-to-set-up-adb-android-debug-bridge-in-mac-osx/)
I assume if you're using Linux or BSD or something else you know what to do (it's very similar to Mac), if not just ask me.
Using your native command-line run `adb logcat > logcat.txt`

Then you open up logcat.txt in a text editor and search for the TAG you are debugging.
Examples Search TAG:
[Scrobbler](https://github.com/tgwizard/sls/blob/master/app/src/main/java/com/adam/aslfms/service/Scrobbler.java#L52)
[NetworkWaiter](https://github.com/tgwizard/sls/blob/master/app/src/main/java/com/adam/aslfms/service/NetworkWaiter.java#L35)

If you know how to work with the source code you could review and add debugging notifications to a few other files ( [Networker](https://github.com/tgwizard/sls/blob/master/app/src/main/java/com/adam/aslfms/service/Networker.java#L37) [SLSNetManage](https://github.com/tgwizard/sls/blob/master/app/src/main/java/com/adam/aslfms/service/NetworkerManager.java#L34) ) just to be safe, but the two I listed above should provide enough information.

[ScrobbleDatabase](https://github.com/tgwizard/sls/blob/master/app/src/main/java/com/adam/aslfms/util/ScrobblesDatabase.java#L41)

Then you can copy and paste the list of found items here on GitHub.

**Comment by HumbleBeeBumbleBee** [comment]
Using Notepad++:
https://ghostbin.com/paste/3mwzo
437 tracks scrobbled and my play cound on last.fm jumped 437

**Comment by marasm76** [comment]
Over the weekend I accumulated 310 tracks in the scrobble cache. I connected to wifi, and attempted to scrobble. After checking the before and after results I found it had dropped 45 tracks. 

Over Sunday and Monday I accumulated 320 tracks. I connected to wifi, and attempted to scrobble. After checking the before and after results I found it had dropped no tracks at all.

I am almost certain I had a logcat running during both attempts. Definitely during the second no dropped tracks attempt. I was having some trouble during the first attempt.

Here's everything "scrobble" related in the logcat. 934 hits. I noticed some "clash" references. Not sure what they mean.

https://ghostbin.com/paste/jyzkn

**Comment by HumbleBeeBumbleBee** [comment]
I recently did a test with about 500 tracks and it dropped about 20... This is a known issue now. I will try to figure this out.

**Comment by marasm76** [comment]
I suppose that I am both glad that you @HumbleBeeBumbleBee have witnessed the problem first hand, and sad because it probably means some work must be done to figure out why it's doing what it's doing.

Unfortunately I cannot provide any logcat info, because the last three scrobble uploads have gone through without any dropped tracks. I did two separate scrobble uploads, each with 100 tracks, and I just did a giant one with 600 tracks. Like I said, it didn't drop any tracks. 

Not sure what to tell you. I am almost certain that the conditions for all my scrobbles are the same. Except for the 600 track one I just did. My laptop was tethered to my cell phone for internet, and it even stopped a few times when the cell lost signal. But it still uploaded all the tracks.

It almost seems random.

If I can be of more help don't hesitate to ask. If the logcat info would be helpful even if it didn't drop any tracks I can provide that too.

**Comment by marasm76** [comment]
I just did scrobble of 188 tracks. It lost 13. Here's everything related to "scrobble" in the logcat.

https://ghostbin.com/paste/3nef4

**Comment by serpent849** [comment]
That's kinda obvious, but are you aware that you can only scrobble what you listened no more than 2 weeks ago? So you can't really submit only once a month, more like 2-3 times.

**Comment by HumbleBeeBumbleBee** [comment]
I also reviewed the code and it seems if Last.fm drops a scrobble it's because something is wrong with the track information. This could be part of the problem.

**Comment by HumbleBeeBumbleBee** [comment]
#129
