### ISSUE TITLE
Multiple scrobbling in Lollipop

### ISSUE THREAD

**Issue by taninamdar** [tgwizard/sls#169]
One track is scrobbled multiple times since I've upgraded my Nexus 4 to lollipop. The track gets scrobbled 3-4 times when it is played only once. I use PowerAmp for playing music.

**Comment by inverse** [comment]
This happening with each song?

**Comment by taninamdar** [comment]
Yes, almost every track. Maybe 8 or 9 out of 10 tracks.

**Comment by psychoadept** [comment]
I'm having a similar problem, but on 4.4.4.  Songs are often scrobbling multiple times, especially if they get paused for a while.  Most of my plays/scrobbles are while driving, so I can connect this problem to songs that were paused when I stopped, and resumed when I got back in the car.  That's not the only case, though, just the most identifiable.  I see other threads about a similar problem with the last song in the queue, though that doesn't happen to me often as I have very long playlists.  I'm using GoneMad Music Player, if it matters.

**Comment by HumbleBeeBumbleBee** [comment]
I cannot confirm this problem (Lollipop 5.0 Galaxy Samsung S5), but I use the stock music player, Rdio and Spotify. I will test this soon and try for a fix. This pull may fix some things https://github.com/tgwizard/sls/pull/149.

**Comment by HumbleBeeBumbleBee** [comment]
@taninamdar 
@psychoadept 
If you know how download and build the .apk
Please use this branch https://github.com/tgwizard/sls/tree/testing-149
Otherwise you can use the latest .apk here.
https://drive.google.com/file/d/0B9lPaMaVVtiJLVlLendjSmxRZDA/view

**Comment by HumbleBeeBumbleBee** [comment]
@taninamdar 
@psychoadept 
https://drive.google.com/file/d/0B9lPaMaVVtiJYTVVVDR4YkU1QUU/view?usp=sharing
This is a beta testing version. Let me know if it solves your problem.
It has a different key so you'll have to uninstall and setup SLS again.

**Comment by HumbleBeeBumbleBee** [comment]
The latest version can be found here https://github.com/tgwizard/sls/releases/tag/v1.4.9
It will include fully working Spotify support on 8/11/2015.

**Comment by HumbleBeeBumbleBee** [comment]
There are two major issues with doing this and two major compatibility issues.

SLS provides support for a variety of applications.
OR
SLS provides support for single track repeat and more **structured scrobbling**.

Some of these applications don't share track duration (well).
and
Some of these applications don't tell SLS when the track is paused or completed, so SLS cannot find out when the track officially started or finished.

I am manually going through all the applications to see which ones don't work with a more compatible scrobbling service.

The Queue method works for now.

**Comment by HumbleBeeBumbleBee** [comment]
Please try this version.
https://drive.google.com/open?id=0B9lPaMaVVtiJaGwwdkt0UjBNVHc

**Comment by HumbleBeeBumbleBee** [comment]
@taninamdar @psychoadept is this still happening?
