### ISSUE TITLE
files on OTG drive not scrobbled

### ISSUE THREAD

**Issue by christianl74** [tgwizard/sls#170]
I'm using Music Folder Player with the "Emulate Android Player" option as a source for the scrobbles. Songs  played from the phone's internal SD are detected by SLS without problems. However, music on a hard drive that I mount via OTG cable is played back fine, but does not get scrobbled.

**Comment by HumbleBeeBumbleBee** [comment]
Hi @christianl74, I am not sure I can recreate that environment to test, but I will do my best to help you!

**Comment by HumbleBeeBumbleBee** [comment]
Hi @christianl74 as long as the tracks are being played and Music Folder Player is broadcasting the track information, it should work.
It's probably something to do with Music Folder Player not broadcasting the information to SLS when OTG is enabled.

**Comment by christianl74** [comment]
Hi @HumbleBeeBumbleBee, thanks, you might be right. I recently installed Lyrics Finder, and I see different behavior based on whether the song comes from internal storage ("Touch to see lyrics of <name of the song>") vs. when it comes from the hard drive ("Touch to see lyrics of <01_full_file_name.mp3>"). Music Folder Player also seems to display mp3 tags only for local file, so maybe that's the problem...

**Comment by HumbleBeeBumbleBee** [comment]
I guess you could try to contact Music Folder Player about this [help.zorillasoft@gmail.com](mailto:help.zorillasoft@gmail.com)
I already did. I will report back to you their response and likely close this issue when they respond.
There isn't much we can do on SLS' end. It's for ZorillaSoft to decide what to do about this issue/bug.

**Comment by HumbleBeeBumbleBee** [comment]
Quote from Zorillasoft.
>Thank you for the feedback.

> The player gets the track information from the Android. It doesn't extract this information directly from the files.
 Android only indexes local files. Therefore Android and the player don't have detailed information about the track.

> I'm sorry, but currently I can't fix that without high efforts.

I am going to close this issue, but if it is fixed at some point could you leave a comment on the closed issue or send me a quick email HumbleBeeBumbleBeeDebugs@gmail.com ?

**Comment by christianl74** [comment]
Hi @HumbleBeeBumbleBee, I wrote to them as well, and their explanation actually helped.There are a few apps that let you do a media scan of the mounted directories - media.Re.Scan (https://play.google.com/store/apps/details?id=com.house.noranuko.mediarescanner) worked fine for me. That fixed my problems with scrobbling, lyrics, and ID3 tags. I guess it's OK as long as the contents of the external mounts don't change too often. Looks like it survives unmounting and reboots.

Thanks for your help!
