### ISSUE TITLE
Annoying Popup When Spotify Changes Track

### ISSUE THREAD

**Issue by Electr0Fi** [tgwizard/sls#171]
I currently have SLS installed and am using it with PowerAmp (it's working flawlessly).
I also have Spotify installed and scrobble though the Spotify app itself.

Whenever I change song in Spotify and then 'minimise' the app, a few seconds later a notification is displayed in the status bar as follows: [Spotify Icon] [Song Name] - [Artist Name]. After about 2 seconds the text disappears and just the Spotify Icon remains. However when the text appear a small popup appears at the bottom of the screen that says:
```
MP:
com.samsung.music.metachanged
```
Two instances of this message appears, both for 3 seconds each. The first instance is displayed, then it appears to blink quickly or 'refresh' and is displayed again for 3 seconds.

I am using a LG G2 (D802) running the OptimusG3 ROM.
It appears to me related to the intent that Spotify uses when it changes a track to display the notification in the status bar.

It is being caused by SLS as the popup disappears when when I uninstall the app.
The popup still appears when I disable scrobbling from within in Spotify app.
The only app that I have selected to srobble from in the SLS settings is PowerAmp.
It does find 'Android Music Player' and 'Samsung Music Player' but both are unchecked.
I'm not sure why there is a 'Samsumg Music Player' installed on my LG phone, I'm assuming it came with the custom ROM or something. Perhaps the LG Music player is just a skinned version of the Samsung Music Player.

Is there any way to stop this popup from showing? 
I'd happily edit or modify SLS myself, but am unsure where to start.

**Comment by Electr0Fi** [comment]
So I downloaded a copy of the source and had a quick trawl though the code (not that I know Java, but anyway).

The popup (actually a Toast notification) is being triggered by a line of code in the 'SamsungMusicReceriver.java' file. Specifically line 48.
```
45 | @Override
46 | protected void parseIntent(Context ctx, String action, Bundle bundle)
47 |		throws IllegalArgumentException {
48 |	Toast.makeText(ctx, "MP: " + action, Toast.LENGTH_LONG).show();
49 |	super.parseIntent(ctx, action, bundle);
50 | }
```
Like I said, I don't know Java, but I'm unsure as to why this part of the program is being called.

**Comment by HumbleBeeBumbleBee** [comment]
I understand your pain. That would make me crazy!
I think the code should be switched from a make Toast to Log.error.
```
45 | @Override
46 | protected void parseIntent(Context ctx, String action, Bundle bundle)
47 |        throws IllegalArgumentException {
48 |    Log.e(ctx, "MP: " + action);
49 |    super.parseIntent(ctx, action, bundle);
50 | }
```
That should help,
I'll see what I can do about it, but you probably could build your own SLS for the time being.
@tgwizard hasn't been administering this project for a while.

**Comment by Electr0Fi** [comment]
@HumbleBeeBumbleBee Thanks for fixing this issue. Do you know when the latest version on GitHub will be pushed to Google Play so I can update it?

**Comment by HumbleBeeBumbleBee** [comment]
Not very soon I am afraid, I have been tracking some bug issues with the current version.
1.4.9 Won't be released until everyone agrees that it's working flawlessly. :)
I can host an .apk signed by me if you want a version you can test for us.
https://drive.google.com/file/d/0B9lPaMaVVtiJLVlLendjSmxRZDA/view
Note: that version does not contain support for Spotify or SoundCloud.
It contains your patch and a patch for wifi scrobbling and single track on repeat scrobbling.
`testing pull $149`
Unfortunately during my testing of the `master` it seems one of these patches is buggy.

**Comment by inverse** [comment]
@HumbleBeeBumbleBee Will test out the latest build from master tonight. 

So you reverted all the changes from #149? What was causing the problem?

 Did you know you you can revert the change with git instead of manually doing it? e.g. `git revert <commit>` which in this instance would have been `git revert a05c68766b8bd54097603fc7744ae9918575e892`

Alternatively you could use a git GUI like SourceTree to make it easier, although it's still good to learn the commands ;) I'm still learning :D

**Comment by HumbleBeeBumbleBee** [comment]
Yeah, I am a manual git monkey and it leaves the project tree looking pretty ugly.
Yes, @metanota is smart and I was really hoping the changes @metanota made would have worked.
SoundCloud and Spotify still work though.

**Comment by Electr0Fi** [comment]
@HumbleBeeBumbleBee, thanks for that. I'll grab that APK and try it out. Spotify had its own scrobbling capability so not too worried about that. I just really wanted the toast gone haha.
