### ISSUE TITLE
Add vlc support 

### ISSUE THREAD

**Issue by muzaboz** [tgwizard/sls#172]

**Comment by muzaboz** [comment]
Add vlc support

**Comment by tomchiverton** [comment]
+1

**Comment by osakechan** [comment]
Please support VLC!

**Comment by HumbleBeeBumbleBee** [comment]
I agree but VLC might want to have it's own last.fm scrobbler like the desktop versions.
They don't seem to interested in adding libre.fm support for the desktop versions either.

**Comment by HumbleBeeBumbleBee** [comment]
Frome #144 
adb shell dumpsys activity broadcasts
'''
Filter #0: BroadcastFilter{1409067b}

      Action: "org.videolan.vlc.remote.Backward"

      Action: "org.videolan.vlc.remote.PlayPause"

      Action: "org.videolan.vlc.remote.Play"

      Action: "org.videolan.vlc.remote.Pause"

      Action: "org.videolan.vlc.remote.Stop"

      Action: "org.videolan.vlc.remote.Forward"

      Action: "org.videolan.vlc.remote.LastPlaylist"
'''

**Comment by HumbleBeeBumbleBee** [comment]
Duplicate #126

**Comment by HumbleBeeBumbleBee** [comment]
As of [version 1.3.2](https://play.google.com/store/apps/details?id=org.videolan.vlc)
VLC now supports audio scrobbling.

**Comment by Antinatalist** [comment]
I cant scrobble on cm 11 and newest vlc android

**Comment by HumbleBeeBumbleBee** [comment]
Please  check your battery settings. I will look into the cm 11.

**Comment by HumbleBeeBumbleBee** [comment]
I'm using cm 14 and it works.

**Comment by HumbleBeeBumbleBee** [comment]
Do you know how to debug?

**Comment by HumbleBeeBumbleBee** [comment]
VLC 1.9.0?

**Comment by HumbleBeeBumbleBee** [comment]
I just tested on cm 11. It works.

**Comment by Antinatalist** [comment]
Vlc 2.0.6

**Comment by Antinatalist** [comment]
Cm 11.0
Android 4.4.4

**Comment by Antinatalist** [comment]
Dont know how to debug

**Comment by HumbleBeeBumbleBee** [comment]
Have you tried enabling "OnGoing" (w/ phone notifications)?

**Comment by Antinatalist** [comment]
yes, i have tried. nothing happened.

**Comment by HumbleBeeBumbleBee** [comment]
Does your version of CM use intent filters?

**Comment by Antinatalist** [comment]
whats that?

**Comment by Antinatalist** [comment]
maybe to make this discussion short, i just need player which can support speed playing and is supported by  SLS. do you know any?

**Comment by HumbleBeeBumbleBee** [comment]
Speed playing defeats the scrobbling system. You need to play half the song at regular speed.

**Comment by Antinatalist** [comment]
interesting o hear that. but even if i play at normal speed with VLC android, SLS doesnt scrobble.

**Comment by Antinatalist** [comment]
intent filters - i will ask again. whats that?

**Comment by HumbleBeeBumbleBee** [comment]
VLC broadcasts track information using intents and SLS picks them up.

**Comment by Antinatalist** [comment]
i probably dont care if not or if yes
how can i enable them?
