### ISSUE TITLE
Synology DS Audio Player

### ISSUE THREAD

**Issue by brogalski** [tgwizard/sls#174]
Im not sure this is even possible but player support for synologys ds audio player would be awesome.

**Comment by HumbleBeeBumbleBee** [comment]
#174 #97 #2 
Triplicate :) 
I going to try and work on it.

**Comment by brogalski** [comment]
Thank you for trying to make this work, good luck!

**Comment by HumbleBeeBumbleBee** [comment]
You are welcome !!! :)
@brogalski 
but please continue discussion in #2.
Thank you.
