### ISSUE TITLE
Doesnt detect PlayerPro

### ISSUE THREAD

**Issue by wilspi** [tgwizard/sls#176]

**Comment by HumbleBeeBumbleBee** [comment]
@metanota should have some explanation for you. 
I am trying to go through all SLS issues right now @metanota , maybe you could help me with this one.
Otherwise @wilspi I will do my best to fix your problem, maybe spend the $4.50 to try a new player. (I don't usual spend money on apps :)

**Comment by metanota** [comment]
Comparing my PR https://github.com/metanota/sls/commit/1b878151687a8083f7efb7a0185a336c3f5d8c57 and it's merge https://github.com/tgwizard/sls/commit/c972ac742b1243e33670fdaaf6c9b56af17c38c6 it's easy to see that the android manifest was not updated to handle intents from the full version of Player Pro. I've created the PR https://github.com/tgwizard/sls/pull/185 that should fix this issue.
