### ISSUE TITLE
Rdio not scrobbling all plays CLOSED

### ISSUE THREAD

**Issue by HumbleBeeBumbleBee** [tgwizard/sls#178]
SLS v1.4.8
Rdio Version 3.0.1.151 (Rdio is also buggy, music plays but app User Interface shuts down sometimes)
Android version 5.0 (lollipop)

SLS does not consistently scrobble all Rdio plays.

**Comment by longloop** [comment]
For me rdio scrobbles have been consistent. Can you share device info?

**Comment by HumbleBeeBumbleBee** [comment]
Samsung Galaxy S5. I just did a fresh install of Rdio, and everything seems to be working now.
I am not sure what was causing the problems before...
May have been a bug with Rdio not SLS.
