### ISSUE TITLE
SLS Now Playing Seems to 'Stick' from PowerAmp

### ISSUE THREAD

**Issue by CardcaptorRLH85** [tgwizard/sls#179]
When I stop a track in PowerAmp, SLS keeps sending a 'Now Playing' notification for that track until I kill PowerAmp completely.  I didn't notice until I tried scrobbling from another device and got an 'invalid session ID' error there.

Device: Sprint Galaxy Nexus [toroplus]
ROM: Unofficial CyanogenMod 12.0 beta [Android 5.0.1]

**Comment by HumbleBeeBumbleBee** [comment]
@CardcaptorRLH85 
If you know how to download and build the .apk
Please use this branch https://github.com/tgwizard/sls/tree/testing-149
Otherwise you can use the latest .apk here.
https://drive.google.com/file/d/0B9lPaMaVVtiJLVlLendjSmxRZDA/view
Let me know if that solved your problem. :)

**Comment by CardcaptorRLH85** [comment]
That seems to have fixed the issue. Thanks ^_^

**Comment by HumbleBeeBumbleBee** [comment]
Thanks for your feedback @CardcaptorRLH85

**Comment by HumbleBeeBumbleBee** [comment]
@CardcaptorRLH85 
This version removes buggy SoundCloud support. If your willing to reinstall please help us test our latest updates.
https://drive.google.com/file/d/0B9lPaMaVVtiJYTVVVDR4YkU1QUU/view?usp=sharing
This is a beta testing version. It has a different key so you'll have to uninstall and setup SLS again.
If you find any problems, please report them. Thanks!

**Comment by HumbleBeeBumbleBee** [comment]
The latest version can be found here https://github.com/tgwizard/sls/releases/tag/v1.4.9
It will include fully working Spotify support on 8/11/2015.
