### ISSUE TITLE
Scrobbling to to other GnuFM servers

### ISSUE THREAD

**Issue by goodevilgenius** [tgwizard/sls#18]
Libre.fm is built on software called GNU FM. It's designed to be compatible with Last.fm. Since SLS supports libre.fm, support for custom GNU FM servers could be added by simply adding in a URL parameter to LibreFM so that scrobbles could be submitted somewhere other than turtle.libre.fm.

**Comment by HumbleBeeBumbleBee** [comment]
I'll have a hack at this ASAP.

**Comment by HumbleBeeBumbleBee** [comment]
I need to get a server going to test this.

**Comment by HumbleBeeBumbleBee** [comment]
A developer has added this feature #304
