### ISSUE TITLE
LG G2 music player doesnt work

### ISSUE THREAD

**Issue by obama** [tgwizard/sls#180]
com.lge.music

**Comment by HumbleBeeBumbleBee** [comment]
https://github.com/tgwizard/sls/blob/master/src/com/adam/aslfms/receiver/LgOptimus4xReceiver.java
Must be something different about the intents for LG G2 music player.
I'd try to help you, but I don't have that phone.

**Comment by obama** [comment]
i have no idea of android coding :/ how can i find out those events/message
names?

**Comment by obama** [comment]
ok i did the lollipop update and there it works.
