### ISSUE TITLE
HTTPS Literals continued

### ISSUE THREAD

**Issue by HumbleBeeBumbleBee** [tgwizard/sls#186]
Does anybody have a solution for 
https://github.com/tgwizard/sls/blob/master/src/com/adam/aslfms/service/NetApp.java#L32
I'd like to add
https://turtle.libre.fm/?hs=true
but it doesn't seem like it works with SLS.

**Comment by inverse** [comment]
Looks like a certificate issue. Perhaps we should contact libre.fm to update their certificate to cover their srobbling endpoint correctly.

**Comment by HumbleBeeBumbleBee** [comment]
I have been noticing that some scrobbles are not recorded, I am thinking about reverting the changes to the NetApp.java I made early. maybe just https for the user names.

**Comment by inverse** [comment]
Perhaps checking LogCat to see what temp exceptions are being thrown when trying to handshake. See: https://github.com/tgwizard/sls/blob/master/src/com/adam/aslfms/service/Handshaker.java#L140



Also I'd say also merge down `ClientProtocolException` and `IOException` on https://github.com/tgwizard/sls/blob/master/src/com/adam/aslfms/service/Handshaker.java#L267 as they are both doing the same and redundant. 

See: https://developer.android.com/reference/org/apache/http/client/ClientProtocolException.html

**Comment by HumbleBeeBumbleBee** [comment]
I think I'll wait until the next version to push this.

**Comment by inverse** [comment]
When are you planning the next release?

**Comment by HumbleBeeBumbleBee** [comment]
Hopefully soon, what do you think. I have three devices at home and I have been testing.

**Comment by inverse** [comment]
I've not had a chance to test anything recently. I'll pick up a build now and run with what's on master :+1:

**Comment by HumbleBeeBumbleBee** [comment]
Try https://github.com/tgwizard/sls/tree/testing-149
