### ISSUE TITLE
To All Major Contributors!!! Android Studio vs. Eclipse

### ISSUE THREAD

**Issue by HumbleBeeBumbleBee** [tgwizard/sls#188]
@tgwizard has made the suggestion that we switch development of SLS from Eclipse to Android Studio
This will make it easier for @tgwizard and presumably, all of us too.

@Argoday @inverse @luisbandalap @metanota 

We may have to drop the "sls_test" portion of the project, unless someone knows how to migrate it.
I already migrated and tested SLS in Android Studio.

I simple yes or no would be great.

I vote yes in hopes that it will make it easier for @tgwizard to contribute.

**Comment by inverse** [comment]
Works for me.is it worth getting all the current pull requests merged before though?

**Comment by HumbleBeeBumbleBee** [comment]
Yes, I am working on merging three major pull requests. 
#149  #149
#101
@inverse Do you like #50 request? I am not sure what to do about it.

**Comment by luisbandalap** [comment]
I agree on switching to Android Studio, it works well enough.
@HumbleBeeBumbleBee you could take a look at my fork, i already merged that commits without making so much changes.

**Comment by HumbleBeeBumbleBee** [comment]
Well, that's 3 against 2, so I guess we will be migrating. :)
@luisbandalap Are you 100% sure #149 and #110 are good and working?
I have read your comments and you seem certain.

**Comment by luisbandalap** [comment]
Yes, indeed #110 is a must merge. I use my own fork saily and I don't have any problem with them.

Well maybe some conflicts when and music app (like poweramp) exposes both their API and Android Music Player API to SLS (some tracks are scrobbled earlier, some others doesn't), but i'm not sure it is because of  #149.

**Comment by HumbleBeeBumbleBee** [comment]
@bryansills Thanks for the quick change, but we're going to merge some pull requests first.

**Comment by bryansills** [comment]
#101 shouldn't be merged. That icon is outdated.

Also, mention me again when you are done with the merges. Android Studio is working for me (at least building the app), so I could probably send a pull request then. But I did kinda force the changes through git. Someone could probably make the changes more correctly than me. :0

**Comment by tgwizard** [comment]
First, I must apologize to everyone that I haven't been here to maintain SLS properly. I'm truly sorry.

I really appreciate all the work you have put into SLS, with bug fixes, issues, pull requests and more. I know many people are using SLS (more than 500K downloads so far) and that you would like it to continue to become better. For me, I'd really like it if SLS could live on without me taking a too active role in its development.

I've given @HumbleBeeBumbleBee full access to the repository. I'm very much open to adding more of you as contributors. I'm happy to sign and upload new versions of SLS to Google Play, and, if wanted, answer questions and take part in discussions, perhaps even review code.

@HumbleBeeBumbleBee @inverse @metanota @bryansills @luisbandalap and others, great work so far, and a huge thank you for picking up the torch.

Humbly,
Adam

**Comment by metanota** [comment]
Feel free to migrate on whatever you want. I'm using Intellij Idea and I'll stay with it since it works perfectly with android applications and doesn't affects any of developers nor development processes.

Many thanks to @HumbleBeeBumbleBee who had literally awaken me (and probably not only me) from sleep with the recent activity :)

I would also like to see #149 to be *extremely* well tested before merging and hope that some of you has already tried to use it in the field.

**Comment by HumbleBeeBumbleBee** [comment]
Thanks everyone! Please download and test the latest pull #149. And post working applications in the dialogue for #149.

**Comment by HumbleBeeBumbleBee** [comment]
There is also https://github.com/tgwizard/sls/blob/master/IssueSummary.md
which I hope some contributors might consider adding support.
I'll be working on Spotify and VLC support for now.

**Comment by inverse** [comment]
@tgwizard First off, thanks for allowing other people to contribute with this awesome project you've created. I can imagine it must have been time consuming trying to keep on top of this considering how actively used it is. :+1: 

@HumbleBeeBumbleBee You've been going super crazy with trying to bring order to the this project with PR's, Issues, and collating data from the app store! well done :dancer: 

I'd like to get involved more too although I feel these coming weeks might be a bit busy as I'll be starting a new job on Monday although perhaps in the evenings I'll have some time!

**Comment by inverse** [comment]
@HumbleBeeBumbleBee what problems are you having importing the `sls_test` project into Android Studio? When I did an import from an eclipse project it looks like everything went as expected. Aside some files it said were not copied and will need to be manually done.

**Comment by Argoday** [comment]
+1 for Android Studio - they've made a lot of good progress over the eclipse version

Thx to @HumbleBeeBumbleBee for the activity!
