### ISSUE TITLE
Scrobble Tracks After 4 minutes

### ISSUE THREAD

**Issue by HumbleBeeBumbleBee** [tgwizard/sls#189]
>A track should only be scrobbled when the following conditions have been met:

>* The track must be longer than 30 seconds.
>* And the track has been played for at least half its duration, or for 4 minutes (whichever occurs earlier.)

>http://www.last.fm/api/scrobbling

For example 
>Some SoundCloud tracks are a couple hours long.

**Comment by prakharsingh95** [comment]
Doesn't SLS do this already? I am interested in implementing otherwise.

**Comment by HumbleBeeBumbleBee** [comment]
@prakharsingh95 No, I don't believe SLS does this already, I have look through the code some. 

Please, fork and code away! :+1:

**Comment by HumbleBeeBumbleBee** [comment]
https://github.com/tgwizard/sls/blob/118eb79c879440620c97235fd2462ab042d38767/app/src/main/java/com/adam/aslfms/service/ScrobblingService.java#L54
