### ISSUE TITLE
Create Gitter or IRC

### ISSUE THREAD

**Issue by inverse** [tgwizard/sls#192]
Perhaps we could create a [gitter][0] channel for ad-hock non issue related discussions. Either that or an IRC channel like `sls-android` on freeenode. What do you think?

[0]: https://gitter.im

**Comment by HumbleBeeBumbleBee** [comment]
I like it.

**Comment by inverse** [comment]
You can even link gitter in the readme like: https://github.com/rocketeers/rocketeer

**Comment by HumbleBeeBumbleBee** [comment]
Ok I created it...
Now I have to add information to the readme.md

**Comment by HumbleBeeBumbleBee** [comment]
Do you want to do both or just https://gitter.im/tgwizard/sls ?

**Comment by HumbleBeeBumbleBee** [comment]
Ok all done :)
