### ISSUE TITLE
1.4.9 APK?

### ISSUE THREAD

**Issue by matachi** [tgwizard/sls#197]
I see that version [1.4.9 has been released](https://github.com/tgwizard/sls/blob/master/app/src/main/assets/changelog.txt). However, the [most recent APK is 1.4.8](https://github.com/tgwizard/sls/releases). Version 1.4.8 is also what's available on [F-Droid](https://f-droid.org/repository/browse/?fdid=com.adam.aslfms).

Are there any plans to build an APK for version 1.4.9?

**Comment by HumbleBeeBumbleBee** [comment]
Hi @matachi there are still some bugs to be worked out. We will ask @tgwizard to build 1.4.9 when it is ready. Thanks for your concern.

**Comment by matachi** [comment]
I see. I saw that 1.4.9 adds support for VLC, which is why I asked about it. But don't mind me; take your time to make the release stable.

**Comment by HumbleBeeBumbleBee** [comment]
@matachi 1.4.8 should already support VLC. I am just letting users know VLC is now supported when they update, because VLC is such a great media/music player.

**Comment by HumbleBeeBumbleBee** [comment]
Please continue in #203 
https://drive.google.com/file/d/0B9lPaMaVVtiJYTVVVDR4YkU1QUU/view?usp=sharing
This is a beta testing version. Let me know if it solves your problem.
It has a different key so you'll have to uninstall and setup SLS again.
