### ISSUE TITLE
add support for Deezer

### ISSUE THREAD

**Issue by asaskevich** [tgwizard/sls#199]
[Deezer](http://deezer.com) has own Android app and it's playing streaming music or music saved to device. Any way to add support for this app, so we can scrobble songs we play through it?

**Comment by HumbleBeeBumbleBee** [comment]
I have sent an email to support@deezer.com and they will hopefully respond.
Deezer will need to add track information broadcasts for SLS to scrobbler Deezer.

**Comment by HumbleBeeBumbleBee** [comment]
Their response.
>We currently recommend using a browser when scrobbling rather than an app as we do not support scrobbling on our standalone apps.

**Comment by HumbleBeeBumbleBee** [comment]
Deezer support should be available in the next release.

**Comment by corsac-s** [comment]
Any timeframe on that release reaching Google Play Store or F-Droid appstore?

**Comment by HumbleBeeBumbleBee** [comment]
The networking still needs some work/testing, otherwise very soon.
I could release right now, or update more of the networking.

Would you like an .apk of the most recent version?

Steps:
1. Scrobble all recent scrobbles.
2. Uninstall the current version.
3. Install this .apk version.
4. Re-login to Last.fm/Libre.fm
5. Test it.

SLS 4.9.+
[app-debug.zip](https://github.com/tgwizard/sls/files/369517/app-debug.zip)

**Comment by corsac-s** [comment]
It wasn't a way to rush you in any way, it's was really for information :) but if you need some test feedback, I'll gladly install it and report back.

**Comment by HumbleBeeBumbleBee** [comment]
It's no rush. This is what I am worried about.
[end data of 1.2.1 Last.fm API](https://getsatisfaction.com/lastfm/topics/absolute-end-of-api-1-2-1-support?rfm=1&topic_submit=true)

**Comment by corsac-s** [comment]
Unfortunately, I'm using libre.fm. I can try to exerce a little the last.fm feature but I'm usually using libre.fm client mode.

**Comment by HumbleBeeBumbleBee** [comment]
That's great! Let me know if you get notifications about Libre.fm connection.

**Comment by corsac-s** [comment]
So at first sight, it works just fine (I just scrobbled from Deezer to libre.fm, and from Deezer to last.fm).

**Comment by corsac-s** [comment]
I got an “authentication failure” notification for libre.fm (because data wasn't enabled, so perfectly normal) and  “wrong password” notification for last.fm (because the password was wrong, so perfectly normal too). Is that what you're talking about?

**Comment by HumbleBeeBumbleBee** [comment]
Yes.
Great!

**Comment by HumbleBeeBumbleBee** [comment]
Wifi and Data was off ?

**Comment by corsac-s** [comment]
Yes
