### ISSUE TITLE
add support for Rhapsody Android (2.0+)

### ISSUE THREAD

**Issue by jpr1877** [tgwizard/sls#20]
SLS interfaced with Rhapsody Beta, but it does not seem to be compatible with Rhapsody 2.0. It would be excellent to have support extended to the new version.

Thanks.

Jeff

**Comment by HumbleBeeBumbleBee** [comment]
I am contacting Rhapsody about this, and will try to find a solution no matter their response.

**Comment by HumbleBeeBumbleBee** [comment]
```
Hi, on the google playstore, you have Rhapsody Android listed as a supported app, but it will not recognize the app when playing music so I can't scrobble from it.

I've heard people say that it used to work with the Rhapsody Beta app, but I am currently running version 3.0.1.89 on an ASUS tablet with Android Ice Cream Sandwich.

If you could fix this issue, it would be greatly appreciated, as Rhapsody is the only device I use for listening to music.

Thank you,
Janice
```

**Comment by HumbleBeeBumbleBee** [comment]
Rhapsody is currently available to me, but I will figure a way to get it on my device. VPN or something.
Once I have it, I will do my best to support your requests or ask Rhapsody to add support. 
-Thanks!

**Comment by HumbleBeeBumbleBee** [comment]
I have sent an email to help@rhapsody.com requesting they broadcast song information so SLS can scrobble music played in Rhapsody.

**Comment by HumbleBeeBumbleBee** [comment]
Rhapsody scrobble support exists.
