### ISSUE TITLE
doesn't scroble some songs from Walkman

### ISSUE THREAD

**Issue by moshpirit** [tgwizard/sls#202]
I'm listening 2 albums (one by one) and looks like some of the songs are not been scrobled.

Version 1.4.9 (f-droid)

**Comment by HumbleBeeBumbleBee** [comment]
Hi @moshpirit. The latest version on f-droid is [v1.4.8](https://f-droid.org/repository/browse/?fdfilter=scrobbler&fdid=com.adam.aslfms)
Is that the version you are referring to?

**Comment by moshpirit** [comment]
Sorry, I saw an issue about 1.4.9 that confused me. You're right, I use the version 1.4.8, sorry

**Comment by HumbleBeeBumbleBee** [comment]
https://drive.google.com/file/d/0B9lPaMaVVtiJYTVVVDR4YkU1QUU/view?usp=sharing
This is a beta testing version. Let me know if it solves your problem.

**Comment by moshpirit** [comment]
Didn't try this version (I don't trust Google so I don't want to visit any Google service), but my configuration is:

- Scrobble point: 50%
- Options: Custom
- Scroble [x]
- Notify now playing [ ]
- When to scrobble: when you pressss the scrobble now button
- Also on playlist finish [x]
- Network: Submit data on: 3G and Wifi
- Roaming [ ]
- Options: Same as for battery

**Comment by HumbleBeeBumbleBee** [comment]
@moshpirit I have the exact same setup and everything scrobbles just fine.
It will be difficult for me to understand what is going wrong if I can't recreate your problem.

**Comment by moshpirit** [comment]
Maybe can be some incompatibility with Walkman or maybe because of some error connecting the wifi, I don't know :-\

**Comment by HumbleBeeBumbleBee** [comment]
It shouldn't be the fault of the music player, but something with the connection SLS is making with last.fm/libre.fm.

**Comment by HumbleBeeBumbleBee** [comment]
https://github.com/tgwizard/sls/issues/165#issuecomment-109637993

**Comment by HumbleBeeBumbleBee** [comment]
@moshpirit Can you listen to the album offline and see if all the songs make it into the cache?

**Comment by HumbleBeeBumbleBee** [comment]
You could try doing some debugging yourself if it is the networking.
https://github.com/tgwizard/sls/issues/165#issuecomment-109637993

**Comment by moshpirit** [comment]
I usually don't have this configuration, I normally use the "scrobble after every track" and sometimes it misses some songs (the same error that you've just posted here, I'm reading the comment, btw), but just a few, so it's not a big deal, so I don't use this configurations by default, just sometimes, so it's diffult to know what's failing here. I've checked the scrobble now option offline and it save the songs perfectly in the cache.

**Comment by moshpirit** [comment]
Lol it didn't was so perfect, "scrobble when push the button" option enabled, I reconnected my phone to Internet and it automatically sent the scrobbles :-(

**Comment by HumbleBeeBumbleBee** [comment]
I really wish I could duplicate your problem... :-( 
Everything works fine on my phones...

**Comment by moshpirit** [comment]
Could you include some kind of log folder or something that we could send you in order to let you see what's the problem? :(

Anyway, don't worry, it's not a big deal and sls is a good app!

**Comment by HumbleBeeBumbleBee** [comment]
The latest version can be found here https://github.com/tgwizard/sls/releases/tag/v1.4.9

**Comment by HumbleBeeBumbleBee** [comment]
Sometimes if the information is wrong SLS can't scrobble.
Please check battery settings or power settings for SLS.
