### ISSUE TITLE
Code style guide

### ISSUE THREAD

**Issue by inverse** [tgwizard/sls#207]
What style guide are you guys using with this? I noticed most of the code is using tabs for indentation but the default one with Android Studio is spaces.

**Comment by HumbleBeeBumbleBee** [comment]
Whatever the default is for Android Studio.
You could add this information as documentation in one of the markdown files if you want.

**Comment by inverse** [comment]
Yeah I think we should include information about that and also move all the code to this format too at first. which will cause a big headache for outstanding work that's being worked on.

Gotta start some where I guess though!

**Comment by HumbleBeeBumbleBee** [comment]
Has this been resolved @inverse ?

**Comment by HumbleBeeBumbleBee** [comment]
At some point I'll go through every piece of code and auto align them.

**Comment by HumbleBeeBumbleBee** [comment]
After 1.5.0 I will format all the code to Android Studio, as long as the users are happy with it and it does not crash.
