### ISSUE TITLE
Now playing notification detected, but no scrobble

### ISSUE THREAD

**Issue by dabbatelli** [tgwizard/sls#209]
Hello, 

I'm using SLS with Vanilla Music (which in his turn uses Scrobble droid APIs).
My problem is that SLS seems to detect without problems the music I'm playing, but then it forgets to scrobble it once it reaches the scrobble point. 
So far I have 666 now playing notifications, but only 470 scrobbles: while I do skip a song from time to time, I am absolutely sure that I don't do it that often. I am not able to relate the failing scrobble to any specific condition.

**Comment by HumbleBeeBumbleBee** [comment]
It's really difficult to debug your issue as you say, "I am not able to relate the failing scrobble to any specific condition."
Could you please share your Android Version, Vanilla Music Version, & Vanilla Music App Source?

**Comment by Row** [comment]
Had the same problem with my Samsung galaxy s6 today. Saw a post on Google play store about androids power optimisation settings for applications. After disabling the setting for simple scrobbler it works again. Perhaps there is some setting/permission to avoid automatic power optimization.

**Comment by Rocksteady18** [comment]
Hey Row that helped me a lot.  I don't have that setting on my phone (kitkat) but I have been using an app called battery saver.  I moved the player I was using and sls and it's finally working.  Great solution, maybe devs could put a disclaimer on google play *turn off battery optimizer for this to work

**Comment by HumbleBeeBumbleBee** [comment]
@Rocksteady18 Could you please share what your device is called?

**Comment by Rocksteady18** [comment]
Motorola XT907 Droid Razr M

**Comment by HumbleBeeBumbleBee** [comment]
Thanks.

**Comment by Rocksteady18** [comment]
np, glad to have my libre.fm scrobbling again, I think sls is the only app that supports libre afaik
