### ISSUE TITLE
add support for Queek Music Player

### ISSUE THREAD

**Issue by Tighbu** [tgwizard/sls#21]
Hi 

Thanks for your app. It's a winner.

Please support Queek Music Shuffler and Queek Music Shuffler HD.

**Comment by HumbleBeeBumbleBee** [comment]
I'll be working on it soon. :)

**Comment by Tighbu** [comment]
Thanks, I've since moved on to MixZing though which already has support.

**Comment by HumbleBeeBumbleBee** [comment]
I have sent an email to romulus@sais.tw requesting they broadcast song information so SLS can scrobble music played in Queek.

**Comment by HumbleBeeBumbleBee** [comment]
From the developers.
> I'm sorry but Queek won't support Last.fm scrobbler.
