### ISSUE TITLE
Release v1.4.9

### ISSUE THREAD

**Issue by tgwizard** [tgwizard/sls#211]
I've uploaded a signed package of v1.4.9 here: https://github.com/tgwizard/sls/releases/tag/v1.4.9. Could you please try it out, especially upgrading and so from existing installations of the version Google Play? If everything works out we'll release this in a week.

**Comment by tgwizard** [comment]
I must say, great work by everyone involved!

**Comment by inverse** [comment]
Will use this thnx!

**Comment by inverse** [comment]
@tgwizard I cannot see the signed release?

**Comment by inverse** [comment]
@tgwizard I cannot see the signed release.

![ss](https://cloud.githubusercontent.com/assets/713525/9161306/038c7ba6-3f41-11e5-83bc-048e35c741e2.png)

**Comment by tgwizard** [comment]
Oh, sorry, I forgot to upload the apk. It is there now.

**Comment by inverse** [comment]
:+1: thnx  will install!

**Comment by inverse** [comment]
No problems seem with minimal usage of google music/8tracks today.

**Comment by HumbleBeeBumbleBee** [comment]
No problems with My Cloud Player, Rocket Player, 8tracks, Rdio, Builtin Samsung Music Player, Google Music Player.
I have found a major problem with SpotifyReceiver though. I might be able to figure it out, but here are my preliminary findings.
https://ghostbin.com/paste/yb243
Unsuccessful scrobble is com.spotify.music (Spotify)
Successful scrobble is com.android.music (Samsung Music Player)

**Comment by HumbleBeeBumbleBee** [comment]
@inverse helped me get this right. Turns out I was giving ScrobblingService.java the wrong unit of time from SpotifyReceiver.java

**Comment by tgwizard** [comment]
I've uploaded a new version of v1.4.9 (39) with the fix for Spotify: https://github.com/tgwizard/sls/releases/tag/v1.4.9-39

**Comment by matheigalm** [comment]
Spotify still does not work for me. app don't recognize while music playing neither the spotify itself. is it the problem with me only or someone else have the same?

**Comment by HumbleBeeBumbleBee** [comment]
@matheigalm Is "Device Broadcast Status" turned on?

**Comment by HumbleBeeBumbleBee** [comment]
I just did a fresh install of the latest source code .zip and everything works fine with Spotify.

**Comment by tgwizard** [comment]
So is there an issue with the newly built apk?

**Comment by inverse** [comment]
I've noticed nothing but I've not used Spotify

**Comment by matheigalm** [comment]
it seems that I've not given much attention in this detail (device broadscast status). that was the problem . It works great. thank you! I've waited so long for it.

**Comment by DemarsM** [comment]
I have the following problem with v 1.4.9 and Spotify: each song is scrobbled 3 times. One might be scrobbled by Spotify itself and one by SLS. I don't know what could be the third...

**Comment by DemarsM** [comment]
Maybe would be a good idea to stop SLS to scrobble on Spotify when it is in online mode  with scrobbling enable. The utility of SLS with Spotify is mainly for offline mode no?

**Comment by HumbleBeeBumbleBee** [comment]
@DemarsM 
1. Could you disable Spotify's builtin scrobbling? If you still have multiple scrobbling we have a problem, otherwise everything is ok.
2. The manual hack is to disable Spotify in "enabled apps" every time you're connected to the internet. 
3. I could try automating this for you on a custom GitHub branch, if you really need this feature badly.

**Comment by tgwizard** [comment]
So, how should we proceed with the release?

**Comment by inverse** [comment]
I've not noticed anything abnormal from using it with the google music app for the past week

**Comment by tgwizard** [comment]
Ok. This release seems good, so I think it should be released to Google Play. I'll do so tomorrow, if no one objects. What do you think?

**Comment by HumbleBeeBumbleBee** [comment]
Sounds good to me.

**Comment by inverse** [comment]
Been using it since I last said without any hiccups. :+1:

**Comment by tgwizard** [comment]
I've uploaded v1.4.9 to Google Play now.

**Comment by DemarsM** [comment]
Can't find where the third is coming from (maybe an old beta install of SLS not cleared ???) but the second scrobble is definately coming from Spotify itself

**Comment by DemarsM** [comment]
@HumbleBeeBumbleBee 

Here a summary of my situation:

When connected to internet with spotify scrobbling on : 3 scrobbles for each song
When connected to internet with spotify scrobbling off : 2 scrobbles for each song
When offline with spotify scrobbling on : 1 scrobble for each song
When offline with spotify scrobbling off: 1 scrobble for each song

The problem is only when im connected to internet

**Comment by HumbleBeeBumbleBee** [comment]
Hmm... kind of a tough one. I can't really figure out what is going wrong. You could try using a Libre.fm account to see if SLS double scrobbles to it. If Libre.fm does not get double scrobbles like last.fm it's not the fault of SLS.
