### ISSUE TITLE
Big Android 5.0 trouble

### ISSUE THREAD

**Issue by Nebbi** [tgwizard/sls#217]
The app (1.4.8) don't detect Google Play Music (Version v.6.0.1951S.2109908). Instead of GPM detects the app android music player which is shown as "not installed"...

Ive tried to use AIMP player but there are only infrequent scrobbles ... please help!

**Comment by HumbleBeeBumbleBee** [comment]
Does Google Play Music scrobble.
I use android 5.0 with google play and have not had the same problem.

**Comment by polamjag** [comment]
Same problem on Xperia Z1 with KitKat. Version of Google Play Music is `6.0.1985S.2228307`

**Comment by viniciuspinto** [comment]
In my case, it wasn't detecting any music apps on Lollipop.

After updating Google Play Music to the latest version (6.0.1985S.2228307), the app now shows it as "Android Music Player", and although it says "not installed", scrobbling is working fine.

**Comment by HumbleBeeBumbleBee** [comment]
@polamjag Do you have special power saving settings or battery settings?
Check your phone time?

**Comment by HumbleBeeBumbleBee** [comment]
https://drive.google.com/open?id=0B9lPaMaVVtiJaGwwdkt0UjBNVHc

You can try this new version.
Please let me know if you have any problems.
This thread will be closed for now.
