### ISSUE TITLE
Cache isn't being submitted

### ISSUE THREAD

**Issue by serpent849** [tgwizard/sls#218]
I've had a Cowon D3 plenue player since January. It runs Android 2.1 and I specifically chose it to be able to scrobble. It mostly worked fine for months (occasional lost scrobbles but no big deal), until it stopped submitting on August 21. That's around the time the lastfm site got updated. Wifi works normally but scrobbling no longer happens, and the Scrobble Now button does nothing :( (Previously it always helped if automatic submissions didn't happen)

I use the MixZing app for music, simply chose the one that worked best out of those you support. I've just updated Simple LastFM to the latest version (which was difficult without GooglePlay) and still nothing :(

**Comment by HumbleBeeBumbleBee** [comment]
Hi @serpent849 very cool mp3 player. I have a user on Google Play reporting almost an identical problem.

Questions:

1. So you are saying that your accounts login but something is going wrong when you press "Scrobble Now" ? SLS is not authenticating for scrobbles or something else is wrong.

2. Does SLS send now playing notifications?

This is difficult. I don't like asking users to debug, but that's usually the best way to solve the problem. I am not sure how to debug your device either (it might be difficult some how).
Here is a link to the [latest release](https://github.com/tgwizard/sls/releases) in case you found the apk a different way.

Possible Solutions:

1. Create a libre.fm account and play some music. If it scrobbles to libre.fm it is most likely a problem with the new last.fm website.

2. Wait some time. This could be a problem with the new last.fm website and users from certain regions are reporting more problems. (Example: many Russian SLS users have "Network error, retrying...")

3. Last resort (if you haven't already).
(Don't forget your last.fm/libre.fm password.)
I hate losing scrobbles, but you might need to uninstall the app including all it's data.
Fresh install and re-enter your account details.

**Comment by serpent849** [comment]
Oh I'm Russian too, might just have to wait then :/ 
Yeah I used the app normally for months. Judging by the "latest now playing notification" it's not sending them anymore either :( 
There's no error when I click "scrobble now", it just doesn't happen.
Yeah that's the version I have, not sure if I downloaded from here or F-droid (tried both). I generally prefer installing from 1mobile when available. I'm using it in Spanish :D (btw, would be great if I could choose the language for the app itself, rather than default to English unless Android is set to Spanish/German/French. but oops unrelated feature requests :3)

**Comment by serpent849** [comment]
How long did you have to wait btw?

**Comment by jonathebest** [comment]
I Have the same problem, I'm from México....

when I Try to send the scrobbles in chaché doesn't happen anything, I Click "scrobbler now" but nothing happen, not even an error message.

I Run the SLS on my samsung galaxy Ace Galaxy, Android 2.3.6

I'll try the Libre.fm scorbbling maybe, but i will wait a little bit more (if is a LastFM problem) , if nothing happen maybe i would re-install the app

**Comment by HumbleBeeBumbleBee** [comment]
@serpent849 It took a day or so for the problem to correct itself for me.

Also did you test solution 1.? That's how I knew for sure it wasn't SLS and that it was last.fm

**Comment by jonathebest** [comment]
I Re Installed de SLS but now i can't login with my last.fm acount

**Comment by beowulf83** [comment]
Even I reinstalled SLS (version 1.4.9) and now I can't login with my last.fm account. I am getting "Network error, retrying...".

I am using a Sony Xperia P with Cyanogenmod 11 Unofficial. I use SLS with Shuttle+ Music Player.

**Comment by AwesomeLemonO** [comment]
I'm using Samsung Galaxy Mini, and already 2 weeks past since I can't log in to my account, the other device could log in easily, but the problem is that other device is kinda bad at playing music, the sound is pretty rubbish, if to say so. So I prefer to use Mini as player, but there's a problem which I told about. Is there any way to fix it or I should wait for a longer time? I couldn't check this for the libre.fm, because I can't even open that site (There is an organization in Russian Government which simply block some sites if they dissatisfied with them, maybe that's the reason).

**Comment by AwesomeLemonO** [comment]
Oh, it works now, haha

**Comment by k1llu7** [comment]
I'm still have the same problem with the scrobblings. I tried the solutions, but even libre.fm didn't log in, in fact, I install SLS in other device on my own, but didn't log either (at last and libre).

I hope that will be a matter of time, because I don't want to lose 3517 scrobblings 

(btw, I was that google play user that you mentioned before)

**Comment by serpent849** [comment]
yeah still having problems too :( well, scrobbles can only be submitted within two weeks, so you've probably lost many of them already, like i also did :(

**Comment by beowulf83** [comment]
SLS started working for me, once I set my device's time to 'Automatic date & time'  from the system settings of my device. Earlier when SLS was not able to log in after the changes made to the Last.fm website, the time on my device had been manually set (I like to set my time five minutes ahead of the actual time). 

I had run catlog on my device when SLS was not able to login and I had noticed this error:

09-11 20:07:31.126 D/Handshaker(12583): Handshaking: Last.fm
09-11 20:07:32.487 E/Handshaker(12583): Handshake fails: bad time: Last.fm
09-11 20:07:32.487 I/Handshaker(12583): Tempfail: Client side timing error, retrying…: Last.fm
09-11 20:07:32.517 D/Sleeper (12583): start sleeping: 60000: Last.fm

Hope that helps.

**Comment by Marwolaeth** [comment]
Thanks, @beowulf83 : it works perfectly! Probably, this is the solution.

**Comment by beowulf83** [comment]
Glad to be of some help @Marwolaeth. :)

**Comment by serpent849** [comment]
Yay, I managed to solve the problem too! Moscow and several other regions of Russia changed their timezone last year, so for now I set mine to Helsinki, which is the same while Europe is on DST. I guess last fm (and/or your app) still thinks Moscow is on GMT+4, while we're on GMT+3 now (no DST).

One more thing is that my device is an mp3 player, not a phone, so it never bothered me much when the time kept getting reset to 9.00 September 1st 2009. I do always reset the date for the sake of lastfm, but I've often not bothered to set the correct time and it still worked until July. If lastfm hasn't imposed any new restrictions, it would be great to have more leeway with the time. (or any apps for fixing it on Android 2.1? I've downloaded time calibrator, but it merely displays the correct time, rather than syncing it. and it did show the incorrect time for Moscow, which is what made me try a different GMT+3 timezone)

**Comment by ddiniz** [comment]
Thank you very much, beowulf83, indeed!

**Comment by Marshall34** [comment]
Автоматическая синхронизация времени работает. Работает все только онлайн. Если оффлайн, то в кэш треки просто не попадают, всегда указанно 0 треков в кэше. Раньше все прекрасно работала. The automatic time synchronization is switched on. Everything works just online. When offline, the cache tracks just do not get, is always set to 0 tracks in the cache. Previously, everything works fine. Samsung GT-I9105 + Poweramp v1.4.9

**Comment by aquatix** [comment]
@serpent849 you might want to try ClockSync, which synchronises your device's clock over ntp: https://play.google.com/store/apps/details?id=ru.org.amip.ClockSync&hl=en

**Comment by HumbleBeeBumbleBee** [comment]
Does anyone still have problems?

**Comment by serpent849** [comment]
no, but i wish there was a way to correct the time for the scrobbles before they're submitted or fix the time more easily (my device doesn't have googleplay).
the only problem is that, as I mentioned, if I list Moscow as my timezone, then either my device, your app or lastfm thinks it's GMT+4, and then lastfm concludes that the date is incorrect.

**Comment by HumbleBeeBumbleBee** [comment]
Troubleshooting
Check your phones time.
Check battery/power settings on phone add SLS to protected/whitelist (power save disabled).
Check SLS options. (power settings)
Check if Last.fm is down. http://status.last.fm
Check enabled apps. example. (Neutron music disabled stops some random scrobbles for me.)
Make sure you can login to last.fm on your phone browser. (That means SLS is the problem if you can't.)
Check settings in your music app for scrobbling.
Make sure your songs have the required metadata information. https://musicbrainz.org 
Make sure your scrobbles are not scrobbled too late. (2 weeks)
Create an issue on github or email us or google community post.
