### ISSUE TITLE
First song incorrectly scrobbled

### ISSUE THREAD

**Issue by cflynn90** [tgwizard/sls#219]
The first song in my library is constantly scribbled witbout being played. It has a special character in it (the song name is - 72 hours - including the hyphens). This is constantly submitted as a scribble without being played. Seems to happen more if I pause the song playing before it reaches the 50% scribble mark.

**Comment by cflynn90** [comment]
Scrobbled not scribbled. Sorry I'm on mobile and didn't catch the typo until after posting.

**Comment by HumbleBeeBumbleBee** [comment]
Thanks for reporting this @cflynn90.
Could you share 3 pieces of information?
1. For what version(s) of SLS has this occurred? (example 1.4.8)
2. What music player and version are you using?
3. What android version do you have?

Questions.
Does this occur with only one music player or have you tested others?
Does your music app of choice remain running as a background process?
#79 Is this similar to what is happening for you?

**Comment by cflynn90** [comment]
1. SLS v1.4.9 currently and 1.4.8 before.
2. Rocket Player v3.4.1.58
3. Android v5.1

Rocket is the only player I use so I haven't noticed any behavior on the other music apps.

I fit believe it runs background processes but I could be wrong.

Yes, #79 sounds exactly the same.

**Comment by cflynn90** [comment]
New problem surfaced today. I started using my cloud player v17.3.1 and instead of scrobbling the soundcloud tracks, the -72 hours- track was scribbled. 


Particularly odd since the my cloud player was playing soundcloud music and sls instead Scrobbled a track stored on my sd card.

**Comment by HumbleBeeBumbleBee** [comment]
My Cloud Player usually works well. Could you explain this new problem with more detail.
What do you mean 72 hours track?
example.
* what happened in order
* what you expected to happen

**Comment by HumbleBeeBumbleBee** [comment]
You might need to temporarily disable Android in enabled apps.

**Comment by HumbleBeeBumbleBee** [comment]
Do you have Neutron music player or just Rocket Player?
Sometimes a music player broadcasts data accidentally to SLS while you are listening to music.
(then...)
Sometimes a track gets loaded into Track waiting area of the app and scrobbles accidentally while another app is running.

Some music apps share data with SLS when they don't need to or SLS stores old track data.

**Comment by HumbleBeeBumbleBee** [comment]
https://drive.google.com/open?id=0B9lPaMaVVtiJaGwwdkt0UjBNVHc

Please try this version. I will close this for now.
