### ISSUE TITLE
Spotify Connect doubling scrobbles

### ISSUE THREAD

**Issue by nrcll** [tgwizard/sls#221]
I’ve been using the last version, 1.4.9, and the Spotify integration works perfectly. Thanks a lot for that.

Today I found out that, thanks to Spotify Connect, when you listen to something on your computer via Spotify, if your mobile phone is connected to the same network, the app acts like it’s also playing this song on your phone, so SLS scrobbles it too. The result are doubled scrobbles (Spotify PC and SLS, because I already turned off the Last.fm built-in option on the Spotify Android app). Is there any way to fix this?

Thanks again

**Comment by HumbleBeeBumbleBee** [comment]
I guess it's a matter of choosing between which device you want as your default scrobbler.
You could disable Spotify manually in the "enabled apps" section of SLS to make your PC default.
You could always have your phone connected and use your phone as the default scrobbler.

I am not sure about using code to fix this...

**Comment by inverse** [comment]
This isn't a feasible thing to implement since SLS wouldn't be able to determine the 'scrobble' state of Spotify. Aside having a whitelisted wifi list which would be set to be disabled if connected.
