### ISSUE TITLE
About problem scrobbling after 1%

### ISSUE THREAD

**Issue by Domi52** [tgwizard/sls#222]
I checked "sony ericsson music player" and i think it works well, but this problem present in my favorite player "neutron music player"(last version from market), my android version 4.1.2, pls fix it, also i picked four stars

**Comment by HumbleBeeBumbleBee** [comment]
Neutron Music Player is scrobbling after 1% of the song is played?

**Comment by inverse** [comment]
What's the issue? Scrobbling after 1% listen?

**Comment by HumbleBeeBumbleBee** [comment]
Hi @Domi52 if I can't recreate the problem there is nothing I can do. I will close this issue for now. Please share any more details and information if you can.
If the problem is fixed pleased let us know.

**Comment by HumbleBeeBumbleBee** [comment]
@Domi52
Neutron music player is not always the most reliable for scrobbling.
