### ISSUE TITLE
problem with scrobble from Spotify

### ISSUE THREAD

**Issue by alefspfc** [tgwizard/sls#223]
the scrobbles i make from spotify appear on cache but when i click on "scrobble now" they doesn't go to my last fm profile. Also, everytime i open Spotify the SLS shows an error message.

**Comment by HumbleBeeBumbleBee** [comment]
Only scrobbles from Spotify aren't going to your last.fm profile?
Have you tried other music apps and do they scrobble?
This could be a problem with the website if no scrobbles from any music app are going to your last.fm profile.

Could you please share what the error message is?

**Comment by alefspfc** [comment]
yes, only scrobbles from Spotify aren't going to my profile. The scrobbles i make from Android Music Player are ok. This is the error message that appear everytime i open Spotify (translating from portuguese): "Sorry! The application Simple Last.fm Scrobbler (process com.adam.aslfms) stopped unexpectedly. Try again"
![sc20150906-164837](https://cloud.githubusercontent.com/assets/14139954/9706304/a66e9d28-54b7-11e5-989c-f43830fd6be2.png)

**Comment by HumbleBeeBumbleBee** [comment]
@alefspfc Sorry that error code is my fault I believe. Spotify must have updated their application or something. I see the crash reports on Google Developer.
I am not sure why Spotify isn't scrobbling. If the songs are in the cache, they should scrobble to last.fm.

**Comment by alefspfc** [comment]
any prediction when the problem will be solved?

**Comment by HumbleBeeBumbleBee** [comment]
I changed a few lines of code. Let me know if this works.
You can install this, but be forewarned it will wipe all your information because I signed it not tgwizard.
https://drive.google.com/file/d/0B9lPaMaVVtiJcnV1WDk1d3VlVWs/view?usp=sharing

**Comment by alefspfc** [comment]
well, the error message doesn't appear anymore but the scrobbles from Spotify still doesn't go to my profile

**Comment by HumbleBeeBumbleBee** [comment]
Please make sure 'broadcast song information so other apps can see' is enabled in Spotify.
