### ISSUE TITLE
app scrobbles on its own, always the same song

### ISSUE THREAD

**Issue by sicid** [tgwizard/sls#224]
Hi. For a few months my phone (galaxy s5) puts up to three different songs in its cache and submits it seemingly on random, resulting in one or two songs being scrobbled up to a dozen times in a row with irregular time between submitting. All while I'm not listening to music on this device or at all. 
I just noticed this recently but like I said, it's been going on for at least two or three months. One song has been submitted about a hundred times since June. Another one is on a good way for doing the same. 

My profile is
last.fm/user/oo-
Some of the songs are:

The Devil's Blood - She
Year of the Goat - Riders of Vultures
Dødheimsgard - Blue Moon Duel
Blind Guardian - Under the Ice 

At least those are some I noticed. I also started deleting some submissions yesterday already.
Any idea? 
Thanks

**Comment by HumbleBeeBumbleBee** [comment]
Could what music player(s) you use?
Is this problem the same as yours #79 ?

**Comment by sicid** [comment]
Hi and thank you for your reply.  It reads similar, but as I said it happens with more than one song as the other guy described. 
I'm using the built-in music app on my galaxy s5. It's simply called 'Musik' (german),  can't seem to find much about it

**Comment by sicid** [comment]
https://www.safaribooksonline.com/library/view/galaxy-s5-the/9781491905098/ch04.html

**Comment by HumbleBeeBumbleBee** [comment]
Duplicate #79
