### ISSUE TITLE
Doesn't work on Huawei P8 Lite

### ISSUE THREAD

**Issue by monciak88** [tgwizard/sls#225]
I'm using Huawei P8 Lite and SLS doesn't work. I've been trying to scrobble from different music players, even on those with scrobbling option: Black Player, Shuttle.

**Comment by HumbleBeeBumbleBee** [comment]
Could you try ["Vanilla Music Player"](https://play.google.com/store/apps/details?id=ch.blinkenlights.android.vanilla) ?

**Comment by monciak88** [comment]
SLS can't see it. :/

**Comment by HumbleBeeBumbleBee** [comment]
Does your device have any special battery settings?

**Comment by monciak88** [comment]
No.

**Comment by HumbleBeeBumbleBee** [comment]
Shuttle Player
Settings -;Scrobbling -;Enable Scrobbling

BlackPlayer
Settings -;Metadata -;Scrobble Music

**Comment by monciak88** [comment]
Still nothing.

**Comment by HumbleBeeBumbleBee** [comment]
Something is very unique about your device. I wish I could debug it.

**Comment by Miladsob** [comment]
I have Honor 4x and the **Simple Lastfm scrobbler** doesn't scrobble musics on my phone, Google Play Music is ok and scrobble but the Huawei Music player is better than!
Please add **Huawei music player** support to SLS!
*Thanks!*

**Comment by khuebner** [comment]
I have an **p8 lite** as well. SLS recognize my favorite music player (GoneMad player) but it seems that SLS only scrobbles songs if I start SLS manually and keep it open. Otherwise no songs are scrobbled. I had no problems with GoneMad on other phones.
I'll try Vanilla Player later.

**Comment by talios** [comment]
Did anything come of this? I've just myself upgraded to a new P9 Plus and noticing SLS is not picking up any scrobbles ( I see it pick up the "now player" event sometimes, but no actual plays ).

Tried using PowerAMP, GoneMad, Neutron, Rocket, and Vanilla Player - I also have a similar issue with iSyncr not picking up play counts, so I suspect there may be a device issue/setting?  If anyone here has solved the problem at the device level sing out....

**Comment by talios** [comment]
Looks like putting both music player and SLS into the list of "protected apps" under Battery settings resolved this issue for me.

**Comment by geeanlooca** [comment]
P10 lite protected apps battery
