### ISSUE TITLE
[Q] Is duration required even when source is 'R' (shoutcast, radio, etc)?

### ISSUE THREAD

**Issue by rejhgadellaa** [tgwizard/sls#226]
(Sorry to bother you via the issue tracker but I'm not sure how else to contact you about this..)

In the docs it says that duration is required but since my app is a shout-/icecast streaming app I have no idea what the duration is. So.. is this really required?
Src: https://github.com/tgwizard/sls/blob/master/Developer's%20API.md

**Comment by HumbleBeeBumbleBee** [comment]
We have a default when track duration is not known which is listening [4 minutes.](https://github.com/tgwizard/sls/blob/master/app/src/main/java/com/adam/aslfms/service/ScrobblingService.java#L282)
If you want your app to work, duration is very important.
You can always test your app with SLS.

**Comment by HumbleBeeBumbleBee** [comment]
Please, let me know if you have further questions.
