### ISSUE TITLE
add support for Andless Player

### ISSUE THREAD

**Issue by shaddow2k** [tgwizard/sls#23]
Please add Support for this player, it's the only stable Flac player out there.

http://code.google.com/p/andless/

Thank you in advance!

**Comment by HumbleBeeBumbleBee** [comment]
I will try to add support for this. :)

**Comment by HumbleBeeBumbleBee** [comment]
I have sent an email to skvalex@gmail.com requesting they broadcast song information so SLS can scrobble music played in Andless.

**Comment by HumbleBeeBumbleBee** [comment]
Hi @shaddow2k Andless player is maintained on github as Alsa player now, I have opened a ticket [here](https://github.com/avs333/alsaplayer/issues/1). I might be able to help implement it.
