### ISSUE TITLE
Submitting cache without automatic time

### ISSUE THREAD

**Issue by R0M4N0F5K7** [tgwizard/sls#230]
So now we know from issue #218 that the issue for unsubmitted cache was the use of manually set time for many of us:
Would it be possible to make scrobbling also available for people that use manually set time on their phone for whatsoever reason? Our would that be to complex to fix/implement?

**Comment by HumbleBeeBumbleBee** [comment]
Possible ignored message codes:

0. None (the request passed all filters).
1. Filtered artist.
2. Filtered track.
3. Timestamp too far in the past.
4. Timestamp too far in the future.
5. Max daily scrobbles exceeded.

**Comment by HumbleBeeBumbleBee** [comment]
This might require permission to use Location to set the app's time differently than your phone.
SLS is supposed to be simple and minimal if possible.
Therefore it may not become a feature.
