### ISSUE TITLE
add support for listenbrainz

### ISSUE THREAD

**Issue by loominade** [tgwizard/sls#235]
https://listenbrainz.org/

Just an idea since I don't even know if they have an api.

**Comment by inverse** [comment]
:+1: Listenbrains looks good - I'm not sure either about an API yet though :(

**Comment by Freso** [comment]
There is some documentation, but note that it isn't official yet: https://listenbrainz.readthedocs.org/

(CC: @alastair, @mayhem)

**Comment by inverse** [comment]
So there is: https://api.listenbrainz.org/1/user/inversechi/listens

**Comment by dns53** [comment]
Thanks to a student participating in the google summer of code listenbrainz now has a last.fm 2 compatable api.
https://blog.musicbrainz.org/2016/08/23/gsoc-16-listenbrainz-fun/

**Comment by Freso** [comment]
It would still be preferable to use the native ListenBrainz API though, as that is able to submit a lot more information than what is possible with the AudioScrobbler API.

**Comment by HumbleBeeBumbleBee** [comment]
If somebody could get me the url to the 2.0 compatible api I could implement this. The next version of SLS will have an option for custom gnu-fm server.

**Comment by HumbleBeeBumbleBee** [comment]
@Freso I am new to this authentication method. This may take some time. I will try to have it done ASAP.

**Comment by HumbleBeeBumbleBee** [comment]
Release 5.1.3 should have this feature.

**Comment by HumbleBeeBumbleBee** [comment]
#326
