### ISSUE TITLE
Doesn`t scrobble on huawei p8 lite

### ISSUE THREAD

**Issue by omanko** [tgwizard/sls#237]
The app doesn`t scrobble on my phone is there a way to fix this?

**Comment by HumbleBeeBumbleBee** [comment]
Does your device have any special battery settings? Many Huawei users are reporting similar problems.

**Comment by omanko** [comment]
I think so i`m not sure though

**Comment by HumbleBeeBumbleBee** [comment]
Duplicate #225

**Comment by HumbleBeeBumbleBee** [comment]
Duplicate #225
