### ISSUE TITLE
add support for MPDroid

### ISSUE THREAD

**Issue by fenque** [tgwizard/sls#238]

**Comment by HumbleBeeBumbleBee** [comment]
https://play.google.com/store/apps/details?id=com.namelessdev.mpdroid

I have sent an email to dreamteam69@gmail.com requesting they broadcast song information so SLS can scrobble music played in MPDroid.

**Comment by abarisain** [comment]
Hi!

I got HumbleBee's email asking for LastFM support. I think we supported it at some point but not sure when and if we really did ...

Anyway, quick question: why don't you use a server side last.fm plugin? It will be way more reliable

**Comment by HumbleBeeBumbleBee** [comment]
@fenque Could you speak to @abarisain ? I haven't tested MPD server yet, although server side makes sense.

**Comment by fenque** [comment]
I misunderstood how the app works, sorry.
