### ISSUE TITLE
No longer working on M

### ISSUE THREAD

**Issue by inverse** [tgwizard/sls#239]
The latest fix I pushed in fixes this but will require a new play store release. I guess we should push this to the store. Then work out a solution to migrate from the Apache HTTP client depending on the implications.

**Comment by HumbleBeeBumbleBee** [comment]
M?

**Comment by Alia5** [comment]
Marshmallow...

**Comment by HumbleBeeBumbleBee** [comment]
Ok.

**Comment by HumbleBeeBumbleBee** [comment]
@inverse I can work all tonight and tomorrow to migrate everything or I will notify Adam about it today.

**Comment by HumbleBeeBumbleBee** [comment]
@inverse #240 will fix M?

**Comment by HumbleBeeBumbleBee** [comment]
I tested on MM emulator and 2.2 emulator. Everything seems to be working. I am going to test the MD5.

**Comment by inverse** [comment]
No stress, happy new year :)

**Comment by HumbleBeeBumbleBee** [comment]
Yes. Happy New Year.

**Comment by HumbleBeeBumbleBee** [comment]
Everything seem to work.

**Comment by inverse** [comment]
That's good. Hmm sucks about that other issue though.

**Comment by HumbleBeeBumbleBee** [comment]
Still not working on M?

**Comment by HumbleBeeBumbleBee** [comment]
Does it work now?
