### ISSUE TITLE
Nexus 7, Android M - stuck with cache after some time

### ISSUE THREAD

**Issue by tjurczyk** [tgwizard/sls#243]
Hi guys,

I scrobble from Spotify and after updating my Nexus 7 to Android M I have the problem. The scrobbler is scrobbling fine for some time (~45 minutes), and then suddenly all its scrobbles are going to the cache. I tried to manually "Scrobble now" a few times, but it doesn't help. I clear the cache and then scrobbling resumes.
It's stock Android 6.0.1 (build number MMB29K). Any help will be appreciated.

**Comment by kelchm** [comment]
I can confirm that I've encountered the same issue on Android N (not M 😛).

**Comment by HumbleBeeBumbleBee** [comment]
@tjurczyk There may be a problem with the old API SLS is using or the database. I am currently working on a few network solutions. I will see if everything works. Do you scrobble to last.fm and libre.fm?

**Comment by HumbleBeeBumbleBee** [comment]
@tjurczyk By any chance are you using Data and WIFI?

**Comment by HumbleBeeBumbleBee** [comment]
Try #278 .

**Comment by HumbleBeeBumbleBee** [comment]
Is this still happening?
