### ISSUE TITLE
Scrobbling stops when network changes

### ISSUE THREAD

**Issue by lorenzo1973** [tgwizard/sls#244]
I've noticed scrobbling stops when my network changes.  For example I'll be using my mobile network during the day, but when I get home and connect to my WiFi the scrobbles will just stack up in the cache and not scrobble. If I restart the phone it will continue on the WiFi, but same issue when I change to 4g or whatever. For information I'm using Amazon to play my music, not sure if this is related or not.

**Comment by webash** [comment]
Not sure if its the network state change causing the issue, but I'm definitely seeing this as well. Had 125 tracks in cache despite the setting to scrobble every 10 tracks, and being online (either 4g or WiFi) the whole time.

**Comment by vinnygecko** [comment]
Had the same issue, 156 tracks in cache, and they would not scrobble until I changed back from WiFi to cellular again. It looks like it works again when you switch back to WiFi but only if you pause the song before switching. 

I'm using Google Play Music on Android (Nexus 6)

**Comment by Row** [comment]
I have a similar problem, the scrobbles are stuck in the local cache. It is not possible to submit them manually, nothing happens when clicking "Scrobble now", all new scrobbles are queued. 
Tried to toggle the wifi and restarting the phone, which does not fix the problem.
Cleared the queue once, then it worked for a while, but now it is broken again.

I am using SLS v1.4.9, DSub and Samsung S6 with Android v5.1.1.

**Comment by LankyLord** [comment]
I am having the same issue as @Row, I will try resetting the queue to see if that solves the issue.

I have a Motorola Moto X Style running Android 6.0. I'm using Shuttle Music Player with SLS.

**Comment by HumbleBeeBumbleBee** [comment]
https://github.com/tgwizard/sls/issues/248#issuecomment-228454730
It could be a number of things.
* Background Data
* Power saving settings

or the app itself.
Please share any additional details and if you got it to work again.

**Comment by HumbleBeeBumbleBee** [comment]
In Options you might want to customize your power saving settings.

**Comment by HumbleBeeBumbleBee** [comment]
I have the same issue at the moment. I can probably debug it.

**Comment by HumbleBeeBumbleBee** [comment]
I have this very problem, you can try this app in the meantime.
https://github.com/tgwizard/sls/files/389151/app-debug.zip
I will test it for some time.

**Comment by HumbleBeeBumbleBee** [comment]
Have you tried enabling roaming? in "Power Options"
In some devices this should work.
I am working on this very bug.

**Comment by HumbleBeeBumbleBee** [comment]
Try #278
