### ISSUE TITLE
When in "repeat current song" mode in LG Music Player, SLS doesn't scrobble subsequent plays

### ISSUE THREAD

**Issue by danhash** [tgwizard/sls#245]
Using LG Music Player, when I turn on "repeat current song" mode, SLS only sends one scrobble to Last.fm, even if the song repeats several times.

**Comment by danhash** [comment]
I am on Android version 4.1.2, Kernel version 3.4.0, on the LG Optimus F3Q (D520).

**Comment by HumbleBeeBumbleBee** [comment]
This is a known issue #155
