### ISSUE TITLE
Copy song title, album, artist on click of now playing

### ISSUE THREAD

**Issue by ned-martin** [tgwizard/sls#246]
This is really not very important but probably easy and it would be nice to have I think...

It would be nice if you could click on the last scrobbled, and now playing areas (in Status) and have it copy the song title, album, artist to the clipboard, for use in letting people know what you are listening to.

**Comment by HumbleBeeBumbleBee** [comment]
Cool idea. I will try to do this some time.

**Comment by HumbleBeeBumbleBee** [comment]
All done. This feature should appear on the front of the next release.

**Comment by HumbleBeeBumbleBee** [comment]
https://drive.google.com/file/d/0B9lPaMaVVtiJaWFwd2ExX3ZReHM/view?usp=sharing
