### ISSUE TITLE
Pulsar Music App - Doesnt Recognise.

### ISSUE THREAD

**Issue by zznukebombzz** [tgwizard/sls#247]
I'be spent most of today trialling every single music app available le to Android.

The winner Pulsar music app however sadly I have found its one of the few music playing apps not supporter by the simple last FM scrobbler.

Please consider including it in an update.

**Comment by inverse** [comment]
Damn - that player looks sleek. Like everything I liked out of Google Music but better. Even has Chromecast support too!

**Comment by hexise** [comment]
I am the developer of Pulsar music player, and I will work with @inverse to support Simple Last.fm Scrobbler in next release. Thanks.

**Comment by zznukebombzz** [comment]
Great sounds good guys! I spent 8 hours trialling music apps Pulsar just
need it to scrobble to my page!


On Tue, Feb 9, 2016, at 08:26 PM, Hexise wrote:
> I am the developer of Pulsar music player, and I will work with
> @inverse[1] to support Simple Last.fm Scrobbler in next
> release. Thanks.


> — Reply to this email directly or view it on GitHub[2].


>



Links:

  1. https://github.com/inverse
  2. https://github.com/tgwizard/sls/issues/247#issuecomment-181776619

**Comment by inverse** [comment]
@tgwizard When a user skips playback the correct broastcast to send is just the START action for the new track right? There's nothing else that needs to be done?

If this is so I'll update the documentation when I have some time to make it clearer to other developers.

**Comment by tgwizard** [comment]
@inverse that sounds correct.

**Comment by zznukebombzz** [comment]
I've got scrobbling via the official last.fm player and via the simple
last.fm scrobbler now for the music app Pulsar, well done guys.


On Thu, Feb 11, 2016, at 02:14 AM, Adam Renberg wrote:
> @inverse[1] that sounds correct.


> — Reply to this email directly or view it on GitHub[2].


>



Links:

  1. https://github.com/inverse
  2. https://github.com/tgwizard/sls/issues/247#issuecomment-182418536

**Comment by hexise** [comment]
@zznukebombzz lucky guy. I just pushed the new release to 20% users yet. 
It's nice that the new release works for you.

**Comment by zznukebombzz** [comment]
Great work and congrats on your app


On Thu, Feb 11, 2016, at 05:23 PM, Hexise wrote:
> @zznukebombzz[1] lucky guy. I just pushed the new release to 20%
> users yet.
>
It's nice that the new release works for you.


> — Reply to this email directly or view it on GitHub[2].


>


Links:

  1. https://github.com/zznukebombzz
  2. https://github.com/tgwizard/sls/issues/247#issuecomment-182734928

**Comment by inverse** [comment]
@hexise thanks so much for implementing such an awesome solution! And so quickly!

**Comment by hexise** [comment]
@inverse that is only because SLS API is clear and easy to integrate. Thanks.
The new version of Pulsar which support SLS has been released, I think this issue can be closed.

**Comment by zznukebombzz** [comment]
https://www.youtube.com/watch?v=m3SjCzA71eM

On Sat, Feb 13, 2016, at 03:44 AM, Hexise wrote:
> @inverse[1] that is only because SLS API is clear and easy to
> integrate. Thanks.
>
The new version of Pulsar which support SLS has been released, I think
this issue can be closed.


> — Reply to this email directly or view it on GitHub[2].


>



Links:

  1. https://github.com/inverse
  2. https://github.com/tgwizard/sls/issues/247#issuecomment-183403794

**Comment by inverse** [comment]
:dancer:
