### ISSUE TITLE
Scrobble Now doesn't work since August 2015

### ISSUE THREAD

**Issue by turas89** [tgwizard/sls#248]
Hello everyone!

My SLS doesn't work since last august :( I have more than 2k songs in my cache and I just can't do anything except seeing what I've just been listening to. Scrobble Now is inactive (nothing happens when pressing). I always thought that one day it's gonna unblock but apparently it won't happen. And I tried to install old version but it didn't help. I'm using Android Player.

Have I lost all of my scrobbles?

**Comment by inverse** [comment]
Damn - that sounds like a horrid situation. Are you able to capture the LogCat output when pushing scrobble now?

**Comment by turas89** [comment]
I've never done LogCat before, give me some time and I'll figure out what is it and how to do it :D Then I'll post it here. Thanks!

**Comment by inverse** [comment]
It'll allow us to see what SLS is trying to do. For example in the scrobble it has logging such as when sessions fail and such. Not sure what the best way to go about capturing this. Normally I just view the output in Android Studio. But it' a bit of a heavy download just for getting a log. I'm sure there are more lightweight and easier solutions.

**Comment by turas89** [comment]
Ok, I've tried to make LogCat using Android Studio and my conclusion is: https://ragarwo.files.wordpress.com/2014/02/12968-i-have-no-idea-what-im-doing1.jpg ;)

But here it is, filtered with the word "last". If that's not enough, tell me please what should I do to get a proper log.

02-12 13:01:13.069: E/fb4a(:<default>):HanziToPinyin(17645): Internal error in Unihan table. The last string "呵" is greater than current string "哎".
02-12 13:09:23.969: V/IPC(18087): Current service version 51031587, last check version 51031587
02-12 13:11:40.689: D/Handshaker(17187): Handshaking: Last.fm
02-12 13:11:41.329: E/Handshaker(17187): Handshake fails: bad time: Last.fm
02-12 13:11:41.349: I/Handshaker(17187): Tempfail: Client side timing error, retrying…: Last.fm
02-12 13:11:41.359: D/Sleeper(17187): start sleeping: 60000: Last.fm
02-12 13:12:41.359: D/Sleeper(17187): woke up sleeping: Last.fm
02-12 13:12:41.369: D/Handshaker(17187): Handshaking: Last.fm
02-12 13:12:41.849: E/Handshaker(17187): Handshake fails: bad time: Last.fm
02-12 13:12:41.849: I/Handshaker(17187): Tempfail: Client side timing error, retrying…: Last.fm
02-12 13:12:41.869: D/Sleeper(17187): start sleeping: 120000: Last.fm
02-12 13:14:41.869: D/Sleeper(17187): woke up sleeping: Last.fm
02-12 13:14:41.879: D/Handshaker(17187): Handshaking: Last.fm
02-12 13:14:42.379: E/Handshaker(17187): Handshake fails: bad time: Last.fm
02-12 13:14:42.379: I/Handshaker(17187): Tempfail: Client side timing error, retrying…: Last.fm
02-12 13:14:42.399: D/Sleeper(17187): start sleeping: 240000: Last.fm
02-12 13:18:42.399: D/Sleeper(17187): woke up sleeping: Last.fm
02-12 13:18:42.409: D/Handshaker(17187): Handshaking: Last.fm
02-12 13:18:42.909: E/Handshaker(17187): Handshake fails: bad time: Last.fm
02-12 13:18:42.909: I/Handshaker(17187): Tempfail: Client side timing error, retrying…: Last.fm
02-12 13:18:42.919: D/Sleeper(17187): start sleeping: 480000: Last.fm
02-12 13:26:42.919: D/Sleeper(17187): woke up sleeping: Last.fm
02-12 13:26:42.929: D/Handshaker(17187): Handshaking: Last.fm
02-12 13:26:43.479: E/Handshaker(17187): Handshake fails: bad time: Last.fm
02-12 13:26:43.489: I/Handshaker(17187): Tempfail: Client side timing error, retrying…: Last.fm
02-12 13:26:43.499: D/Sleeper(17187): start sleeping: 960000: Last.fm
02-12 13:30:38.939: V/IPC(19087): Current service version 51031587, last check version 51031587

**Comment by inverse** [comment]
I think this is enough information to go on. It looks like an issue with the communication to last.fm and the timestamps of the tracks.

> The timestamp provided was not close enough to the current time. The system clock must be corrected before re-handshaking.

Perhaps you could adjust your devices clock either from network time, manually, or with an app (https://play.google.com/store/apps/details?id=ru.org.amip.ClockSync&hl=en)

**Comment by turas89** [comment]
Didn't work either :( I used ClockSync but "scrobble now" still doesn't do anything.

**Comment by inverse** [comment]
Anyone else have any idea why this happening?

**Comment by turas89** [comment]
I can try to log on to last.fm again but then I will probably lose my scrobbles for good. So, as Inverse says, any ideas?

**Comment by inverse** [comment]
I don't see why scrobbling would clear the cache. If in doubt you could always create a backup of the APK using the adb tools.

**Comment by turas89** [comment]
Today I found out that "clear credentials" button doesn't work either. Just like "scrobble now".  I've created a backup and later I'll try to reinstall the whole app.

**Comment by LiteraryRecluse** [comment]
It might be unrelated, but I have also had this issue for years, and only just discovered it was because I turned "background data" off on my phone.  I turned it off because I didn't want apps auto-updating and using up my data plan, but for some reason it didn't cross my mind that it would also stop the scrobbler from syncing. (Even if I push it manually.)

Anyway, it might be something to consider.

**Comment by HumbleBeeBumbleBee** [comment]
@turas89 
@LiteraryRecluse 

Please scrobble everything in your cache.
Uninstall Simple Last.fm Scrobbler.
Install this .apk.

https://drive.google.com/file/d/0B9lPaMaVVtiJRDdTQzBWRGRuOTQ/view?usp=sharing

**Comment by HumbleBeeBumbleBee** [comment]
https://github.com/tgwizard/sls/files/389151/app-debug.zip

**Comment by HumbleBeeBumbleBee** [comment]
With new devices this could be a mixture of background data off OR power saving mode.

**Comment by JonisK** [comment]
On Android Marshmallow, I had some problems with the Scrobble Now button, too. After removing SLS from the list of battery-optimized apps, its functionality is restored.
