### ISSUE TITLE
Scrobbler stopped working on Kindle Fire - Jan/Feb 2016

### ISSUE THREAD

**Issue by kowalskie** [tgwizard/sls#249]
All was working well (v1.4.9) on my Kindle Fire 7 (the cheep basic one) until (about) the 1st Feb 2016. 

I then started getting the "Wrong username/password" error on the last.fm authentication page. 
I did the "Clear Credentials" and re-entered my details but still get the same error. 

I uninstalled the app and downloaded the latest version (v1.4.9) again and started from scratch but again got the same error (my last.fm username/password was not accepted)

Also, now i have put a fresh install on when i got to the "Enabled apps" page it gives me a message of "No music apps detected". Previous to the reinstall this found the default Amazon Music player that i was using. 

My device is running Fire OS 5.1.1 (which seems to have been released mid december 2015, i don't know when i got the update...) and using the 'standard' Amazon Prime Music player.

Thanks for any info

**Comment by inverse** [comment]
So you can now authenticate correctly, Just are unable to scrobble tracks from the Amazon Prime Music player. Is this the same as the one on the play store or a fireos specific one?

**Comment by kowalskie** [comment]
Sorry if my post sounded confusing.

No, still can't authenticate. 

After reinstalling i can also not even see the Amazon Music player in the "Enabled Apps" section. This is the default Fire Amazon Prime Music Player, it comes pre-installed and i think it is somewhat different to the store was as it seems to be more integrated into the whole OS.

**Comment by SathyaBhat** [comment]
Try changing your password on last.FM and login here. It's some problem with last.fm and ran into the Same problem with Spotify and SLS.

Once password changed, I logged in with new password and it worked fine

**Comment by kowalskie** [comment]
Sorry for the delay in replying - but YES. that fixes it. 

I just went to last.fm and changed my password, then updated the scrobbler with my new password and, boom, sorted, back in the room, etc...

Odd. Especially as with the 'wrong' credentials it didn't even pick up the music player on the device...

Many thanks!
