### ISSUE TITLE
Exclude certain songs from being scrobbled

### ISSUE THREAD

**Issue by aouelete** [tgwizard/sls#252]
What I imagine is a setting that excludes certain songs from being scrobbled based on words present in the title, artist, etc. This would be extremely useful when listening to music from Spotify or Google Music where  there are occasional ads that obviously should not be scrobbled.

Would it be possible to implement such a feature?

**Comment by kelchm** [comment]
Ideally it would also be possible to prevent things from scrobbling based on length. This would be a relatively simple way to prevent podcasts that are played in Play Music from being scrobbled.

**Comment by aouelete** [comment]
The only problem I see with such an implementation is that some songs (not that many, though) can be just as short as an ad.

Although, on the other hand, such songs are almost always part of an album as a whole. If you're listening to a purchased album, then there shouldn't be any ads, so this approach could work.

**Comment by HumbleBeeBumbleBee** [comment]
Google Play adds shouldn't scrobble with the latest version.
This could be implemented.

**Comment by HumbleBeeBumbleBee** [comment]
Duplicate #127
