### ISSUE TITLE
add support for Youtube Music

### ISSUE THREAD

**Issue by Tanmay-r** [tgwizard/sls#253]
I stream my music mostly on youtube music on android and there are web scrobblers which scrobble from youtube on chrome on desktop. So, I was wondering if there is a way sls can scrobble youtube music app.

**Comment by cjones26** [comment]
+1 for this, recently started utilizing the YouTube Red "YT Music" app--would LOVE to see this supported!

**Comment by Rebkos** [comment]
I second that. 

I use PowerAmp mostly and it works good. But sometimes I go for Youtube (usually because i just don't have enough free space so I have only fraction of my collection stored in phones, tablets and iPod.) and I would like to get scrobbles from listening to that aswell

**Comment by HumbleBeeBumbleBee** [comment]
YouTube music does not support track information broadcasts currently.

I have sent an email to ytmusic-support@google.com requesting they broadcast song information so SLS can scrobble music played in Youtube Music.

**Comment by Tanmay-r** [comment]
Thanks for the information. Please keep us updated.

**Comment by wmvoje** [comment]
Any progress made here? Is the lack of broadcasting still the only issue?

**Comment by a93h** [comment]
Closed in place of #437 please continue there.
