### ISSUE TITLE
Add button "Get it on F-Droid"

### ISSUE THREAD

**Issue by PanderMusubi** [tgwizard/sls#254]
Please, add a button "Get it on F-Droid" with a PNG file from https://commons.wikimedia.org/wiki/File:Get_it_on_F-Droid.svg in your README.md file on GitHub with the appropriate link to the page of your app on F-Droid.

**Comment by Allanitomwesh** [comment]
I like this idea +1

**Comment by PanderMusubi** [comment]
For reference implementation, see https://github.com/PanderMusubi/trickytripper/commit/9e0a1da3e9dfe164791f1cd6ad988ea8c61a9e6d
