### ISSUE TITLE
not detect any music player

### ISSUE THREAD

**Issue by Msamurai** [tgwizard/sls#255]
couple days ago it worked very fine until i had to reset my phone into factory reset
after the reset the sls not detect rocket music player at all it it's read poweramp and deezer as android music player
i tried other scrobbler like official last fm and wail and it's working fine the problem is in sls
i tried reset the phone again  and again nothing new please any one can help me

**Comment by HumbleBeeBumbleBee** [comment]
Could you share your phone model and android version?

**Comment by Msamurai** [comment]
Lenovo A536 
Kitkat 4.4.2
It work fine now but not detect spotify

**Comment by Msamurai** [comment]
It happened again

**Comment by Msamurai** [comment]
About the last answer don't mind it it Work fine except Spotify

**Comment by Msamurai** [comment]
I feel so dump thank you for your answer 
I didn't notice that information broadcast is off in spotify
Thank you again
