### ISSUE TITLE
Add support for Timber

### ISSUE THREAD

**Issue by wb9688** [tgwizard/sls#256]
Can you please add support for [Timber](https://github.com/naman14/Timber)?

**Comment by HumbleBeeBumbleBee** [comment]
I can ask the developers or try to write the code.
I'll look into it.
There are lots of music apps in the meantime.

**Comment by HumbleBeeBumbleBee** [comment]
Timber supports SLS now.
https://play.google.com/store/apps/details?id=naman14.timber
The latest version is broadcasting.
