### ISSUE TITLE
Tracks scrobbled twice while listening via SONOS

### ISSUE THREAD

**Issue by piemmepi** [tgwizard/sls#258]
I am experiencing an issue where tracks are scrobbled twice while listening from Google Play Music and casting the audio to a SONOS device. Any chance there is a workaround for this? I am using the latest version of all the relevant apps.

**Comment by HumbleBeeBumbleBee** [comment]
Does SONOS have any option to disable track information broadcasts?

**Comment by piemmepi** [comment]
Couldn't find any option similar to that on the Android app :(
The closest thing was an option to enable/disable the notification.

By the way, this only happens if, from within Google Play Music, I cast to the SONOS, but not if I play Google Play Music tracks from within the SONOS app.

**Comment by HumbleBeeBumbleBee** [comment]
SONOS app is broadcasting track information too. Have you tried changing enabled/disabled apps in SLS?

**Comment by HumbleBeeBumbleBee** [comment]
Strange there does not seem to be a good solution.

**Comment by HumbleBeeBumbleBee** [comment]
SONOS and Google Play are probably both broadcasting track data and clashing.

Could you please try this app?
https://drive.google.com/open?id=0B9lPaMaVVtiJaGwwdkt0UjBNVHc
Make sure all your scrobbles are submitted.

I will close this for now.

**Comment by piemmepi** [comment]
Hi, I have tried to install the application with no success. I have enabled installing applications from unknown sources, etc... but I get a message saying "App not installed". 

I have a Sony Z5 compact + Marshmallow if that helps.

Cheers

**Comment by HumbleBeeBumbleBee** [comment]
https://drive.google.com/file/d/0B9lPaMaVVtiJTm9nRktLTVdvREU/view?usp=sharing

**Comment by piemmepi** [comment]
Same result :(

**Comment by HumbleBeeBumbleBee** [comment]
Did you uninstall the previous version?

**Comment by piemmepi** [comment]
Oh I hadn't tried it that way. I can install it now and it seems to fix the
issue!

Thanks

**Comment by HumbleBeeBumbleBee** [comment]
@piemmepi It actually worked? Please let me know if you have any problems.

**Comment by piemmepi** [comment]
Yes it seems to be working fine. Tracks cast from the play music app to the
sonos are scrolled once, and tracks played from within the sonos app are
still working
