### ISSUE TITLE
Avoid scrobbling advertisements

### ISSUE THREAD

**Issue by BalooUriza** [tgwizard/sls#259]
Google Play Music Radio now inserts ads every 2-5 songs. It would be nice to not scrobble these fake tracks during the ads, as otherwise it quickly becomes the top listened to track.

**Comment by HumbleBeeBumbleBee** [comment]
Hello thank you for this info. I had the same problem with Spotify. Hopefully there is a good fix.

**Comment by HumbleBeeBumbleBee** [comment]
I have been testing this on my phone and it doesn't seem to be a problem.

**Comment by HumbleBeeBumbleBee** [comment]
I am going to close this, because the updated version of Google Play doesn't seem to scrobble commercials.
