### ISSUE TITLE
Can not login

### ISSUE THREAD

**Issue by dufferzafar** [tgwizard/sls#260]
I am unable to login to my last.fm account using Simple Last.fm Scrobbler. It just keeps on showing "Wrong username/password". I can login to my libre.fm account using that app though.

I know this sounds like I'm just typing out my username/password wrong, but trust me, I am not.

FWIW, I wasn't able to login on the official Last.fm app (as it was outdated) but once I updated it to the latest version, It started working. I am also able to login on the last.fm website.

I remember something like this happened with Clementine player (on Linux) too, but once an update rolled in, things worked fine. https://github.com/clementine-player/Clementine/issues/5005

Anyone know how I can debug this?

**Comment by dufferzafar** [comment]
I also tried WAIL, and it seems to be working fine, it's about the web based login I guess, since the new last.fm app also does login via web.

**Comment by dufferzafar** [comment]
From a [reddit comment](https://www.reddit.com/r/lastfm/comments/4iajpo/cant_login_to_lastfm_using_a_bunch_of_android_apps/d2yzabf):

> This sounds awfully like a discontinuation of the 1.2 version of the scrobbling API. Version 2.0, which is much more secure (does not send your password in plaintext, for instance), uses something called OAuth (this basically means that you have to authenticate in a browser, instead of entering your password in the app you're logging in to), and was supposed to take over a long time ago, though I guess they kept 1.2 around for compatibility reasons. If 1.2 is now gone, that means a lot of scrobblers will stop working, as many of them only support 1.2. I hope this isn't the case. Either way, it's all just speculation.

**Comment by bilde2910** [comment]
Just decided to do some digging around for fun (I posted the comment quoted by @dufferzafar). The authentication API for 1.2.1 seems to work right now - I am getting an "OK" response, so unless it isn't working now, it may just have been a temporary downtime. So I'd just suggest one thing - try again now :-)

I also forgot that 1.2 doesn't actually send the password in plaintext. I *thought* it did, but after reading the API docs again, I realized that it apparently hashes it with md5 twice. That's better, but it's still not good enough by today's standards.

**Comment by dufferzafar** [comment]
I just reinstalled SLS and test again. It still does not work. :cry:

**Comment by AhmedKamal20** [comment]
Mine stopped scrobbling too, by the same error, cleared the app data/cache and tried again, doesn't help.

**Comment by dufferzafar** [comment]
I'm seeing all these errors on my new tablet, while my phone is still running the Official Last.fm App for Android, but NOT the latest version, it still uses the old version which does auth by the 1.2 API.

So, I think that clients who are already logged in via the old API keep on working but new clients don't work. @bilde2910 Does this sound reasonable?

**Comment by AhmedKamal20** [comment]
I was already logged in, and got the error.
but it appeared yesterday at night, not 3 days ago when you start the issue, so, maybe they logging out gradually.

**Comment by bilde2910** [comment]
I don't know, really. Quoting the [submissions API page](http://www.last.fm/api/submissions),

> #### This protocol is now deprecated! Please use the Scrobbling API.

> **Note:** There is now a new way for sending scrobbles called the [Scrobbling API](http://www.last.fm/api/scrobbling) which is integrated into the rest of the Last.fm Web Services as opposed to being a separate service like 1.2.1. New clients should all use the Scrobbling API and not this protocol as we will not be issuing new client ids for this protocol and are likely to disable the "tst" client id at some point.

That's really all I know at this point. Still, it's strange that they would disable access gradually, and not just cut access for everybody at the same time. Stranger still that they would do it without notification.

**Comment by inverse** [comment]
Perhaps it's time to think about migrating to the newer API. Will mean we can remove the need to store the hashed password from the app to which is always a plus.

**Comment by sebasalazar** [comment]
I have the dame issue, from May 16, I can't login u.u

**Comment by HumbleBeeBumbleBee** [comment]
Please make sure your phone time is correct.

**Comment by HumbleBeeBumbleBee** [comment]
Troubleshooting

1. Check your phone's time.
2. Check battery/power settings on phone add SLS to protected/whitelist (power save disabled).
3. Check SLS options. (power settings)
4. Check if Last.fm is down. http://status.last.fm
5. Check enabled apps. example. (Neutron music disabled stops some random scrobbles for me.)
6. Make sure you can login to last.fm on your phone browser. (That means SLS is the problem if you can't.)
7. Check settings in your music playing/streaming app for enabling scrobbling.
8. Make sure your songs have the required metadata information. https://musicbrainz.org 
9. Make sure your scrobbles are not scrobbled too late. (2 weeks)
10. Create an issue on github or email us or google community post.

**Comment by HumbleBeeBumbleBee** [comment]
Has anybody found a solution?

**Comment by HumbleBeeBumbleBee** [comment]
Please continue on #250
