### ISSUE TITLE
Feature Request: Foobar2000 Android support

### ISSUE THREAD

**Issue by danhash** [tgwizard/sls#264]
The Foobar2000 media player now has an Android app (http://mobile.foobar2000.com/). What would it take to add support to SLS for Foobar2000?

**Comment by HumbleBeeBumbleBee** [comment]
I have sent an email to mobile@foobar2000.com requesting they broadcast song information so SLS can scrobble music played in foobar2000 Mobile.

**Comment by HumbleBeeBumbleBee** [comment]
It seems to be working now. It will appear as the stock music player.
