### ISSUE TITLE
huawei music player

### ISSUE THREAD

**Issue by Oxeda** [tgwizard/sls#265]
is there any way to make it work with this extraordinary player? 

version:6.130.301

**Comment by HumbleBeeBumbleBee** [comment]
#225
*Looks like putting both music player and SLS into the list of "protected apps" under Battery settings resolved this issue for me.* - Same Question

**Comment by Oxeda** [comment]
Yeah same question, different answer though, not every phone has the same battery settings :(

**Comment by HumbleBeeBumbleBee** [comment]
Could you please try musixmatch to see if the lyrics show up. I can't really test a builtin app except with a third party download site.

**Comment by Oxeda** [comment]
thanks for replying, yea i tried musicxmatch, it doesn’t show up, about the app, i downloaded it from the official huawei site [here](http://appstore.huawei.com/app/C10021449) just click at the blu-green button with the computer icon, that’s the official application. thx.

**Comment by Oxeda** [comment]
oh, don’t worry about the language, that site is in chinese but the app has english texts.

**Comment by HumbleBeeBumbleBee** [comment]
Well my computer keeps detecting the exe and apk as a virus and the links as malware.

**Comment by HumbleBeeBumbleBee** [comment]
Well. It seems you are correct. It has intents. Thank you.

**Comment by Oxeda** [comment]
mmm that’s weird, that’s the official huawei site, you can check it at google search, maybe your browser thinks that’s a virus because the language. If you google the full link you gonna see a lot of people download it from there, there are a bunch of other huawei apps. [screenshot](http://imgur.com/a/jkzxJ)

**Comment by HumbleBeeBumbleBee** [comment]
Here's a copy of the apk.
https://drive.google.com/file/d/0B9lPaMaVVtiJbW0tT3RvWTFwalE/view?usp=sharing
It works now.
Could you please check it for mistakes?

**Comment by HumbleBeeBumbleBee** [comment]
That has a Huawei in it.

**Comment by Oxeda** [comment]
thx! gonna try it right now

**Comment by Oxeda** [comment]
:) awesome, it’s working! thank you very very very much, now the huawei app is perfect :)

**Comment by Oxeda** [comment]
working perfectly: http://www.last.fm/es/user/Tlamaki

thanks again!

**Comment by HumbleBeeBumbleBee** [comment]
Very welcome. Please, I beg you, tell me any problems you have with it.

**Comment by Oxeda** [comment]
:) i will!

**Comment by HumbleBeeBumbleBee** [comment]
@Oxeda I am going to close this for now. If you have further questions, I will reopen this for you.
