### ISSUE TITLE
No music players available

### ISSUE THREAD

**Issue by Pauloxzak** [tgwizard/sls#266]
Just acquired a new phone and installed SLS to work with my poweramp as usual. On previous phone worked fine also with poweramp (it was an asus zenfone 5), but now it doesn't recognize any music players at all, not even stock player.
New phone: Asus Zenfone 2 Deluxe 
Android: 5.0 Lollipop
Not rooted, stock firmware
Any help? Thanks!

**Comment by HumbleBeeBumbleBee** [comment]
Hello. Have you checked your battery settings and music app settings?
I have no idea why it won't detect the stock app.

**Comment by Pauloxzak** [comment]
Hi,
not sure why it happened either.
After reinstalling and rebooting twice, it recognized the both, the stock app and poweramp. seems to be working fine now. =)

**Comment by HumbleBeeBumbleBee** [comment]
Great. It's tough to debug without access. Will try to test in emulator, but some important updates should be coming soon.

**Comment by Pauloxzak** [comment]
Cool! I'd guess it's something related to the auto install android does when you sync your account on a new device. I had problems once redeeming premium version of another app on this scenario, also solved after reinstalling and some reboots.

**Comment by HumbleBeeBumbleBee** [comment]
Ok. I will close those issue for now.
