### ISSUE TITLE
Translate to Polish

### ISSUE THREAD

**Issue by Grzes58** [tgwizard/sls#267]
Hello,
I like your app and I think that I can help you with translate it to polish.

**Comment by HumbleBeeBumbleBee** [comment]
OK.  There is a translation program in Android Studio or tx https://www.transifex.com/sls/sls/

**Comment by HumbleBeeBumbleBee** [comment]
You can always make a copy of the English translotion and overwrite it in your language manually.
https://github.com/tgwizard/sls/blob/master/app/src/main/res/values/strings.xml

**Comment by Grzes58** [comment]
Ok, thanks. I send request for polish language.

**Comment by Grzes58** [comment]
I've already finished translate. Sometimes I had problem, because it's hard to translate to polish not knowing the context.I overwrite english version in txt file. Can I send you this file somehow? Or paste it to comment in this issue?

**Comment by HumbleBeeBumbleBee** [comment]
Create a repository or paste it here.

**Comment by Grzes58** [comment]
<?xml version="1.0" encoding="utf-8"?>
<resources>

    
    <string name="close">Wyjście</string>
    <string name="remove">Usuń</string>
    <string name="reset">Zresetuj</string>
    <string name="clear_creds">Wyczyść</string>
    <string name="are_you_sure">Jesteś pewien?</string>
    <string name="warning">Ostrzeżenie</string>
    <string name="will_submit_stuff">Informacja o słuchaniu zostanie udostępniona na tej stronie</string>
    <string name="also_disable_np_title">Wyłącz równiez teraz odtwarzane</string>
    <string name="also_disable_np_summary">[Hmpf]</string>
    
    
    
    <string name="by">przez</string>
    <string name="issues">Problemy: %s</string>
    <string name="website">Strona tytułowa: %s</string>
    <string name="by_adam">przez Adam Renberg</string>
    <string name="license">Wydano na podstawie Apache License v2.0</string>
    <string name="about_text">Lekki scrobbler wysyłający informację do serwisu Last.fm (i/lub Libre.fm)na temat tego jakiej muzyki słuchasz na swoim smartfonie. Last.fm pozwoli wyświetlić Ci statystyki słuchanych utworów oraz przedstawi rekomendacje muzyki, którą być może polubisz.</string>
    <string name="everything_disabled">Scrobblowanie/odtwarzanie jest wyłączone.</string>
    <string name="file_error">Błąd pliku!</string>
    <string name="thats_new">Oto, co nowego</string>
    <string name="about">O</string>
    <string name="whats_new">Co nowego</string>
    <string name="supported_netapps">Wspierane strony internetowe: %1</string>
    <string name="supported_apps">Wspierane aplikacje: %s i więcej…</string>
    

    
    <string name="scrobbles_cache_nonum">Scrobble w pamięci lokalnej:</string>
    <string name="scrobbles_cache">Scrobble w pamięci lokalnej: %1</string>
    <string name="db_error">Błąd bazy danych</string>
    <string name="scrobble_now">Aktualnie scrobblowane</string>
    <string name="reset_stats">Zresetuj statystyki</string>
    <string name="scrobble_cache_title">Pamięć podręczna scrobbli</string>
    <string name="confirm_delete_sc">Jesteś pewien, że nie chcesz scrobblować tego utworu do %1? Ta operacja nie będzie mogła zostać cofnięta.</string>
    <string name="confirm_delete_sc_from_all">Jesteś pewien, że nie chcesz scrobblować tego utworu? Ta operacja nie będzie mogła zostać cofnięta.</string>
    <string name="confirm_delete_all_sc">Jesteś pewien, że chcesz usunąć scrobble z pamięci podręcznej dla %1? Ta operacja nie będzie mogła zostać cofnięta.</string>
    <string name="confirm_delete_all_sc_from_all">Jesteś pewien, że chcesz usunąć scrobble z pamięci podręcznej? Ta operacja nie będzie mogła zostać cofnięta</string>
    <string name="no_scrobbles_in_cache">Brak scrobbli w pamięci podręcznej</string>
    <string name="view_sc">Wyświetl scrobble w pamięci podręcznej</string>
    <string name="view_sc_details">Wyświetl szczegóły</string>
    <string name="delete_sc">Usuń z pamięci podręcznej</string>
    <string name="clear_cache">Wyczyść pamięć podręczną</string>
    <string name="track_info">Informacje o utworze</string>
    <string name="view_sc_title_for">Pamięć podręczna scrobbli dla %1</string>
    <string name="view_sc_for_all_summary">Wyświetl i edytuj listę niewysłanych scrobbli</string>
    <string name="all_websites">Wszystkie strony internetowe</string>
    <string name="sc_sorted_by">Zamówione przez: %1</string>
    <string name="sc_sort_title">Sortuj według</string>
    <string name="sc_sortorder_change">Zmień kolejność sortowania</string>
    <string name="sc_sort_when_asc">Czas odtwarzania, rosnąco</string>
    <string name="sc_sort_when_desc">Czas odtwarzania, malejąco</string>
    <string name="sc_sort_artist_asc">Artysta, rosnąco</string>
    <string name="sc_sort_artist_desc">Artysta, malejąco</string>
    <string name="sc_sort_album_asc">Album, rosnąco</string>
    <string name="sc_sort_album_desc">Album, malejąco</string>
    <string name="sc_sort_track_asc">Nazwa utworu, rosnąco</string>
    <string name="sc_sort_track_desc">Nazwa utworu, malejąco</string>
      
    
    
    <string name="user_credentials_title">Ustawienia danych użytkownika</string>
    <string name="user_credentials_summary">Ustaw nazwę oraz hasło dla swojego %1 konta</string>
    <string name="user_credentials_summary_no_napp">Ustaw nazwę oraz hasło dla swojego konta</string>
    <string name="user_credentials_enter_ok">Uwierzytelnienie</string>
    <string name="user_credentials_enter_cancel">Powrót</string>
    <string name="user_credentials_clear_title">Wyczyść dane użytkownika</string>
    <string name="user_credentials_clear_summary">Wyczyść nazwę użytkownika oraz sesję</string>
    <string name="supported_netapps_category_title">Wspierane strony internetowe</string>
    <string name="username">Nazwa użytkownika</string>
    <string name="password">Hasło</string>
    <string name="auth_client_banned">Niniejsza wersja aplikacji jest przestarzała. Proszę o zaktualizowanie jej.</string>
    <string name="auth_bad_auth">Nieprawidłowa nazwa użytkownika/hasło</string>
    <string name="auth_server_error">Błąd serwera: %1, Ponowna próba…</string>
    <string name="auth_timing_error">Przekroczono czas po stronie klienta. Ponowna próba…</string>
    <string name="auth_network_error_retrying">Błąd sieci. Ponowna próba…</string>
    <string name="auth_network_unfit">Niedozwolone udostępnienie danych w sieci, zmień ustawienia na ekranie opcji.</string>
    <string name="auth_updating">Uwierzytelnianie…</string>
    <string name="auth_internal_error">Błąd wewnętrzny</string>
    <string name="auth_just_error">Błąd, ponowna próba…</string>
    <string name="logged_in_just">Logged in as:</string>
    <string name="logged_in_as">Zalogowany jako: %1</string>
    <string name="log_in_to">Zaluguj do</string>
    <string name="not_logged_in">Nie zalogowany w</string>
    <string name="create_user_title">Zaloguj się</string>
    <string name="create_user_summary">Zaloguj się na konto %1</string>
    <string name="confirm_clear_creds">Jesteś pewien, że chcesz wyczyścić uwierzytelnienia użytkownika dla for %1? Ta operacja spowoduje również usunięcie niewysłanych scrobbli.</string>
    <string name="confirm_clear_all_creds">Jesteś pewien, że chcesz wyczyścić uwierzytelnienia użytkownika dla wszystkich zalogowanych kont? Ta operacja spowoduje również usunięcie niewysłanych scrobbli.</string>
    
    
    
    <string name="incompatability_short">Ostrzeżenie: %1$s jest zainstalowany i może powodować zdublowanie scrobbli.</string>
    <string name="incompatability_long">Ostrzeżenie: %1$s jest zainstalowany i może powodować niekompatybilność przy scrobblowaniu. Wyłącz scrobblowanie w tej aplikacji lub ją odinstaluj. %1$s.</string>
    <string name="show_supported_apps_list_summary">Włączone/wyłączone scrobblowanie z applikacji</string>
    <string name="supported_apps_category_title">Włączone aplikacje</string>
    <string name="app_disabled">Nie scrobbluj muzyki z tej aplikacji</string>
    <string name="not_installed">Ta aplikacja nie jest zainstalowana</string>
    <string name="no_supported_mapis_title">Nie wykryto aplikacji odtwarzających muzykę</string>
    <string name="find_supported_mapis_one_title">Została wykryta 1 aplikacja odtwarzająca muzykę</string>
    <string name="find_supported_mapis_many_title">Zostały wykryte %1 aplikacje odtwarzające muzykę</string>
    <string name="find_supported_mapis_summary">Odtwórz muzykę w wspieranej aplikacji a wtedy tutaj się pojawi</string>
    <string name="unknown_mapi">Nieznana aplikacja (pre SLS v1.2.3)</string>
    
    
    
    <string name="options_title">Opcje</string>
    <string name="advanced_options_title">Opcje zaawansowane</string>
    <string name="scrobbling">Scrobble</string>
    <string name="scrobbling_enable">Udostępniaj informacje o odtwarzaniu, gdy słuchasz piosenki</string>
    <string name="nowplaying">Udostępniaj aktualnie słuchane</string>
    <string name="nowplaying_enable">Udostępniaj informację o aktualnie słuchanym utworze</string>
    <string name="scrobble_point_title">Punkt scrobblowania</string>
    <string name="scrobble_point_summary">Scrobble zostaną dodane do bazy danych po wysłuchaniu %1% utworu</string>
    <string name="ao_battery_title">Podczas używania baterii</string>
    <string name="ao_plugged_title">Podczas używania z podłączoną ładowarką</string>
    <string name="options_summary">Zawrzeć ustawienia oszczędzania baterii</string>
    <string name="advanced_options_custom_category_title">Modyfikowane ustawienia scrobblowania</string>
    <string name="advanced_options_when_title">Kiedy scrobblować</string>
    <string name="advanced_options_also_on_complete_title">Również po zakończeniu playlisty</string>
    <string name="advanced_options_also_on_complete_summary">Scrobblowanie również wtedy, gdy skończysz słuchać playlisty</string>
    <string name="advanced_options_also_on_plugged_title">Również wtedy, gdy podłączona jest ładowarka</string>
    <string name="advanced_options_also_on_plugged_summary">Również wtedy, gdy jesteś podłączony do źródła zasilania</string>
    <string name="should_disable_np">Powinieneś również wyłączyć udostępnianie informacji o aktualnie słuchanym utworze, aby zaoszczędzić baterię.</string>
    <string name="advanced_options_type_standard_name">Standardowe</string>
    <string name="advanced_options_type_battery_name">Oszczędzanie baterii</string>
    <string name="advanced_options_type_same_as_battery_name">Takie same jak dla oszczędzania baterii</string>
    <string name="advanced_options_type_custom_name">Modyfikowane</string>
    <string name="advanced_options_when_1_name">Po każdym uwtorze</string>
    <string name="advanced_options_when_5_name">Po pięciu utworach</string>
    <string name="advanced_options_when_10_name">Po dziesięciu utworach</string>
    <string name="advanced_options_when_25_name">Po 25 utworach</string>
    <string name="advanced_options_when_never_name">Gdy naciśniesz przycisk "scorbbluj teraz"</string>
    <string name="advanced_options_net_title">Sieć</string>
    <string name="advanced_options_net_summary">Udostępniaj informacje dla: %1</string>
    <string name="advanced_options_net_any_name">Jakakolwiek sieć</string>
    <string name="advanced_options_net_3gup_name">3G i Wifi</string>
    <string name="advanced_options_net_wifi_name">Tylko Wifi</string>
    <string name="advanced_options_net_roaming_title">Roaming</string>
    <string name="advanced_options_net_roaming_summary_off">Nie udostępniaj informacji, gdy jesteś w roamingu</string>
    <string name="advanced_options_net_roaming_summary_on">Udostępniaj informacje, gdy jesteś w roamingu</string>
    
    
    
    <string name="status">Status</string>
    <string name="scrobble_status_title">Status scrobbli</string>
    <string name="other_category_title">Inne</string>
    <string name="status_show_title">Status</string>
    <string name="status_show_summary">Pokaż statystyki i cały status</string>
    <string name="status_title">Informacje o statusie</string>
    <string name="scrobbling_disabled">Scrobblowanie jest wyłąćzone</string>
    <string name="scrobble_last_at">Ostatnio udostępnione informacje o scrobblach:</string>
    <string name="scrobble_last_fail_at">Ostatnio nieudane udostępnienie informacji o scrobblach:</string>
    <string name="nowplaying_disabled">Udostępnianie informacji o aktualnie słuchanym utworze są wyłączone</string>
    <string name="nowplaying_last_at">Ostatnio udostępniona informacja o aktualnie słuchanym utworze:</string>
    <string name="nowplaying_last_fail_at">Ostatnio nieudane udostępnienie informacji o scrobblach:</string>
    <string name="stats_scrobbles">Liczba wszystkich zascrobblowanych utworów:</string>
    <string name="never">Nigdy</string>
    <string name="stats_nps">Liczba wszystkich informacji o aktualnie granym utworze:</string>
    <string name="it_was">To było:</string>
    <string name="confirm_stats_reset">Jesteś pewien, że chcesz zresetować statystyki o udostępnianiu dla %1? Ta operacja nie będzie mogła zostać cofnięta.</string>
    <string name="profile_page">Strona profilu</string>
    
    
</resources>

**Comment by HumbleBeeBumbleBee** [comment]
I can get you an app tomorrow with your language in it.

**Comment by Grzes58** [comment]
Ok, no problem.

**Comment by HumbleBeeBumbleBee** [comment]
https://drive.google.com/file/d/0B5waOgiB_JImaDdyVXVRRmhOSUU/view?usp=drivesdk

**Comment by Grzes58** [comment]
There's a couple mistakes. Now it's good

<?xml version="1.0" encoding="utf-8"?>
<resources>

    
    <string name="close">Wyjście</string>
    <string name="remove">Usuń</string>
    <string name="reset">Zresetuj</string>
    <string name="clear_creds">Wyczyść</string>
    <string name="are_you_sure">Jesteś pewien?</string>
    <string name="warning">Ostrzeżenie</string>
    <string name="will_submit_stuff">Informacja o słuchaniu zostanie udostępniona na tej stronie</string>
    <string name="also_disable_np_title">Wyłącz równiez teraz odtwarzane</string>
    <string name="also_disable_np_summary">[Hmpf]</string>
    
    
    
    <string name="by">przez</string>
    <string name="issues">Zgłaszanie problemów: %s</string>
    <string name="website">Strona tytułowa: %s</string>
    <string name="by_adam">autorstwa Adama Renberga</string>
    <string name="license">Wydano na podstawie Apache License v2.0</string>
    <string name="about_text">Lekki scrobbler wysyłający informację do serwisu Last.fm (i/lub Libre.fm) na temat tego jakiej muzyki słuchasz na swoim smartfonie. Last.fm pozwoli wyświetlić Ci statystyki słuchanych utworów oraz przedstawi rekomendacje muzyki, którą być może polubisz.</string>
    <string name="everything_disabled">Scrobblowanie/odtwarzanie jest wyłączone.</string>
    <string name="file_error">Błąd pliku!</string>
    <string name="thats_new">Oto, co nowego</string>
    <string name="about">O aplikacji</string>
    <string name="whats_new">Co nowego</string>
    <string name="supported_netapps">Wspierane strony internetowe: %1</string>
    <string name="supported_apps">Wspierane aplikacje: %s i więcej…</string>
    

    
    <string name="scrobbles_cache_nonum">Scrobble w pamięci lokalnej:</string>
    <string name="scrobbles_cache">Scrobble zapisane w pamięci lokalnej: %1</string>
    <string name="db_error">Błąd bazy danych</string>
    <string name="scrobble_now">Scrobbluj teraz</string>
    <string name="reset_stats">Zresetuj statystyki</string>
    <string name="scrobble_cache_title">Pamięć podręczna scrobbli</string>
    <string name="confirm_delete_sc">Jesteś pewien, że nie chcesz scrobblować tego utworu do %1? Ta operacja nie będzie mogła zostać cofnięta.</string>
    <string name="confirm_delete_sc_from_all">Jesteś pewien, że nie chcesz scrobblować tego utworu? Ta operacja nie będzie mogła zostać cofnięta.</string>
    <string name="confirm_delete_all_sc">Jesteś pewien, że chcesz usunąć scrobble z pamięci podręcznej dla %1? Ta operacja nie będzie mogła zostać cofnięta.</string>
    <string name="confirm_delete_all_sc_from_all">Jesteś pewien, że chcesz usunąć scrobble z pamięci podręcznej? Ta operacja nie będzie mogła zostać cofnięta</string>
    <string name="no_scrobbles_in_cache">Brak scrobbli w pamięci podręcznej</string>
    <string name="view_sc">Pamięć podręczna</string>
    <string name="view_sc_details">Wyświetl szczegóły</string>
    <string name="delete_sc">Usuń z pamięci podręcznej</string>
    <string name="clear_cache">Wyczyść pamięć podręczną</string>
    <string name="track_info">Informacje o utworze</string>
    <string name="view_sc_title_for">Pamięć podręczna scrobbli dla %1</string>
    <string name="view_sc_for_all_summary">Wyświetl i edytuj listę niewysłanych scrobbli zapisanych w pamięci podręcznej</string>
    <string name="all_websites">Wszystkie strony internetowe</string>
    <string name="sc_sorted_by">Zamówione przez: %1</string>
    <string name="sc_sort_title">Sortuj według</string>
    <string name="sc_sortorder_change">Zmień kolejność sortowania</string>
    <string name="sc_sort_when_asc">Czas odtwarzania, rosnąco</string>
    <string name="sc_sort_when_desc">Czas odtwarzania, malejąco</string>
    <string name="sc_sort_artist_asc">Artysta, rosnąco</string>
    <string name="sc_sort_artist_desc">Artysta, malejąco</string>
    <string name="sc_sort_album_asc">Album, rosnąco</string>
    <string name="sc_sort_album_desc">Album, malejąco</string>
    <string name="sc_sort_track_asc">Nazwa utworu, rosnąco</string>
    <string name="sc_sort_track_desc">Nazwa utworu, malejąco</string>
      
    
    
    <string name="user_credentials_title">Ustawienia danych użytkownika</string>
    <string name="user_credentials_summary">Ustaw nazwę oraz hasło dla swojego konta w serwisie %1 </string>
    <string name="user_credentials_summary_no_napp">Ustaw nazwę oraz hasło dla swojego konta</string>
    <string name="user_credentials_enter_ok">Zaloguj</string>
    <string name="user_credentials_enter_cancel">Powrót</string>
    <string name="user_credentials_clear_title">Wyczyść dane użytkownika</string>
    <string name="user_credentials_clear_summary">Wyczyść nazwę użytkownika oraz sesję</string>
    <string name="supported_netapps_category_title">Wspierane strony internetowe</string>
    <string name="username">Nazwa użytkownika</string>
    <string name="password">Hasło</string>
    <string name="auth_client_banned">Niniejsza wersja aplikacji jest przestarzała. Proszę o zaktualizowanie jej.</string>
    <string name="auth_bad_auth">Nieprawidłowa nazwa użytkownika lub hasło</string>
    <string name="auth_server_error">Błąd serwera: %1, Ponowna próba…</string>
    <string name="auth_timing_error">Przekroczono czas po stronie klienta. Ponowna próba…</string>
    <string name="auth_network_error_retrying">Błąd sieci. Ponowna próba…</string>
    <string name="auth_network_unfit">Niedozwolone udostępnienie danych w sieci, zmień ustawienia na ekranie opcji.</string>
    <string name="auth_updating">Uwierzytelnianie…</string>
    <string name="auth_internal_error">Błąd wewnętrzny</string>
    <string name="auth_just_error">Błąd, ponowna próba…</string>
    <string name="logged_in_just">Zalogowany jako:</string>
    <string name="logged_in_as">Zalogowany jako: %1</string>
    <string name="log_in_to">Zaloguj do serwisu</string>
    <string name="not_logged_in">Nie zalogowany w</string>
    <string name="create_user_title">Zaloguj się</string>
    <string name="create_user_summary">Zaloguj się na konto %1</string>
    <string name="confirm_clear_creds">Jesteś pewien, że chcesz wyczyścić uwierzytelnienia użytkownika dla for %1? Ta operacja spowoduje również usunięcie niewysłanych scrobbli.</string>
    <string name="confirm_clear_all_creds">Jesteś pewien, że chcesz wyczyścić uwierzytelnienia użytkownika dla wszystkich zalogowanych kont? Ta operacja spowoduje również usunięcie niewysłanych scrobbli.</string>
    
    
    
    <string name="incompatability_short">Ostrzeżenie: %1$s jest zainstalowany i może powodować zdublowanie scrobbli.</string>
    <string name="incompatability_long">Ostrzeżenie: %1$s jest zainstalowany i może powodować niekompatybilność przy scrobblowaniu. Wyłącz scrobblowanie w tej aplikacji lub ją odinstaluj. %1$s.</string>
    <string name="show_supported_apps_list_summary">Włączone/wyłączone scrobblowanie z applikacji</string>
    <string name="supported_apps_category_title">Włączone aplikacje</string>
    <string name="app_disabled">Nie scrobbluj muzyki z tej aplikacji</string>
    <string name="not_installed">Ta aplikacja nie jest zainstalowana</string>
    <string name="no_supported_mapis_title">Nie wykryto aplikacji odtwarzających muzykę</string>
    <string name="find_supported_mapis_one_title">Została wykryta 1 aplikacja odtwarzająca muzykę</string>
    <string name="find_supported_mapis_many_title">Zostały wykryte %1 aplikacje odtwarzające muzykę</string>
    <string name="find_supported_mapis_summary">Odtwórz muzykę w wspieranej aplikacji a wtedy tutaj się pojawi</string>
    <string name="unknown_mapi">Nieznana aplikacja (pre SLS v1.2.3)</string>
    
    
    
    <string name="options_title">Opcje</string>
    <string name="advanced_options_title">Opcje zaawansowane</string>
    <string name="scrobbling">Scrobble</string>
    <string name="scrobbling_enable">Udostępniaj informacje o odtwarzaniu, gdy słuchasz piosenki</string>
    <string name="nowplaying">Udostępniaj aktualnie słuchane</string>
    <string name="nowplaying_enable">Udostępniaj informację o aktualnie słuchanym utworze</string>
    <string name="scrobble_point_title">Punkt scrobblowania</string>
    <string name="scrobble_point_summary">Scrobble zostaną dodane do bazy danych po wysłuchaniu %1% utworu</string>
    <string name="ao_battery_title">Podczas używania baterii</string>
    <string name="ao_plugged_title">Podczas używania z podłączoną ładowarką</string>
    <string name="options_summary">Zawiera ustawienia oszczędzania baterii</string>
    <string name="advanced_options_custom_category_title">Modyfikowane ustawienia scrobblowania</string>
    <string name="advanced_options_when_title">Kiedy scrobblować</string>
    <string name="advanced_options_also_on_complete_title">Również po zakończeniu playlisty</string>
    <string name="advanced_options_also_on_complete_summary">Wyślij scrobble również wtedy, gdy skończysz słuchać playlisty</string>
    <string name="advanced_options_also_on_plugged_title">Również wtedy, gdy podłączona jest ładowarka</string>
    <string name="advanced_options_also_on_plugged_summary">Również wtedy, gdy jesteś podłączony do źródła zasilania</string>
    <string name="should_disable_np">Powinieneś również wyłączyć udostępnianie informacji o aktualnie słuchanym utworze, aby zaoszczędzić baterię.</string>
    <string name="advanced_options_type_standard_name">Standardowe</string>
    <string name="advanced_options_type_battery_name">Oszczędzanie baterii</string>
    <string name="advanced_options_type_same_as_battery_name">Takie same jak dla oszczędzania baterii</string>
    <string name="advanced_options_type_custom_name">Modyfikowane</string>
    <string name="advanced_options_when_1_name">Po każdym uwtorze</string>
    <string name="advanced_options_when_5_name">Po pięciu utworach</string>
    <string name="advanced_options_when_10_name">Po dziesięciu utworach</string>
    <string name="advanced_options_when_25_name">Po 25 utworach</string>
    <string name="advanced_options_when_never_name">Gdy naciśniesz przycisk "scorbbluj teraz"</string>
    <string name="advanced_options_net_title">Sieć</string>
    <string name="advanced_options_net_summary">Udostępniaj informacje dla: %1</string>
    <string name="advanced_options_net_any_name">Jakakolwiek sieć</string>
    <string name="advanced_options_net_3gup_name">3G i Wifi</string>
    <string name="advanced_options_net_wifi_name">Tylko Wifi</string>
    <string name="advanced_options_net_roaming_title">Roaming</string>
    <string name="advanced_options_net_roaming_summary_off">Nie udostępniaj informacji, gdy jesteś w roamingu</string>
    <string name="advanced_options_net_roaming_summary_on">Udostępniaj informacje, gdy jesteś w roamingu</string>
    
    
    
    <string name="status">Status</string>
    <string name="scrobble_status_title">Status scrobbli</string>
    <string name="other_category_title">Inne</string>
    <string name="status_show_title">Status</string>
    <string name="status_show_summary">Pokaż statystyki i cały status</string>
    <string name="status_title">Informacje o statusie</string>
    <string name="scrobbling_disabled">Scrobblowanie jest wyłąćzone</string>
    <string name="scrobble_last_at">Ostatnio udostępnione informacje o scrobblach:</string>
    <string name="scrobble_last_fail_at">Ostatnio nieudane udostępnienie informacji o scrobblach:</string>
    <string name="nowplaying_disabled">Udostępnianie informacji o aktualnie słuchanym utworze są wyłączone</string>
    <string name="nowplaying_last_at">Ostatnio udostępniona informacja o aktualnie słuchanym utworze:</string>
    <string name="nowplaying_last_fail_at">Ostatnio nieudane udostępnienie informacji o scrobblach:</string>
    <string name="stats_scrobbles">Liczba wszystkich zascrobblowanych utworów:</string>
    <string name="never">Nigdy</string>
    <string name="stats_nps">Liczba wszystkich informacji o aktualnie granym utworze:</string>
    <string name="it_was">To było:</string>
    <string name="confirm_stats_reset">Jesteś pewien, że chcesz zresetować statystyki o udostępnianiu dla %1? Ta operacja nie będzie mogła zostać cofnięta.</string>
    <string name="profile_page">Strona profilu</string>
    
    
</resources>
