### ISSUE TITLE
I can't login anymore "connection error, retrying"

### ISSUE THREAD

**Issue by xzoldyck** [tgwizard/sls#268]
Many days ago the app stopped scrobbling, I uninstall, delete the cache and retrying many times, but I can't login anymore

**Comment by HumbleBeeBumbleBee** [comment]
Last.fm or libre.fm?

**Comment by xzoldyck** [comment]
Last.fm

**Comment by HumbleBeeBumbleBee** [comment]
Is your phone time correct?
Can you login from a browser (phone)?

**Comment by HumbleBeeBumbleBee** [comment]
You can also uninstall your current SLS and try this one.
https://drive.google.com/open?id=0B9lPaMaVVtiJNXdXNGcwUEUzUnM

**Comment by xzoldyck** [comment]
My time zone was wrong, now I can login and scrobbling as usual, thank you!
