### ISSUE TITLE
Crashes when a Shoutcast stream is played in Winamp

### ISSUE THREAD

**Issue by CoffeeAndKeyboard** [tgwizard/sls#27]
Copied bug from Google Code as requested [http://code.google.com/p/a-simple-lastfm-scrobbler/issues/detail?id=102]

What steps will reproduce the problem?
1. Install Winamp 1.1.1 and Simple Last.fm scrobbler
2. In Winamp - Play an audio file (say, .mp3) from the local system (SD card in this case)
3. Navigate to Shoutcast options in Wimamp and play a stream

What is the expected output? What do you see instead?

Simple Last.fm should be able to scrobble based on the stream information available (Winamp displays song playing in the stream). Otherwise, if this feature of reading a Shoutcast stream information is yet unimplemented, Simple last.fm scrobbler should silently ignore.

Message displayed on device: The application Simple Last.fm Scrobbler (process com.adam.aslfms has stopped unexpectedly. Please try again.)

=== Stack trace ===
java.lang.RuntimeException: Unable to start receiver com.adam.aslfms.receiver.
WinampMusicReceiver: android.os.BadParcelableException: ClassNotfoundException when unmarshalling: com.nullsoft.winamp.model.ShoutCastStation

  at ....
  ...
  at com.adam.aslfms.receiver.BuiltInMusicAppReceiver.parseIntent(BuiltInMusicAppReceiver.java:71)
  at com.adam.aslfms.receiver.AbstractPlayStatusReceiver.onReceive(AbstractPlayStatusReceiver.java:79)
  at android.app.ActivityThread.handleReceiver(ActivityThread.java:1994)

What version of the product are you using? On what operating system and
what device?

Device: HTC Desire HD

=== details on feedback ===
Device ace
Build Id GRI40
Model Desire HD
Product htc_ace
SDK version 10
Release 2.3.3
Incremental version 87995

Please provide any additional information below.

**Comment by HumbleBeeBumbleBee** [comment]
@CoffeeAndKeyboard 
Are you still using WinAmp for Android?
I can't find any reliable sources for the newest version of WinAmp...
We can't really support an application (.apk) we cannot find or trust.

**Comment by HumbleBeeBumbleBee** [comment]
WinAmp is deprecated, I think I'll be closing all of it's related issues until a reliable new version is released from nullsoft.
