### ISSUE TITLE
Issues with Poweramp?

### ISSUE THREAD

**Issue by McNippleson** [tgwizard/sls#270]
Seems to be working and not working randomly. Sometimes I'll launch SLS after a few hours of listening to music in PA and it will say that there are no tracks in the cache to submit. 

Not sure what info to add, both latest versions, Android 5.1.1

**Comment by HumbleBeeBumbleBee** [comment]
This is a known issue. PowerAmp broadcasts song information differently than other music players.
Often when it's closed or paused.
Did you check the TroubleShooting guide?

**Comment by HumbleBeeBumbleBee** [comment]
PowerAmp is now able to scrobble two ways. It scrobbles intents to the regular stock 'com.android.music.*' and 'com.adam.aslfms.notify.*'
This is probably for lyrics apps, but it's causing a broadcast clash in SLS.

**Comment by HumbleBeeBumbleBee** [comment]
A temporary fix may be disabling "Android Music Players" in enabled apps.

**Comment by HumbleBeeBumbleBee** [comment]
Please try disabling PowerAmp's scrobble setting to Simple Last.fm Scrobbler.

**Comment by McNippleson** [comment]
> Please try disabling PowerAmp's scrobble setting to Simple Last.fm Scrobbler.
This or A temporary fix may be disabling "Android Music Players" in enabled apps.
? 

Also I think it may be related to quitting PA with X in the notification drawer. I'll have to test it.

**Comment by HumbleBeeBumbleBee** [comment]
SLS has a bunch of receivers now. Using the stock broadcasts should be fine.

**Comment by HumbleBeeBumbleBee** [comment]
https://drive.google.com/file/d/0B9lPaMaVVtiJUkUyWVVTSjlUd2c/view?usp=sharing

This is a testable version of SLS. If you don't mind testing it, that would be great!!!

**Comment by HumbleBeeBumbleBee** [comment]
Here's a better version.
https://drive.google.com/file/d/0B9lPaMaVVtiJUVhsVTg2OGdHckk/view?usp=sharing

**Comment by HumbleBeeBumbleBee** [comment]
Not all of this functionality is working.

**Comment by HumbleBeeBumbleBee** [comment]
@McNippleson Is it working?

**Comment by McNippleson** [comment]
I haven't had the chance to test it properly sorry

**Comment by HumbleBeeBumbleBee** [comment]
#119
