### ISSUE TITLE
VLC 2.0.2

### ISSUE THREAD

**Issue by xsveeden** [tgwizard/sls#271]
Since the release of ver. 2.0.x of VLC, the scrobbler app has not been recognizing tracks, that is, it doesn't recognize music is being played. I can log out and re-login of last.fm (via scrobbler app) and it will work again for a short time. Usually, quitting VLC or restarting the phone will break it again. This is new to the latest version of VLC. It continues to work fine with the Rhapsody app.

Environment: Android 6.0 on an HTC One M8.

**Comment by HumbleBeeBumbleBee** [comment]
Yes,  I think they've decided only to support lyrics apps.

**Comment by HumbleBeeBumbleBee** [comment]
BuMP is a good player too.

**Comment by HumbleBeeBumbleBee** [comment]
I have contacted VLC and they seem to have bigger issues to deal with.

**Comment by HumbleBeeBumbleBee** [comment]
Hi! @xsveeden 
I have modified the source code of VLC to update metadata when the widget updates.
This should work for now.

**Comment by HumbleBeeBumbleBee** [comment]
It will install separately. So make sure you use the modified VLC.

https://drive.google.com/file/d/0B9lPaMaVVtiJckxtLTJCOGc5Z3c/view?usp=sharing

**Comment by HumbleBeeBumbleBee** [comment]
https://code.videolan.org/videolan/vlc-android/issues/100

**Comment by xsveeden** [comment]
Thanks for your continuing attention to this. Seems to be working now. On another note, there seems to be a lot of armchair quarterbacks "working" on the VLC project. I commend your patience with that.
