### ISSUE TITLE
Missing scrobbles with Unknown Album

### ISSUE THREAD

**Issue by SHADOW-XIII** [tgwizard/sls#272]
I noticed that tracks that Have artist tag saved as "Aaaa & Bbbbb" are not sending.
Despite that catlog shows "Scrobble success" but scrobble never appears in the track list on last.fm

I think it either sends incorrect data to last or last has issue when it's ampersand 
my desktop client sends it fine and question is why Last responds OK but I didn't get response body

From quick look I think it might be due to UrlEncodedFormEntity, see [http://stackoverflow.com/questions/4841331/url-encode-and-decode-special-character-in-java](url) 

Anyone can confirm having this issue and ideas to fix it?

**Comment by HumbleBeeBumbleBee** [comment]
Thank you for reporting this!

I never tested this before.

This can be repaired easily I think.

I'll keep you posted and give you a fresh .apk if it gets fixed.

**Comment by HumbleBeeBumbleBee** [comment]
You can try this .apk for now.
Please scrobble all your current scrobbles.
Uninstall your current Simple Last.fm Scrobbler.

This one has a lot of updates and is in beta testing. (it works, but it might have bugs).
Please notify me if anything goes wrong.

My track data is url encoded in the apk.
It should work.

https://drive.google.com/open?id=0B9lPaMaVVtiJMDNGb2JQMXhLT0E

**Comment by SHADOW-XIII** [comment]
Didn't show up on now playing, didn't show up on the page after scrobbling,
This is pretty much what I had in the logs:
```
07-14 15:14:39.808 18159 18287 D Scrobbler: http://post2.audioscrobbler.com:80/protocol_1.2
07-14 15:14:40.004 18159 18287 I Scrobbler: {s=<herewassessiontokenIguess>, a[0]=One Artist & Other Artist, b[0]=Unknown album, t[0]=Title A Title, i[0]=1468505419, o[0]=P, l[0]=260, n[0]=, m[0]=, r[0]=}
07-14 15:14:40.172 18159 18287 D Scrobbler: OK
07-14 15:14:40.173 18159 18287 I Scrobbler: Scrobble success: Last.fm
```

not sure how else I could use adb to help you though

**Comment by HumbleBeeBumbleBee** [comment]
Could you check your login status?

**Comment by HumbleBeeBumbleBee** [comment]
Please try this .apk

**Comment by HumbleBeeBumbleBee** [comment]
```
07-14 10:52:07.407 14434-15797/com.adam.aslfms I/Scrobbler: {s=543a861341aff4cd2fa6bb21c3f3d695, a[0]=Simon & Garfunkel, b[0]=s & g, t[0]=The Sound of Silence, i[0]=1468507629, o[0]=P, l[0]=297, n[0]=, m[0]=, r[0]=L}
07-14 10:52:07.457 14434-15411/com.adam.aslfms D/Scrobbler: OK
07-14 10:52:07.457 14434-15411/com.adam.aslfms I/Scrobbler: Scrobble success: Last.fm
```

**Comment by SHADOW-XIII** [comment]
ok, I think I figured it out .... if it's missing album name, it sends "Unknown album" and then it's not scrobbling (including Now Playing), if I set album name it works

**Comment by HumbleBeeBumbleBee** [comment]
What music app are you using if you don't mind?
Album name is optional.
That isn't supposed to happen.

**Comment by SHADOW-XIII** [comment]
Looks like Poweramp bug then

**Comment by HumbleBeeBumbleBee** [comment]
No. Definitely SLS.

**Comment by SHADOW-XIII** [comment]
I noteiced in logs:
`07-14 15:43:47.849  3836  3836 E SLSPlayStatusReceiver: Dumping Intent start
07-14 15:43:47.849  3836  3836 E SLSPlayStatusReceiver: [duration=260000]
07-14 15:43:47.849  3836  3836 E SLSPlayStatusReceiver: [com.maxmpz.audioplayer.source=com.maxmpz.audioplayer]
07-14 15:43:47.849  3836  3836 E SLSPlayStatusReceiver: [artist=Artist One & Artist Two]
07-14 15:43:47.849  3836  3836 E SLSPlayStatusReceiver: [playing=false]
07-14 15:43:47.849  3836  3836 E SLSPlayStatusReceiver: [id=6]
07-14 15:43:47.849  3836  3836 E SLSPlayStatusReceiver: [album=null]
07-14 15:43:47.849  3836  3836 E SLSPlayStatusReceiver: [track=There Was Title]
07-14 15:43:47.849  3836  3836 E SLSPlayStatusReceiver: Dumping Intent end
07-14 15:43:47.849  3836  3836 E SLSPlayStatusReceiver: Action received was: com.android.music.playstatechanged
07-14 15:43:47.849  3836  3836 D BuiltInMusicAppReceiver: Package: null : null
07-14 15:43:47.858  3836  3836 D BuiltInMusicAppReceiver: Will read data from intent
07-14 15:43:47.858  3836  3836 E BuiltInMusicAppReceiver: Long: 260 int: 260
07-14 15:43:47.859  3856  3856 I Exchange: EasService.onCreate
07-14 15:43:47.860  3836  3836 D ScrobblingService: State: PAUSE
07-14 15:43:47.861  3836  3836 E SLSPlayStatusReceiver: Dumping Intent start
07-14 15:43:47.861  3836  3836 E SLSPlayStatusReceiver: [duration=260]
07-14 15:43:47.861  3836  3836 E SLSPlayStatusReceiver: [artist=Artist One & Artist Two]
07-14 15:43:47.861  3836  3836 E SLSPlayStatusReceiver: [album=Unknown album]
07-14 15:43:47.861  3836  3836 E SLSPlayStatusReceiver: [state=0]
07-14 15:43:47.861  3836  3836 E SLSPlayStatusReceiver: [track=There Was Title]
07-14 15:43:47.861  3836  3836 E SLSPlayStatusReceiver: [app-package=com.maxmpz.audioplayer]
07-14 15:43:47.861  3836  3836 E SLSPlayStatusReceiver: [app-name=Poweramp]
07-14 15:43:47.861  3836  3836 E SLSPlayStatusReceiver: Dumping Intent end
07-14 15:43:47.861  3836  3836 E SLSPlayStatusReceiver: Action received was: com.adam.aslfms.notify.playstatechanged`

**Comment by HumbleBeeBumbleBee** [comment]
https://drive.google.com/open?id=0B9lPaMaVVtiJVHpPazVrTEdsWlU

Try this one.

**Comment by HumbleBeeBumbleBee** [comment]
https://drive.google.com/open?id=0B9lPaMaVVtiJM0JFOHJDbGZBbkU

This should cover all the bases. 'Unknown album' will be scrobbled in the case of null or "" (empty string).

**Comment by HumbleBeeBumbleBee** [comment]
https://drive.google.com/open?id=0B9lPaMaVVtiJM0JFOHJDbGZBbkU

**Comment by HumbleBeeBumbleBee** [comment]
https://drive.google.com/file/d/0B9lPaMaVVtiJdG5NTXpkMlFMY00/view?usp=sharing

**Comment by HumbleBeeBumbleBee** [comment]
It seems to be working now.

**Comment by HumbleBeeBumbleBee** [comment]
This is frustrating.

**Comment by HumbleBeeBumbleBee** [comment]
PowerAmp seems to be the only app on my test device that doesn't user the folder name for Unkown album.
Unknown album must trip something at Last.fm
https://drive.google.com/open?id=0B9lPaMaVVtiJQXhTWlRTQW5KbTQ

**Comment by HumbleBeeBumbleBee** [comment]
What do you think of the new features btw?

**Comment by SHADOW-XIII** [comment]
will test it later tonigh and let you know

**Comment by HumbleBeeBumbleBee** [comment]
https://drive.google.com/open?id=0B9lPaMaVVtiJTWFnaUNteVJudzQ
Updated.

**Comment by SHADOW-XIII** [comment]
Can confirm it's working now with empty album
Many thanks!
