### ISSUE TITLE
Suggestion: Notify if not scrobbling or account disconnected

### ISSUE THREAD

**Issue by thenickchapman** [tgwizard/sls#273]
My account was disconnected last August and I haven't been scrobbling since then from my phone.  Re-authenticating seems to have corrected the issue.

That said, only one item was "enqueued" for scrobble.  I've played, probably, thousands since then.  I guess I have two suggestions/requests:
(1) A notification of some type if not SLS is not authenticated to some a last.fm or libre.fm account for x amount of time (maybe configurable per scrobble destination or only notifies if authentication has ever been actually established).
(2) Played items be cached for (hopefully, later) scrobble whether authenticated or not so that, in the event of authentication failure, played track information isn't lost.

That said, love SLS and appreciate all the hard work that goes into it.  I'll continue to happily use it as is, but wanted to share my thoughts.

**Comment by HumbleBeeBumbleBee** [comment]
Hello! There is nothing worse than lost scrobbles.
I am rewriting the networking right now.
I have added the feature that lets the user know when they're not logged in to libre.fm or last.fm

Do you use libre.fm also?

**Comment by thenickchapman** [comment]
Agreed!  I can't explain why it pains me so, but looking at my statistics and seeing how little I've scrobbled this year hurts my heart a little.

Wow, sounds awesome! Yes, I scrobble to both last.fm and libre.fm.  I don't really reference my libre.fm stuff as often since there is less historical data due to me starting to use it much later.  I just like the idea of not having my data owned by last.fm in case they ever become jerks (or get bought out by jerks) and prevent me from accessing it.

Thanks for the quick response and hard work!!!

**Comment by HumbleBeeBumbleBee** [comment]
Was your username in last.fm blank? or you simply had "wrong username/password"?
Do you remember the error response?

That's part of it... when you're logged into one or the other or both, SLS won't complain.

It should have complained about bad authentication though.

**Comment by HumbleBeeBumbleBee** [comment]
Here's the new list of supported apps for you...

		Spotify, Google Music, Deezer, Rhapsody, Rdio, My Cloud Player, SoundCloud, 8tracks,
		InfiniTracks, Squeezer, Amazon Music, Huawei, n7player, BuMP, PowerAMP, Black Player, AIMP,  
		Timber (Beta), Vanilla Music, SmartVanilla Music, Shuttle Music Player, Rocket Player,
		JRTStudio Android Music Player, PlayerPro, Jetaudio, jukefox, foobar2000, DeaDBeeF,
		GoneMAD Music Player, Folder Player, Neutron Music Player, Music Pump XBMC Remote (Beta),
		Music Folder Player, Meridian Player, MixZing, Archos Music Player, Radio Noise FM,
		Now Playing, SoundSeeder, MortPlayer, bTunes, WIMP, Just Playlists, RockOn, Apollo,
		Android Music Player, HTC Hero/Sense Music Player, MIUI Music Player, ServeStream,
		Default Sony Ericsson/Xperia Music Player, myTouch 4G, LG Music Player,
		DAAP Media Player, xenoAmp, Marine, MediaMonkey,

**Comment by thenickchapman** [comment]
"wrong username/password" sounds correct...and I don't recall seeing an error response.  Where would that have been?  I don't think libre.fm was logged in.  There was no error or "wrong username/password," though.  Honestly, I'm not certain I was logged into it from the start, though.

By "should have complained," do you mean a notification?  I can't guarantee that didn't happen last October or whenever my last scrobble was, just that I don't recall seeing it.  If it would have occurred at that point and I dismissed it out of haste, sorry for starting this thread and complaining!

Thanks for the list, too!  That's impressive support!

**Comment by HumbleBeeBumbleBee** [comment]
Do you want to try the newest version?
It might be buggy, so scrobbling may not work 100%

**Comment by HumbleBeeBumbleBee** [comment]
[app-debug.zip](https://github.com/tgwizard/sls/files/367280/app-debug.zip)

**Comment by HumbleBeeBumbleBee** [comment]
![screenshot_2016-07-16-19-48-30](https://cloud.githubusercontent.com/assets/8563086/16897879/97dfe702-4b8e-11e6-8072-832e23362b8f.png)

**Comment by HumbleBeeBumbleBee** [comment]
[app-debug.zip](https://github.com/tgwizard/sls/files/367866/app-debug.zip)

Ok!

**Comment by thenickchapman** [comment]
Thanks!  I'll try it now and poke around.  Again, I appreciate the support and am really impressed with your attention to this.  I'll have to look around for the donate option too.

**Comment by thenickchapman** [comment]
Huh, it wouldn't let me install over the existing version (and keep settings),  Said something about "same signature"...so I'll try uninstalling and then installing the new one.

**Comment by HumbleBeeBumbleBee** [comment]
Yeah. Sorry I forgot to mention that... Scrobble your scrobble uninstall and reinstall.
Different key... same install path. WaBam! Conflict.

**Comment by thenickchapman** [comment]
Install worked after uninstall.  Here's what I'm seeing:

I was shown a "Credentials REQUIRED to work properly" popup notice briefly at the bottom of the screen after install/open when the "what's new" text is displayed.  Nice!

Looking through the settings, the popup is displayed again when I enter the any section of the settings or when I leave the app (after making no changes to the settings).

Google Play Music isn't showing as an available option under 'Enabled Apps'...but still seems to scrobble correctly.  I guess I'll try to change my password to "break authentication" and see what happens.

OK..I reset my password at last.fm.  It is still scrobbling, now...so I guess I have to wait until my authentication token expires or something like that?  I'm not sure how long that takes, but I'll keep playing music periodically and see what happens.  Let me know if I should just use the 'clear credentials' option instead, although I don't know if that would mirror a real-life authentication failure issue as accurately.

Thanks!

**Comment by HumbleBeeBumbleBee** [comment]
I can purposely break networking here.
No problem, and thank you for you!

**Comment by thenickchapman** [comment]
When my authentication token(?) expired, I got the message below:

![image](https://cloud.githubusercontent.com/assets/2610305/16960734/af5c1f82-4db8-11e6-8fbd-efd2787bf643.png)

 When my phone restarted, however, the message didn't come back (even after I listened to some music).  I wasn't sure if the app would complain more if I wasn't signed into libre.fm.  I'll try that next, disassociate with libre.fm and see if I get prompted to re-authenticate or anything.

Probably, since it told me once, it felt that was enough and I could fix it myself if I wanted.

Lastly, my scrobbles aren't being stored (for upload on re-authentication, presumably).  This, also, may be due to my existing login to libre.fm.  I'll test and see.

If you understand my (minor) issues and aren't interested in adding more, complex, functionality to the app, I entirely understand...but I wanted to document it in case you do want to spend tons of thankless hours.  :)

**Comment by HumbleBeeBumbleBee** [comment]
Thank you! No issue is minor. If something goes wrong or you don't like it, let me know.

[app-debug.zip](https://github.com/tgwizard/sls/files/372166/app-debug.zip)

**Comment by thenickchapman** [comment]
I'll install the new one today!  Disconnecting from libre.fm didn't seem to cause another error/notice and my scrobbles aren't being stored (with no current working credentials).

I'll try the new version and see if there is any difference.  Thanks, again, for the continued support!
