### ISSUE TITLE
detection for foobar in enabled apps

### ISSUE THREAD

**Issue by rapchee** [tgwizard/sls#274]
the mobile version of the classic windows music player
https://play.google.com/store/apps/details?id=com.foobar2000.foobar2000
http://mobile.foobar2000.com

**Comment by HumbleBeeBumbleBee** [comment]
It already supports it I believe?

**Comment by rapchee** [comment]
sorry, new to github, i just found the closed issues, and saw the previous foobar request, where i could see that foobar is detected as the default player (which i have previously disabled, it caused complications) - would it perhaps be possible to get it detected as foobar? for me it's fine now, just to avoid further confusion

**Comment by HumbleBeeBumbleBee** [comment]
The app is used under "Android Music Player(s)"

**Comment by rapchee** [comment]
on my xperia m it shows as "Sony Ericsson Music Player"

**Comment by HumbleBeeBumbleBee** [comment]
You can try this newer version if you like... [app-debug.zip](https://github.com/tgwizard/sls/files/367289/app-debug.zip)

Warning it may have bugs.

foobar needs to add "package"="com.foobar2000.foobar2000" in the broadcast for this to work.

I don't have a Sony phone but I will try to get it on my phone and test it.

**Comment by rapchee** [comment]
using the debug version, it does indeed appear as "android music player", although it also says the app is not installed. still, scrobbling works.

**Comment by HumbleBeeBumbleBee** [comment]
Few people use the original Android Music Player. SLS detects if the package is installed.
