### ISSUE TITLE
View Scrobble Cache button doesn't work

### ISSUE THREAD

**Issue by bajituka** [tgwizard/sls#275]
1) Go to status
2) Click "More" menu icon
3) Click "View scrobble cache"

Nothing happens

**Comment by HumbleBeeBumbleBee** [comment]
Could you test this .apk to see if View scrobble cache works.

[app-debug.zip](https://github.com/tgwizard/sls/files/376210/app-debug.zip)

**Comment by HumbleBeeBumbleBee** [comment]
@bajituka What version of SLS? What version of Android?

**Comment by bajituka** [comment]
The latest version works fine. I'll close it.
