### ISSUE TITLE
Pre-release

### ISSUE THREAD

**Issue by HumbleBeeBumbleBee** [tgwizard/sls#278]
#Anyone who wants to test / debug the newest version, please download and install this signed apk.

Please report everything you're unhappy about and obvious bugs.
If you know how to use 'adb', you could use debug logs in your comments.

8/22/2016
[app-debug.zip](https://github.com/tgwizard/sls/files/430454/app-debug.zip)

**Comment by inverse** [comment]
Signed with different key?

**Comment by HumbleBeeBumbleBee** [comment]
I will fix that before the official release.

**Comment by HumbleBeeBumbleBee** [comment]
I tried to recreate that but it did not work. Installed easily on my phones.
What did the installer say when it didn't install?

**Comment by inverse** [comment]
It gave no errors, but just that it could not install.

Perhaps I wasn't running the official play store release and my own build then :/

**Comment by RonteCZ** [comment]
I installed this version to check on Czech translation and everything is correct. Please put my name in the changelog. Thanks!

**Comment by HumbleBeeBumbleBee** [comment]
@RonteCZ Already done. I just haven't posted it yet. There are some more bug fixes needed.

```
  * Add Love track feature
  * Network notifications
  * Last.fm API 2.0
  * Add Czech (thanks to Michal Absolin)
```

**Comment by RonteCZ** [comment]
@HumbleBeeBumbleBee  Ok, thanks!

**Comment by bajituka** [comment]
Did you include the RU translation in this release? My phone's locale is RU but everything is in English.

**Comment by HumbleBeeBumbleBee** [comment]
I add RU to the official branch. This branch is mine. They will merge.

**Comment by bajituka** [comment]
Okay.
I noticed an issue with credentials, don't know how to reproduce it though. First I indicated wrong credentials, then I indicated correct credentials. In some hours I received a notification about wrong credentials, however I've logged in successfuly back then.

**Comment by HumbleBeeBumbleBee** [comment]
@bajituka Still working on it...

**Comment by HumbleBeeBumbleBee** [comment]
@bajituka Could you please translate this last group of strings to Russian?
```xml
<!-- START heart strings -->
<string name="heart_and_copy">Song Options</string>
<string name="heart_title">Love</string>
<string name="heart_current_track">Love Current Track at last.fm</string>
<string name="no_heart_track">Heart Track Failed</string>
<string name="loved_track">Loved Track</string>
<string name="no_lastFm">Please enter your last.fm credentials</string>
<!-- END heart strings -->

<!-- START copy strings -->
<string name="copy_title">Copy</string>
<string name="copy_current_track">Copy Current Track to Clip Board</string>
<string name="no_copy_track">Copy Track Failed</string>
<string name="no_current_track">No Current Song Available</string>
<!-- END copy strings -->

<!-- START permissions and warnings strings -->
<string name="permission_required">Permission REQUIRED to work properly</string>
<string name="creds_required">Credentials REQUIRED to work properly</string>
<!-- END permissions and warnings strings -->
```

**Comment by bajituka** [comment]
@HumbleBeeBumbleBee will do within 24 hours, I'm not at the PC I need to be at currently

**Comment by bajituka** [comment]
@HumbleBeeBumbleBee I've made a pull request

**Comment by UksusoFF** [comment]
Thank, now it's scrobbled #248.
Waiting release to Play Market and F-Droid :)
BTW. I can help with Russian translate if still need.

**Comment by HumbleBeeBumbleBee** [comment]
@UksusoFF 
What is "Limited Network" in Russian?

**Comment by UksusoFF** [comment]
@HumbleBeeBumbleBee 
Probably "Ограниченная сеть". Where in app can see this?

**Comment by HumbleBeeBumbleBee** [comment]
Thanks. This is a pre release. There will be an official release as soon as everything works.

**Comment by HumbleBeeBumbleBee** [comment]
I am going to be doing the release soon. If anybody has any questions or problems please download the newest version in the first comment and tell me if the problem persists.

**Comment by HumbleBeeBumbleBee** [comment]
Anybody have anything to say about the newest release? I am going to post it today.

**Comment by UksusoFF** [comment]
Look forward! :)

**Comment by inverse** [comment]
I've not noticed any issues so far

**Comment by UksusoFF** [comment]
Today get some crashes after enable WiFi and sync cached tracks.
[2016-09-05-21-10-49.zip](https://github.com/tgwizard/sls/files/455422/2016-09-05-21-10-49.zip)

**Comment by HumbleBeeBumbleBee** [comment]
Did it recover?

**Comment by UksusoFF** [comment]
Few times. Now got this error always when off/on WiFi.

**Comment by HumbleBeeBumbleBee** [comment]
@UksusoFF Have you tried the full release version?

**Comment by HumbleBeeBumbleBee** [comment]
Please comment here #287
