### ISSUE TITLE
Stops to scrobble on MIUI

### ISSUE THREAD

**Issue by RonettePulaski** [tgwizard/sls#281]
I have some problems of scrobbling on MIUI (Xiaomi Redmi 3) and PowerAMP player. Sometimes SLS stops to scrobble and resumes only after manual enabling player in settings. I heard that it is a specificial MIUI bug, associated with power management. Maybe it possible to make baypass to this?
I lost about thousand tracks in scrobbled chart because of this issue.

**Comment by HumbleBeeBumbleBee** [comment]
What version of Android are you running please?

**Comment by RonettePulaski** [comment]
Android 5.1.1 LMY47V
Linux 3.10.49-perf-g48b885e
MIUI 7.1.3.0

**Comment by HumbleBeeBumbleBee** [comment]
Try #278

**Comment by RonettePulaski** [comment]
Button "Love" gives no result and visual reaction.Regards to my problem, I turned off memory optimization in developer settings, will look, how it can help. 30.07.2016, 21:34, "HumbleBeeBumbleBee" <notifications@github.com>:Try #278—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by HumbleBeeBumbleBee** [comment]
Does Miki work?

**Comment by RonettePulaski** [comment]
It seems yes.

**Comment by HumbleBeeBumbleBee** [comment]
[app-debug.zip](https://github.com/tgwizard/sls/files/396924/app-debug.zip)

Please try this apk.
