### ISSUE TITLE
Huge data usage

### ISSUE THREAD

**Issue by arrufat** [tgwizard/sls#286]
I can't see how data usage can be this high after 3 days of moderate use: 
![screenshot_20160819-081955](https://cloud.githubusercontent.com/assets/1671644/17800773/314eadd0-65e6-11e6-9234-428d26f35fd2.png)

**Comment by HumbleBeeBumbleBee** [comment]
What version of SLS? 1.4.9?

**Comment by HumbleBeeBumbleBee** [comment]
How many songs in the cache?

**Comment by arrufat** [comment]
Yes, version 1.4.9.
The thing is that the phone was plugged to an external battery, so it was sending the now playing notifications.
However, in the settings I marked not to scrobble while roaming.

**Comment by HumbleBeeBumbleBee** [comment]
Are you last.fm or libre.fm or both?

**Comment by arrufat** [comment]
I'm using both services

**Comment by HumbleBeeBumbleBee** [comment]
Roughly how many songs and is data enabled for how long?

**Comment by arrufat** [comment]
Hard to tell, I would say three days and around 100 songs...

**Comment by HumbleBeeBumbleBee** [comment]
Would you mind testing a newer .apk ? It is signed. If the install does not work it's because the apk I send you is not official.

**Comment by arrufat** [comment]
Of course :)

**Comment by HumbleBeeBumbleBee** [comment]
@arrufat Also have you enabled, SLS > Options > Network > WiFi Only ?

**Comment by HumbleBeeBumbleBee** [comment]
#278 Do you know how to work with .zip files? Unpack the .zip and run the .apk .

**Comment by HumbleBeeBumbleBee** [comment]
Looking at my data I would say maybe I have the same problem.

**Comment by HumbleBeeBumbleBee** [comment]
Can I ask what type of phone or what type of battery optimization you have?

**Comment by arrufat** [comment]
I enabled the WiFi only after I saw this problem (too late)
I've updated the app, I'll keep you posted on #278 if I find any issue.
Thanks for the quick responses :)

**Comment by arrufat** [comment]
I have a OnePlus One and I was using "Conserve Battery" on battery and "Standard" when plugged in

**Comment by HumbleBeeBumbleBee** [comment]
Does your phone have a power saving mode?

**Comment by arrufat** [comment]
I guess so... It is using android 6.0.1 (Cyanogenmod) so it must have the doze mode.

**Comment by HumbleBeeBumbleBee** [comment]
Are you using WiFi only on the new app?
Can ask what music app(s) besides Phonograph that you are using?
I can test here no problem.

**Comment by arrufat** [comment]
I haven't tried the new app yet. Do you recommend enabling scrobbling on data again?
I'm using Phonograph and Poweramp.

**Comment by HumbleBeeBumbleBee** [comment]
Let me check first.

**Comment by HumbleBeeBumbleBee** [comment]
If you do decide to use it please record your starting KB used and you're updated KB so the difference can be assessed.

Were scrobbles getting stuck in the cache sometimes?

**Comment by arrufat** [comment]
Ok.
Yes, I recall having to manually press the scrobble button to force the scrobbling and empty the cache.

**Comment by HumbleBeeBumbleBee** [comment]
@arrufat Was the scrobble button not working sometimes?

If False, it may have been the older versions way of dealing with the new devices.

If True
This is probably the problem. It must be trying to send all that data across the network and it's being rejected somehow.

**Comment by arrufat** [comment]
Yes, I remember the button not working at some point, but I thought it was a network problem.

**Comment by HumbleBeeBumbleBee** [comment]
Here are the [numbers](https://github.com/HumbleBeeBumbleBee/SLSmanager/blob/master/NetWork_Usage/stats.txt) to the best of WireShark's knowledge.

Ok. I think you can try it when you get the chance.
I am going to scrobble a bunch of my music to test it more.

**Comment by inverse** [comment]
That data usage seems insane. Could it be that it got stuck and kept trying to retry even though requests were failing? hmm

**Comment by HumbleBeeBumbleBee** [comment]
My next commit contains a fix.

**Comment by arrufat** [comment]
Thank you! I can't wait to try the next version

**Comment by HumbleBeeBumbleBee** [comment]
https://play.google.com/apps/testing/com.adam.aslfms
