### ISSUE TITLE
Release v1.5.0

### ISSUE THREAD

**Issue by HumbleBeeBumbleBee** [tgwizard/sls#287]
https://github.com/tgwizard/sls/releases/tag/v1.5.0

Please test it.

**Comment by Luckz** [comment]
When is this going to be on Google Play? Are you using the beta feature?

**Comment by HumbleBeeBumbleBee** [comment]
@Lucky
I have yet to take a good look at the beta feature.
I will try and use it.

**Comment by lucky** [comment]
@HumbleBeeBumbleBee i think you meant to mention @Luckz

**Comment by ALERTua** [comment]
I would very appreciate it if you add a widget for marking currently playing song as loved. if you want me to create an issue with this feature request — please let me know.

**Comment by HumbleBeeBumbleBee** [comment]
@Luckz 
The Beta Version should go live soon.

**Comment by HumbleBeeBumbleBee** [comment]
@ALERTua I will try to add this feature soon.

**Comment by HumbleBeeBumbleBee** [comment]
The app has been released on Google Play

**Comment by ALERTua** [comment]
joining, downloading, testing. thank you!
