### ISSUE TITLE
New notification system permanent or quickly displays and closes.

### ISSUE THREAD

**Issue by jck** [tgwizard/sls#288]
I'm using SLS v 1.5.0 with google play music. When i pause music and swipe away GPM's notification, SLS's notification still persists. Even clearing the queue in GPM doesn't help.

**Comment by HumbleBeeBumbleBee** [comment]
You can hide sls notifications in thearly options menu
 although it's built to capture all Scrobbles even with new devices power saving mode and swipe to close SLS shutting down the scrobbling service.

It's a persistent notification or lost Scrobbles.
I went with persistent notification.
I am working on a fix.

**Comment by HumbleBeeBumbleBee** [comment]
https://github.com/tgwizard/sls/blob/master/app/src/main/assets/changelog.txt#L6

**Comment by jck** [comment]
Thanks! I should mention that I've been using 1.4.9 on Android N since DP3
without any issues.

**Comment by HumbleBeeBumbleBee** [comment]
What model of phone?

**Comment by jck** [comment]
Nexus 5x

**Comment by HumbleBeeBumbleBee** [comment]
Did it work in power saving mode?

**Comment by jck** [comment]
I never tried while the phone was in "Battery saver" mode. However, I
didn't override the default battery optimization for this app.

**Comment by HumbleBeeBumbleBee** [comment]
Well, this annoys me too, however people complain more about missed scrobbles.
I am looking into a fix that will allow the notification to be swiped away when the music is no longer active.
[app-debug.zip](https://github.com/tgwizard/sls/files/447570/app-debug.zip)

Here's the apk I have been working on. If you could help test it that would be great.
It should allow you to swipe away the notification when music is not playing.

**Comment by adduxa** [comment]
Same annoying problem with 1.5.0 and Poweramp  2.0.10.
SLS's Power saving mode doesn't help, solution is unchecked Device Notifications checkbox in Custom options, but even then notification pops up and immediately disappears when scrobbling starts

**Comment by HumbleBeeBumbleBee** [comment]
Yes this is true. I am trying to find a way to make sure all Scrobbles are captured and the interface stays simple and swipe notification.

**Comment by HumbleBeeBumbleBee** [comment]
https://play.google.com/apps/testing/com.adam.aslfms

**Comment by dedioste** [comment]
Seems fixed on Nexus 5x running Android Nougat NRD90R  (last release).

**Comment by HumbleBeeBumbleBee** [comment]
If you have plroblems scrobbling you can enable ongoing to make sure all scrobbles are captured.
It's still there but you can disable it.
