### ISSUE TITLE
Showing notifications, when this shouldn't happen

### ISSUE THREAD

**Issue by BasDV** [tgwizard/sls#296]
Hi!

Love the app. But, since the last update I've set no notifications as options. But what happens is that the app shows a notifications for 0.2 second. Realizes it shouldn't be displaying it and then removing it again. 
It does this a few times. Resulting in a second per song of flashing notification icon. Can this be fixed?

I'm on a OnePlus One, Android 6

**Comment by HumbleBeeBumbleBee** [comment]
#288

**Comment by HumbleBeeBumbleBee** [comment]
https://play.google.com/apps/testing/com.adam.aslfms
