### ISSUE TITLE
Spotify not detected 

### ISSUE THREAD

**Issue by bshillingford** [tgwizard/sls#297]
In current sls version v1.5.0, on Android 6.0.1 (Cyanogenmod) on Oneplus One, Spotify is not being detected and/or shown in the enabled app list.

**Comment by HumbleBeeBumbleBee** [comment]
Is it scrobbling?

**Comment by bshillingford** [comment]
Stupid me. I had "device broadcast status" off in the Spotify app, I'll see if it works now then close the ticket.

edit: Yup, works fine now. 
Thanks!

**Comment by bshillingford** [comment]
Stupid me. I had "device broadcast status" off in the Spotify app, I'll see
if it works now then close the ticket.
