### ISSUE TITLE
Apollo support

### ISSUE THREAD

**Issue by pseiler** [tgwizard/sls#3]
I wan't to have support for the android 4 apollo music player. I think that doesn't take much time to include.
I would do this by myself but I haven't any android/java programming skills to do that.
But I can be a tester (I'm using a desire z with an andromadus rom)
At the moment I cannot find the sourcecode of apollo

Best regards and thank you for this awesome program

**Comment by HumbleBeeBumbleBee** [comment]
It's probably because the app is being recognized as a stock or builtin android player.
SLS could have added detection for Apollo but as long as it scrobbles, I think we can close this issue.
