### ISSUE TITLE
Notification blinks when changing song (in Spotify), Polish translation has issues

### ISSUE THREAD

**Issue by dupld** [tgwizard/sls#300]
When I change songs in Spotify, the notification from SLS blinks usually twice and then disappears. All notifications are disabled in settings.

Also, Polish translation has issues. Many sentences are badly translated (like from translator). I can help you with translation if you want.

**Comment by HumbleBeeBumbleBee** [comment]
#288 

#292 

Use the following file to translate.

https://github.com/tgwizard/sls/blob/master/app/src/main/res/values-pl/strings.xml

Get the translations to me in any form and I will update them.

**Comment by HumbleBeeBumbleBee** [comment]
https://play.google.com/apps/testing/com.adam.aslfms
