### ISSUE TITLE
Notification permanently displayed 

### ISSUE THREAD

**Issue by seanfilidis** [tgwizard/sls#302]
For a couple weeks this app shows a notification that cannot be swiped away. It just says the title of the last song I played. Clicking on it poems the app, but there is nothing to resolve. There is nothing in the cache. Only way to remove the notification is to restart my phone.

**Comment by seanfilidis** [comment]
Opens, not poems.

**Comment by Row** [comment]
I have the same problem. Samsung s6 with android 6.0.1, DSub https://github.com/daneren2005/Subsonic

**Comment by HumbleBeeBumbleBee** [comment]
#288

**Comment by HumbleBeeBumbleBee** [comment]
https://play.google.com/apps/testing/com.adam.aslfms
