### ISSUE TITLE
Wrong tracks are scrobbled.

### ISSUE THREAD

**Issue by rascal-pl** [tgwizard/sls#305]
Here is a problem:
![Imgur](http://i.imgur.com/qaqjxoC.png)
And it's not only an error in notification. Those tracks are scrobbled to last.fm.
I tried another app called srobb, but it doesn't support caching, so when I'm offline, my tracks are simply not saved for later submit to last.fm, so I would prefer to use simple last fm scrobbler.
PS - I tried many different options in poweramp and this app, scrobbled tracks are always wrong.

**Comment by HumbleBeeBumbleBee** [comment]
So you have tried other music players?

**Comment by HumbleBeeBumbleBee** [comment]
Please message me if this problem reoccurs I will be calling this issue. This issue thread has ceased.
