### ISSUE TITLE
Credentials cleared by 1.5 update with no notification

### ISSUE THREAD

**Issue by robertc** [tgwizard/sls#308]
I just got home after spending five days driving about listening to music in the car to discover that none of those tracks have been scrobbled.  When I investigated in the app all my credentials had been cleared, there was no notification that this had happened, just the useless un-deletable notifications about what song had last played.

**Comment by HumbleBeeBumbleBee** [comment]
Firstly sorry for the lost scrobbles.
Secondly the app should no be clearing all your credentials.
Are you sure you are not running version 1.5.1?

**Comment by HumbleBeeBumbleBee** [comment]
Can you still login?

**Comment by robertc** [comment]
> This required relogin

Then the app should have an obvious notification that this has happened.  Also songs should go into the scrobble cache like they did before when there was a problem.
