### ISSUE TITLE
Doesn`t work scrobbling

### ISSUE THREAD

**Issue by elluvium** [tgwizard/sls#310]
Doesn`t work scrobbling to Lastfm after last update on nexus5 hammerhead. Just nothing happens while playing music. I'm not a Java developer but I will try to debug it.

**Comment by HumbleBeeBumbleBee** [comment]
I assume you tried religion and reinstall and clear cache?

**Comment by HumbleBeeBumbleBee** [comment]
Also what music app are you using?

**Comment by elluvium** [comment]
Of course I have tried! There was a problem with login like in issue #307. And actually in v.1.5.1 it's ok. 
Poweramp (beta)

**Comment by HumbleBeeBumbleBee** [comment]
Could you test another music player to see if it's a poweramp problem?

**Comment by HumbleBeeBumbleBee** [comment]
Have you tried Google Play Music?

**Comment by elluvium** [comment]
It seems that is really the problem with poweramp. Shuttle+ works perfectly

**Comment by HumbleBeeBumbleBee** [comment]
Happy scrobbling!
