### ISSUE TITLE
Scrobbles only about 2/3 of songs casting to Chromecast via GPM

### ISSUE THREAD

**Issue by davidqvist** [tgwizard/sls#313]
SLS only scrobbles about 2/3 of the songs, when I cast to Chromecast using Google Play Music. I'm not sure the issue occurs all the time, but I haven't been able to pinpoint exactly what is causing it.

Additional info:
- My device is a Samsung Galaxy S6 running 6.0.1 build G920FXXU4DPIH
- I've disabled Samsung's own battery optimizer functionality and also made sure that Greenify isn't killing SLS.
  I can't figure out what exactly changes when I tick and untick things in the notification settings, but I have all of them ticked
- Also, Google Play Music is scrobbling as "Android Music Player"

Tell me if you need additional information or if there's anything else I can do to help.

**Comment by HumbleBeeBumbleBee** [comment]
Hello great work on posting this here on the GitHub.

**Comment by HumbleBeeBumbleBee** [comment]
I will try to recreatexplain the problem. If I cannot you may want to try a debuggable version of SLS which I can provide for you.

**Comment by HumbleBeeBumbleBee** [comment]
You can also try this app in case closing SLS is the reason you're losing scrobbles.
https://play.google.com/store/apps/details?id=dan.wilkie.last.charts

**Comment by HumbleBeeBumbleBee** [comment]
I haven't been able to recreate the problem.
Have you tried enabling "OnGoing" in options?
