### ISSUE TITLE
Erratic notification issue

### ISSUE THREAD

**Issue by davidteal** [tgwizard/sls#317]
Hi guys.

When Phone Notifications are disabled, it seems like the app is trying to push a notification but then disappearing straight away.  This make the notifications jump up and down erratically which is quite annoying.

Using SLS 1.5.1
Android 7.0
Nexus 6P

Let me know if you need any more info.

Cheers.

**Comment by HumbleBeeBumbleBee** [comment]
You must disable "OnGoing" or enable "Phone Notifications".
If you disable OnGoing, everytime you open and close the app a scrobble will be lost. The official app is dealing with the same problem. Ongoing notification vs losing scrobbles.

**Comment by HumbleBeeBumbleBee** [comment]
There maybe be another small patch available but it may break long pauses.

**Comment by HumbleBeeBumbleBee** [comment]
The best solution for now would be disabling Power Saving for Simple Last.fm Scrobbler and all your music apps. I am not sure there is a proper work around for the notifications.
