### ISSUE TITLE
Add" love track" to libre.fm

### ISSUE THREAD

**Issue by MartinL0815** [tgwizard/sls#318]
Since LibreFM supports loving tracks too, it would be nice to add this to sls!

**Comment by HumbleBeeBumbleBee** [comment]
What version of Android are you using? The live track feature should work for both.

**Comment by MartinL0815** [comment]
Hi, 

The live feature works, but using the "love" function fails, because I'm not logged into last.FM. 

But now to your question - the Android version is 5.0.2.

Martin Lemburg 

Berlin / Deutschland

martin.lemburg@gmx.net
http://about.me/Martin0815

-----Original Message-----

**Comment by HumbleBeeBumbleBee** [comment]
You are correct.

**Comment by HumbleBeeBumbleBee** [comment]
The next version should fix this issue.
