### ISSUE TITLE
google music doesnt show up in apps list on marshmellow

### ISSUE THREAD

**Issue by DwordPtr** [tgwizard/sls#319]
I've installed logged into lastfm and rebooted.
I'm on an axon 7.

**Comment by HumbleBeeBumbleBee** [comment]
It shows up as "Android Music Player" Apps

**Comment by DwordPtr** [comment]
@HumbleBeeBumbleBee No apps show up besides spotify. This is while I'm playing music on the google music app.

**Comment by earfolds** [comment]
When listening with Google Play Music, "Android Music Player" appears in the list, but is listed as uninstalled. No music is detected, and no scrobbles are cached. (Android 7.1)

**Comment by HumbleBeeBumbleBee** [comment]
@earfolds Have you tried disabling power saving for Simple Last.fm Scrobbler and GPM ?
