### ISSUE TITLE
custom SLS apks for custom GNU-fm server

### ISSUE THREAD

**Issue by bilde2910** [tgwizard/sls#320]
I am running SLS v1.5.1 on Android 6.0.1/OxygenOS 3.2.7 on a OnePlus 3. When I try to add my Gnu FM credentials to SLS, the apps gets stuck at the "Authenticating" stage. Packet capture from server shows that no attempt is made by SLS to connect to it. For reference, server IP is 192.168.10.248 on local network, phone is 192.168.10.247, and they are of course on the same network. HTTP access log is also blank on server. Other apps on the device (like Chrome) have no problems connecting to the server IP.

I'm not sure if this is relevant, but no music apps are seemingly picked up by SLS. Tried foobar2000, the built-in player and n7player. No luck on any of them. I've tried reinstalling SLS several times to no avail.

![image](https://cloud.githubusercontent.com/assets/6617815/19788061/8d8f4b12-9ca6-11e6-8c70-3878ff6de8de.png)
![image](https://cloud.githubusercontent.com/assets/6617815/19788067/9ccf8de4-9ca6-11e6-90f2-14caa956ac60.png)

**Comment by HumbleBeeBumbleBee** [comment]
https://github.com/tgwizard/sls/blob/master/app/src/main/java/com/adam/aslfms/service/NetApp.java

**Comment by HumbleBeeBumbleBee** [comment]
Test these  urns directly.
            0x03, "Gnu-fm server", "192.168.1.248/?hs=true", "custom",
            "192.168.1.248", "192.168.1.248/user/%1", "192.168.1.248/2.0/");

**Comment by HumbleBeeBumbleBee** [comment]
It could also be the fact that it's trying to use ssl.

**Comment by HumbleBeeBumbleBee** [comment]
https://github.com/tgwizard/sls/blob/master/app/src/main/java/com/adam/aslfms/service/Handshaker.java#L357-L388

**Comment by bilde2910** [comment]
Interesting. I never got to try directly setting the URL's in source, but I did run a test against an HTTPS URL just now and it was immediately picked up by Wireshark. If I put in an HTTP URL, it does not show up at all. It fails (according to Wireshark) with an unknown certificate error, though I'll see if I can install a self-signed certificate onto my device and server and see if that allows authentication to pass. Seems to me like SLS forcing SSL is what could be the core problem here. I'll double-check.

**Comment by bilde2910** [comment]
I've tried both installing a certificate on my device and cloning the repository and running it with Android Studio but I just *cannot* get it to work. The certificate is not recognized by any installed apps, Android Studio does not recognize the repository as a project and Gradle fails to run. I'm probably doing something wrong here, but it could take me hours just to set up a development environment for this and I unfortunately don't have time to do all that just to confirm whether there is an error in SSL or not.

I'd guess it's most likely due to the app forcing SSL; if you could have it distinguish between `http://` and `https://` URLs then I'd guess that'd fix the problem. Unfortunately, I cannot verify this myself. I'd love to test it on my device, but it looks like I'll need an APK to do that. :-(

**Comment by HumbleBeeBumbleBee** [comment]
I'll rewrite some code for you. You can also check out Let's Encrypt for apache. I can't get GNUFM server working myself. I'm interested in how you did that.

**Comment by bilde2910** [comment]
CA-signed certificates only really work for domain names, and I'm just setting this up locally on an IP address with no associated domain, so getting SSL to work properly is difficult.

It's also worth noting that my GNU.FM isn't *technically* a GNU.FM server. It's a PHP solution I wrote myself that implements the audioscrobbling protocol and stores scrobbles locally in a database. It allows me to nicely chart my listening statistics without having to hand over my listening data to third parties. I can also do interesting queries against my database to show statistics that last.fm and libre.fm can't produce, such as hourly listening trends, etc. It accepts the same input format as GNU.FM, so it should work with SLS. (It works with other scrobblers)

Also thank you for looking into this. When you get them done, I'll test out the changes and see if they work for me.

**Comment by HumbleBeeBumbleBee** [comment]
@bilde2910 Do you need a fully custom url  
`
    CUSTOM(
            0x03, "Gnu-fm server", "[[GNUKEBOX_URL]]", "custom",
            "[[NIXTAPE_URL]]", "[[NIXTAPE_URL]]/user/%1", "[[NIXTAPE_URL]]");
`
OR
you can add the folder /2.0/
and
/?hs=true
`
    CUSTOM(
            0x03, "Gnu-fm server", "[[GNUKEBOX_URL]]/?hs=true", "custom",
            "[[NIXTAPE_URL]]", "[[NIXTAPE_URL]]/user/%1", "[[NIXTAPE_URL]]/2.0/");
`

**Comment by HumbleBeeBumbleBee** [comment]
Also what version of GNU FM are you trying to use?
2.0 or the older method?

**Comment by bilde2910** [comment]
It doesn't matter what URL I use, since I have access to the server anyway and can create directory structures/edit the scripts as needed. I think it might be best to keep it as-is, though, for compatibility and consistency reasons. (Changing it would cause problems for everybody who uses SLS for GNU.FM servers right now.)

My API implements the old protocol (1.2 IIRC) but I can easily implement 2.0 if need be. I'll probably have to do that anyway at some point, so don't worry about that. I'm not entirely sure what the real GNU.FM uses, though. Just do whatever is easiest for you, or whatever works with the official GNU.FM. The main problem that I'm finding is the forced HTTPS, preventing any requests to the server from coming through. Once that part is sorted, I'm sure I can work around whatever protocol is in place so that it works with SLS.

**Comment by HumbleBeeBumbleBee** [comment]
[app-debug.zip](https://github.com/tgwizard/sls/files/597028/app-debug.zip)
This one should give you API 2.0

**Comment by HumbleBeeBumbleBee** [comment]
[app-debug.zip](https://github.com/tgwizard/sls/files/597039/app-debug.zip)
This one should give you API 1.2

**Comment by HumbleBeeBumbleBee** [comment]
I won't commit those changes to the official build now, but I might eventually.

**Comment by HumbleBeeBumbleBee** [comment]
I would need a "developer button" to change the the custom scrobbler to GNU.fm to API 1.2
It's just not sensible at the moment. Users have a hard enough time understanding Android's new power saving options.

**Comment by HumbleBeeBumbleBee** [comment]
I could make the change official though if you use 2.0
technically both changes could be made but that would increase the code size for 4 files.

**Comment by HumbleBeeBumbleBee** [comment]
The only reason that the nixtape url's are still inside the code is because version of android with GingerBread and lower do not have the correct cipher suite for Cloudflare (Libre.fm) server where as Last.fm accepts everything.
If you migrate your code to 2.0 I can maybe add the 2.0 http handshake to the official build.

**Comment by bilde2910** [comment]
Thank you for the APKs. The 1.2 API APK works wonderfully. I'll give 2.0 a shot and see if I can get a proper implementation of it. There's no real reason to stay on 1.2 anyway, because GNU FM [seems to use the 2.0 API](https://github.com/foocorp/gnu-fm/tree/master/gnukebox). There's no reason to keep it there if I'm the only person in the universe who uses SLS with 1.2 on a custom server. I'll get back to you once I've tested the 2.0 implementation.

**Comment by bilde2910** [comment]
I developed a working 2.0 implementation. I can get the 1.2 APK to work perfectly fine, but 2.0 refuses to connect. It only wants to connect over HTTPS, not standard HTTP. In effect, that's the same issue as the published version of the app. Wireshark log is attached. Server IP is .248, device IP is .247. I attempted HTTP first, then HTTPS, then HTTP again. Only the HTTPS connection attempt went through.

![wireshark2](https://cloud.githubusercontent.com/assets/6617815/20392057/80cdf8ac-acd6-11e6-9939-7b0508d54920.png)

**Comment by HumbleBeeBumbleBee** [comment]
Sorry about that, I'll go over the code again.

**Comment by bilde2910** [comment]
No worries! I managed to finally set up an external server after a lot of hassle, with SSL, and that definitely works with SLS. So the only thing I really see is distinguishing between `http://` and `https://`. Last.fm etc. don't have the SSL problem, but for the average Joe running a GNU FM server, I'd imagine it's a bit more work to set up SSL properly.

SSL solves every issue I've detailed in this thread, so adding support for HTTP is really the only thing I can see at the moment. :) I can see if I can create a PR for that if you'd like.

**Comment by HumbleBeeBumbleBee** [comment]
@bilde2910 I am currently working on listenbrainz.org compatibility. I will get back on this project shortly.
It's seems like it would be easier to setup a listenbrainz.org server as it can be setup via Docker.
I'll get back to this soon.
This will give 3 official scrobbling address and 2 custom server options in Simple Last.fm Scrobbler.

**Comment by a93-39a** [comment]
I will add the http:// vs https:// support in the README.md
