### ISSUE TITLE
Uninstalled apps remain in enabled apps list

### ISSUE THREAD

**Issue by lief** [tgwizard/sls#322]
It looks messy. Could you have the app clear music apps from the list once they're uninstalled, please?

**Comment by HumbleBeeBumbleBee** [comment]
I will look into it.

**Comment by HumbleBeeBumbleBee** [comment]
Yes. It could be done however some applications such as "Android Music Player" Apps cannot be removed because they receive standardized music information broadcasts, even though they are reported as not installed.
I could however have a clear button added.

**Comment by HumbleBeeBumbleBee** [comment]
[app-debug.zip](https://github.com/tgwizard/sls/files/601471/app-debug.zip)
