### ISSUE TITLE
add support for VLC android support

### ISSUE THREAD

**Issue by Antinatalist** [tgwizard/sls#327]
https://play.google.com/store/apps/details?id=org.videolan.vlc&hl=en
thanks in advance

**Comment by HumbleBeeBumbleBee** [comment]
I already asked them to support it. There is a conflict in their notification system and track information broadcasts.

**Comment by HumbleBeeBumbleBee** [comment]
Areally you sure your VLC is not scribbling?

**Comment by Antinatalist** [comment]
i am sure.
