### ISSUE TITLE
Scrobbling my Audiobooks

### ISSUE THREAD

**Issue by ketan-a** [tgwizard/sls#329]
I love to listen audiobooks, for that I'm using [this](https://github.com/PaulWoitaschek/MaterialAudiobookPlayer) open source android app. But I don't know how my Audiobook scrobbles are also recorded and sent to Last.Fm/Libre.Fm 
In Enabled App list I'm unable to see this audiobook player listed.
I want to avoid this. Can some one help?

**Comment by HumbleBeeBumbleBee** [comment]
https://github.com/PaulWoitaschek/MaterialAudiobookPlayer/blob/824e88376a6ded3f9c87176c70fd7e60786cab36/audiobook/src/main/java/de/ph1b/audiobook/playback/utils/ChangeNotifier.kt#L105-L124

We should ask the developer to have a button to disable track information
broadcasts, or I might be able to change the code for you.

**Comment by HumbleBeeBumbleBee** [comment]
https://github.com/PaulWoitaschek/MaterialAudiobookPlayer/blob/824e88376a6ded3f9c87176c70fd7e60786cab36/audiobook/src/main/java/de/ph1b/audiobook/playback/PlaybackService.kt#L188
AND
https://github.com/PaulWoitaschek/MaterialAudiobookPlayer/blob/824e88376a6ded3f9c87176c70fd7e60786cab36/audiobook/src/main/java/de/ph1b/audiobook/playback/PlaybackService.kt#L229

**Comment by ketan-a** [comment]
@HumbleBeeBumbleBee Could you please do that and make a PR in that repo,
BTW Thanks for quick reply :simple_smile:

**Comment by HumbleBeeBumbleBee** [comment]
[139-MaterialAudiobookPlayer-debug-v2.9.0.1.apk.zip](https://github.com/tgwizard/sls/files/608829/139-MaterialAudiobookPlayer-debug-v2.9.0.1.apk.zip)

You can test this apk if you like.

**Comment by ketan-a** [comment]
This still getting scrobbled 🙂

**Comment by HumbleBeeBumbleBee** [comment]
Did you change your preferences?

**Comment by HumbleBeeBumbleBee** [comment]
[139-MaterialAudiobookPlayer-debug-v2.9.0.1.apk.zip](https://github.com/tgwizard/sls/files/608871/139-MaterialAudiobookPlayer-debug-v2.9.0.1.apk.zip)

Here's the next one.

**Comment by HumbleBeeBumbleBee** [comment]
![2016-11-23](https://cloud.githubusercontent.com/assets/8563086/20562784/7a030dba-b153-11e6-8a37-d0cedc9d1667.png)

**Comment by ketan-a** [comment]
Hey, Thanks buddy. First apk with toggle turned off, worked for me. Thanks
for the quick fix. Will you do a pull request in that repo?

**Comment by HumbleBeeBumbleBee** [comment]
Yeah.

**Comment by ketan-a** [comment]
I have created a issue there.

**Comment by ketan-a** [comment]
Your pull request is not listed in that repo.

**Comment by HumbleBeeBumbleBee** [comment]
He might be the only one able to officially make the request and pull.

**Comment by ketan-a** [comment]
Yes, it seems that way.

**Comment by HumbleBeeBumbleBee** [comment]
https://github.com/PaulWoitaschek/MaterialAudiobookPlayer/pull/512/
