### ISSUE TITLE
Credentials REQUIRED to work properly

### ISSUE THREAD

**Issue by felip3paixao** [tgwizard/sls#332]
Hello guys, just got a new asus zenfone laser, but when I open the app this message shows up - "Credentials REQUIRED to work properly" ans I can't even log in. Is there a fix
![screenshot_2016-12-01-01-39-59](https://cloud.githubusercontent.com/assets/24285785/20781344/44b0e0bc-b769-11e6-9dbf-9e60a0e5b773.jpg)
?

**Comment by HumbleBeeBumbleBee** [comment]
Hello. Have you signed to last.for or Libre.fm?

**Comment by HumbleBeeBumbleBee** [comment]
Please be sure to leave your username in the credentials.

**Comment by felip3paixao** [comment]
I can't login, it's always showing "NETWORK ERROR" message in any network,....I tried 3g, 4g, wifi...nothing works.

I was researching for asus features and how to whitelist apps but found nothing

**Comment by felip3paixao** [comment]
Man ...suddenly it worked...I think it was a "new phone issue" maybe.

Thanks for the support, got answers here and through google play review....you guys are great  :)
