### ISSUE TITLE
Repeating songs don't scrobble, it only scribbles it the first time 

### ISSUE THREAD

**Issue by coscorrodrift** [tgwizard/sls#337]
I'm using Phonograph, and the scrobbler seems to only detect once the song when I play it on repeat.

It seems that this happens both when I set the repeat button to repeat 1 song and when I queue the same song several times. I'm using Phonograph on Android 6.0.1 in a Samsung Galaxy S7 SM-G930FD

**Comment by HumbleBeeBumbleBee** [comment]
#324

**Comment by Djidiouf** [comment]
@HumbleBeeBumbleBee I have the same issue with Google Play Music.
On another app, I saw that they were able to fix it: https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/issues/1061

I don't get what you mean on the #324 ticket by saying "Shuttle Player may solve this problem." Is your solution to use another music player?
