### ISSUE TITLE
SLS not working on Vanilla Nightly

### ISSUE THREAD

**Issue by Airon90** [tgwizard/sls#341]
SLS doesn't scrobble if I use nightly version of Vanilla Music. It logged into Libre.fm and Listenbrainz, it recognized Vanilla Nightly but no track has been cached to be submitted.

**Comment by HumbleBeeBumbleBee** [comment]
Where can I get a copy of this Vanilla Nightly?

**Comment by Airon90** [comment]
[Here](http://android.eqmx.net/android/vanilla/VanillaMusic-nightly.apk) ;) You can find the link on [Vanilla Music's website](http://vanillamusic.io/) or in the Info section of the app

**Comment by HumbleBeeBumbleBee** [comment]
Ok this apk should fix your problem.

**Comment by HumbleBeeBumbleBee** [comment]
[app-debug.apk.zip](https://github.com/tgwizard/sls/files/752473/app-debug.apk.zip)

A newer version of SLS will fix this problem, but not the upcoming release.
