### ISSUE TITLE
Renaming the app from Simple Last.fm Scrobbler to something else

### ISSUE THREAD

**Issue by Airon90** [tgwizard/sls#342]
The app supports other services and support to other apps has been requested.

**Comment by HumbleBeeBumbleBee** [comment]
True but that's a decision for the originall developer.

**Comment by Airon90** [comment]
Did he decide to maintain the name even with support to other services or did he just choose the name of the app when only Last.fm was supported?

**Comment by HumbleBeeBumbleBee** [comment]
So far it only supports scrobblers. I have tried to add Listen Brainz support but it's still in alpha mode.
