### ISSUE TITLE
Google Play Music not visible in enabled apps

### ISSUE THREAD

**Issue by dudonio** [tgwizard/sls#343]
I'm running official nougat on One Plus 3 and the Scrobbler says in "Android music player" apps, that "This app is not installed".

**Comment by HumbleBeeBumbleBee** [comment]
Does Google play music scribble?

**Comment by HumbleBeeBumbleBee** [comment]
Scrobble?

**Comment by HumbleBeeBumbleBee** [comment]
I will close this until further notice from OP.
Google Play Music should work, but will appear as "Android Music Player" Apps
