### ISSUE TITLE
Chinese Translation

### ISSUE THREAD

**Issue by cmpute** [tgwizard/sls#344]
I'm able to help with Chinese translation.
I've already requested in Transifex, please check it. And also if needed, I can make a pull request.

**Comment by HumbleBeeBumbleBee** [comment]
I have approved the translation however I like pull requests.

**Comment by cmpute** [comment]
@HumbleBeeBumbleBee Is there any thing more than providing with src/main/res/values/values-zh-CN/string.xml ? or I have to translate in transifex and then generate a xml file?

**Comment by HumbleBeeBumbleBee** [comment]
As long as you translate all the lines, you can't get the information anyway you want.
- Email
- Post them here
- Pull request
- Transifex

**Comment by HumbleBeeBumbleBee** [comment]
Awesome merged!
