### ISSUE TITLE
Songs on repeat not being scrobbled

### ISSUE THREAD

**Issue by zamanni** [tgwizard/sls#345]
I'm using Samsung Music Player on Android 6.0.1 and SLS 1.5.3

For some reason, when I have a song set to play on repeat, SLS will only scrobble it the first time I listen and not the other times.

Any way this could be solved? Thanks in advance.

**Comment by HumbleBeeBumbleBee** [comment]
This is a known issue that affects several music applications that do not share track switching information.
#324
