### ISSUE TITLE
add support for Yatse (Kodi remote app)

### ISSUE THREAD

**Issue by iparr** [tgwizard/sls#347]
[Yatse](https://play.google.com/store/apps/details?id=org.leetzone.android.yatsewidgetfree) is a Kodi (formally XBMC) control app.

When music is played through the Kodi device, then scrobbling is handled by Kodi's scrobbling plugin. None of our business!

However, Yatse also has the ability to stream from the Kodi device and play on a mobile device. This works really well and is useful for multi-room setups, etc. This music is not scrobbled, currently.

Support for Yatse in this mode would be brilliant as I believe responsibility for this should lie with the mobile device upon which SLS is installed.

*A similar situation exists with [4-Head](https://play.google.com/store/apps/details?id=com.allo.fourhead) which although streaming doesn't work quite yet, rapid development suggests it will soon! I don't know if both apps can be accommodated at the same time?*

**Comment by inverse** [comment]
That makes totally sense. Unfortunately it requires the paid unlocker to be able to play music which I dont currently have.

Do you know if the application broastcasts the music it's playing? If yes we could try and hook into it.

If yes we could hook into that, alternaitvely get the developer to provide such broastcasts. They could implement our API which would automatically get picked up. 

See: https://github.com/tgwizard/sls/wiki/Developer%27s-API

I'll reach out to the developer to see what they say.

**Comment by iparr** [comment]
I don't know for certain if it broadcasts. I know that it has the ability to show what it's playing within a notification but I'm no app dev. Sorry.

Good luck reaching out to the developer. If they're not game then do consider trying *4-head*!

**Comment by inverse** [comment]
Got this reply from the developer:

>Well Yatse support scrobbling with most apps, it broadcast the standard "com.android.music.metachanged" and "com.android.music.playstatechanged".
It's automatic and by default for the local audio player, and there's an option in advanced settings to also scrobble when Yatse streams to upnp or chromecast renderers.

so it _should_ work but I don't have a licence to try it out. @HumbleBeeBumbleBee can you confirm we listen to the default android broadcasts? It's been a while since I touched android development.

**Comment by iparr** [comment]
I'd be happy to contribute the couple of dollars necessary for a license, if it would help. Thanks for looking into this.

**Comment by HumbleBeeBumbleBee** [comment]
I just purchased the app, I will see what I can do.

**Comment by HumbleBeeBumbleBee** [comment]
https://yatse.tv/redmine/projects/yatse/wiki/Api

**Comment by inverse** [comment]
That's awesome they have documentation :+1:

**Comment by Tolriq** [comment]
Using the API should not be necessary. Yatse sends the standard broadcast as said to @inverse.

It works with the default last.fm scrobbler app. Not sure what else would be needed without adding explicitely your API that I'd prefer to avoid to limit maintenance and issues not related to Yatse.

**Comment by inverse** [comment]
Just tested and it looks like it's scrobbling and being detected as "Android Music Player" apps

**Comment by HumbleBeeBumbleBee** [comment]
Same here it seems to be working.

**Comment by HumbleBeeBumbleBee** [comment]
Local music seems to work but maybe streaming does not.

**Comment by Tolriq** [comment]
Streaming needs to check the advanced option, Announce songs when streaming ;)

Since Yatse can't know to where it's streamed and if the target does not already scrobble it's off by default.

**Comment by HumbleBeeBumbleBee** [comment]
I have tested it and it doesn't seem to broadcast when I play music that is on Kodi.

**Comment by Tolriq** [comment]
You mean play music on Kodi that is on Kodi? This is normal, this is not streaming.

In that case Yatse does not do anything when screen if off, so would miss some songs. This is Kodi roles to scrobble there's addons for that.

The streaming case is when Yatse streams to something like Chromecast or UPnP. As in that case it is responsible for the playing so knows all that is played.

**Comment by HumbleBeeBumbleBee** [comment]
It seems local to chrome cast works.

**Comment by Tolriq** [comment]
Kodi to Chromecast or to local should work too.

**Comment by iparr** [comment]
Thanks for the insight all.

This is now working - even with "Announce songs when streaming" set to off. When I stream to Yatse from Kodi I get submissions to last.fm.

Feel free to close this thread unless you feel you can get it to announce the name as @inverse suggests - it may help avoid similar confusion.

**Comment by Tolriq** [comment]
"Announce songs when streaming" is only needed when streaming via Yatse to something, not when streaming to Yatse.

About getting the name, it's not possible as is. But I can add a new String to the intent that could be handled by sls. Would maybe allow more apps to be supported by sls without the need to fully add your specific API.

**Comment by HumbleBeeBumbleBee** [comment]
Awesome! Great job.
