### ISSUE TITLE
Email in Google Play Store seems to be invalid 

### ISSUE THREAD

**Issue by MartinL0815** [tgwizard/sls#352]
Hi, 

I tried to use the sls-app@… email address to contact "you, but Google returned a failure notification. 

Is GitHub the only way to contact you? 

Best regards, 

Martin

**Comment by inverse** [comment]
Depends what you're contacting about. GitHub is the best place for issues, feature requests, etc

@HumbleBeeBumbleBee is that email invalid now?

**Comment by HumbleBeeBumbleBee** [comment]
Email should still be good.

**Comment by MartinL0815** [comment]
Hi,

There is still a failure notification for: sls-app@googlegroups.com.

The message is about "no such group, or no permission".

Best regards,

Martin Lemburg
Berlin / Germany

martin.lemburg@gmx.net
http://about.me/Martin0815

------- Original message -------

**Comment by HumbleBeeBumbleBee** [comment]
Hell Martin,
You should be able to access it now.
