### ISSUE TITLE
Informational question: Where to get the ListenBrainz token from?

### ISSUE THREAD

**Issue by MartinL0815** [tgwizard/sls#354]
Hi,

I wanted to use the new experimental feature to scrobble to ListenBrainz.

The credentials section of ListenBrainz requires a token, not a password.

I searched for a way to get the token, but was not successfull.

So - could you answer the question how to get the token?

Thanks in advance!

Best regards,

Martin

**Comment by HumbleBeeBumbleBee** [comment]
https://listenbrainz.org/login/?next=%2Fimport

**Comment by HumbleBeeBumbleBee** [comment]
It may not work right now.
