### ISSUE TITLE
[Crazy idea] Firefox support

### ISSUE THREAD

**Issue by regagain** [tgwizard/sls#359]
Hi guys!

It would be really cool to have support for Firefox in order to scrobble the songs I listen to on Bandcamp.

Is there any chance it will happen? Would it be technically feasible?

**Comment by inverse** [comment]
You'll be better pushed working on Firefox for Android extension for this functionality.

https://github.com/david-sabata/web-scrobbler was working on porting to FF for desktop. Perhaps raising a ticket for looking into the mobile extension development too.

**Comment by regagain** [comment]
Thanks!
