### ISSUE TITLE
Help for app configuration listings

### ISSUE THREAD

**Issue by Argoday** [tgwizard/sls#36]
Add a "Why is my app not showing up?" button to the Enabled Apps page that includes the menu options for known supported apps to remind users that they have to enable scrobbling on some (most?) music players

**Comment by HumbleBeeBumbleBee** [comment]
@Argoday Has this been resolved for you application? 
If so, this issue is CLOSED.

**Comment by Argoday** [comment]
This was a suggestion for better user messaging in the SLS app directly, not the supporting application after seeing several users missing the setup steps listed above

That said - this is a long-dead issue and can stay closed
