### ISSUE TITLE
Repeat plays are not scrobbling 

### ISSUE THREAD

**Issue by darklight00** [tgwizard/sls#364]
When I repeat songs via the google play app they don't seem to be scrobbling to last.fm. Only the initial play seems to be showing up.

**Comment by jflory7** [comment]
I can give a +1 to this issue too. I have noticed the same problem with SLS for tracks that I have queued simultaneously after each other in Google Play Music. However, it's not consistent. I noticed that there was one time where I played a song maybe ten times in a row, and only one play was detected, while another time a few hours later I played a song twice, but both plays were detected. The only difference here is that I was actively using my phone when the song I played twice was playing. For the song that I played ten times, I was not actively using my phone.

Is there any debug information that would be helpful to collect or make it easier to review this bug report? I'd be more than happy to provide some if I had instructions or knew what would be helpful to provide.

Also, @darklight00, it would probably be helpful too if you can tell what handset you have, what version of Android you're running, and what version of Google Play Music you're running.

# Phone details

* **Handset**: LG Nexus 5X
* **Android**: 7.1.1
* **Google Play Music version**: 7.6.4619-1.P.3882088

**Comment by danhash** [comment]
Same issue that's been reported multiple times and not fixed. See #324, #155, #337, #345.
