### ISSUE TITLE
Spotify not recognised as music app.  

### ISSUE THREAD

**Issue by alexmitrani** [tgwizard/sls#377]
8.4.3.479 armv7
Motorola Moto G3
Android 6.01

Thanks.

**Comment by HumbleBeeBumbleBee** [comment]
Have you enabled Track Broadcasts in Spotify?

**Comment by alexmitrani** [comment]
I hadn't.  I've turned it on now and it is working.  Thanks very much for
your prompt and helpful reply.

Kind regards

Alex Mitrani
