### ISSUE TITLE
SLS scrobbles skipped tracks that have played for 30secs regardless of the percentage point set in options.

### ISSUE THREAD

**Issue by Londino** [tgwizard/sls#378]
Hello all, first post on Github ever.

So I downloaded from Play Store and installed on my Sony Z5 Compact (Android 7.0) version 1.5.3 of the app which resulted in an odd behaviour using the stock Music app.

As the title of this post mentions, everytime i would skip a track AFTER it had been playing for 30secs SLS would scrobble the skipped track even if it was way far behind the scrobble percentage point. This behaviour would NOT replicate itself if i skipped the playing track before reaching the 30sec mark.

For example, i set my scrobble percentage point at 80% and then went ahead and listened to a track whose length was at least 5 mins long. If i skipped to the next one after 30secs had gone by, SLS would scrobble the skipped trap even though i had listened to no more than 10-15% of the track's total length. If i skipped the playing track BEFORE the 30sec mark, then SLS would work as advertised and not scrobble the skipped track.

I have also tested the above while listening to 30secs off the middle of a track, as opposed to the beginning and the exactly same thing happens.

Thank you for your input. I hope i was as descriptive as possible...

**Comment by a93h** [comment]
This should be fixed in the next release. v1.5.8 vCode 49
I would suggest using F-Droid to test the fix is true.
F-Droid does not require builds meet any specifications, but Play Store requires #476
