### ISSUE TITLE
What URLs to use for custom ListenBrainz/"L-Brnz" server credentials?

### ISSUE THREAD

**Issue by Freso** [tgwizard/sls#379]
Username and token are "obvious", but what goes in URL and API URL? Full URL ("http://my.own.server/") for both? Direct API URL ("http://my.own.server/1/") for API URL? Only the domain name? With or without trailing slash?

I've tried to set it up for https://beta.listenbrainz.org/ and it seems to get stuck on "Authenticating...". I've tried various variations of "https://beta.listenbrainz.org/" and "https://beta.listenbrainz.org" and "beta.listenbrainz.org" (with and without "/1" for the API URL).

**Comment by HumbleBeeBumbleBee** [comment]
Yes. Unfortunately I haven't been able to update the API.
ListenBrainz is in developed phase right now. It might be difficult for me to maintain at the moment I'm somewhat busy.

**Comment by a93-39a** [comment]
Next Release
