### ISSUE TITLE
SLS claims to scrobble, but tracks do not show up on Last.fm

### ISSUE THREAD

**Issue by Mzyxptlk** [tgwizard/sls#382]
I'm using SLS with VLC. Even though SLS claims to be submitting both scrobbles and now playing notifications (the scrobble cache remains empty and the 'total tracks scrobbled' counter increments steadily),  when I visit my Last.fm profile, they do not show up in my Recent Tracks listing. I have exempted SLS from power optimization. I've enabled OnGoing, phone notifications, scrobble and notify now playing and VLC is set as an enabled app.

I'm using a Moto G gen3 with Android 6.0.1 and the latest versions of SLS and VLC from the Play Store. I have reinstalled both SLS and VLC; the problem persists.

**Comment by HumbleBeeBumbleBee** [comment]
Hi @Mzyxptlk , sorry for not getting back to you as soon as possible.
Do you know how to use adb ?
I can help you debug if necessary but I will try the app myself first.

**Comment by Mzyxptlk** [comment]
I'm not familiar with Android development, but I've managed to get ADB up and running, and USB debugging enabled. Happy to look up stuff I don't understand, but otherwise be gentle. :)

**Comment by HumbleBeeBumbleBee** [comment]
Hi @Mzyxptlk 

Please open the zip and run this apk on your phone. [app-debug.zip](https://github.com/tgwizard/sls/files/1310324/app-debug.zip) 

Log into your preferred song scrobbler/listener.

Play music using VLC

Run this command using adb.

> adb -d logcat com.adam.aslfms:D

Post the output here.

**Comment by Mzyxptlk** [comment]
Here it is: [sls-claims.txt](https://github.com/tgwizard/sls/files/1311189/sls-claims.txt)

Starts with VLC playing a track at 17:15:42, containing all the log messages during that track, and ends with VLC starting another track at 17:17:53.

**Comment by HumbleBeeBumbleBee** [comment]
Sorry that command doesn't work for some reason.

I just tried it myself... it's been a while since I used 'adb'.

Here's a better example #165

**Comment by HumbleBeeBumbleBee** [comment]
For example.

> .\adb.exe logcat > ~\Documents\Logcat.txt

**Comment by HumbleBeeBumbleBee** [comment]
I can clean it up myself after that. Please paste the logs of a couple songs at least.
@Mzyxptlk  Have you tried enable OnGoing and Phone Notifications in Options?

**Comment by Mzyxptlk** [comment]
Here: [sls-claims-2.txt](https://github.com/tgwizard/sls/files/1313707/sls-claims-2.txt)

I played 13 tracks. All got picked up by SLS but failed to scrobble. Phone Notifications and OnGoing were enabled for this run. I used the default settings for the previous one.

**Comment by Mzyxptlk** [comment]
I don't know what changed, but the last couple of weeks SLS has been scrobbling fine with VLC. I'm pretty sure I didn't make any changes to the SLS settings in that time. VLC did update at various points in time, but I'm not sure if one of those updates coincided with the point SLS started working again.

Thanks for your efforts!

**Comment by a93h** [comment]
Sounds good.
VLC is still in the android developement process.
Glad it is doing better.
