### ISSUE TITLE
Incorrect credentials/no scrobbling for ListenBrainz

### ISSUE THREAD

**Issue by gregoryopera** [tgwizard/sls#391]
For some time now, Simple Last.fm Scrobbler does not seem to "scrobble" music to ListenBrainz anymore.

I have tried clearing and re-entering my username/"User token" (with and without the "-") and Simple Last.fm Scrobbler will indicate that I am correctly logged-in... But when I start to listen to music, the end result is always the same.

Often, I'll see an error in the notification area that says I'm using incorrect credentials and when I look under "Status" for ListenBrainz (Simple Last.fm Scrobber-->Status-->Listen Brainz), I see something like:
31/08, 20:45
Error, retrying...

This might be related to [Issue 385](https://github.com/tgwizard/sls/issues/385).

**Comment by HumbleBeeBumbleBee** [comment]
Fixed.

**Comment by gregoryopera** [comment]
I concur, this has been fixed.

Thanks!
