### ISSUE TITLE
Notification bug

### ISSUE THREAD

**Issue by rocknosh** [tgwizard/sls#396]
![screenshot_20170918-001356](https://user-images.githubusercontent.com/32042036/30524133-4e2d756e-9c07-11e7-8467-b9c3c18a594b.png)

white bar under notice, android 7.1.2 resurrection remix, last SLS update

**Comment by HumbleBeeBumbleBee** [comment]
Hello, I apologize, I have yet to change the coloring of the logo. This is the love track feature.
You can select the far right 'hidden' white button to love a track on libre/last fm.
