### ISSUE TITLE
SLS losing scrobbles on HTC One V

### ISSUE THREAD

**Issue by timaero** [tgwizard/sls#4]
50% of tracks not being submitted to local cache or even not recognized like last playing.

Problem confirmed with both Hero Music Player and PowerAMP. 

Chech plz.

**Comment by HumbleBeeBumbleBee** [comment]
@timaero @prashker can this be closed?

**Comment by prashker** [comment]
@HumbleBeeBumbleBee I have not had the phone since 2013. Having said that when I last used it I had switched from stock to a CyanogenMod based ROM and there was **not** issues. SLS was working back then.
