### ISSUE TITLE
Doesn't scrobble songs on repeat with Google Play Music

### ISSUE THREAD

**Issue by Jezza-x3** [tgwizard/sls#403]

**Comment by ammgws** [comment]
Experienced this today as well. Only one play was scrobbled (not sure if it was the first or last time that was scrobbled).

**Comment by Jezza-x3** [comment]
@ammgws check the time that it was scrobbled

**Comment by a93-39a** [comment]
This is a well known bug.
I have tried many things, but doing so breaks support for several different supported music players.
I will see what I can do.

**Comment by a93h** [comment]
Closing to redirect conversation to #324
