### ISSUE TITLE
Fix version name (for F-Droid)

### ISSUE THREAD

**Issue by PanderMusubi** [tgwizard/sls#407]
Please fix version name for building for F-Droid, see https://gitlab.com/fdroid/fdroiddata/issues/889

**Comment by breversa** [comment]
Latest available version on F-Droid is currently 1.5.3 : https://f-droid.org/wiki/page/com.adam.aslfms#1.5.5

**Comment by PanderMusubi** [comment]
I think in a day or so the new build will appear in the F-Droid client. See https://gitlab.com/fdroid/fdroiddata/blob/master/metadata/com.adam.aslfms.txt Please report here if you see it appearing.
