### ISSUE TITLE
Not scrobbling on Android 7.1.2

### ISSUE THREAD

**Issue by airon90** [tgwizard/sls#411]
I'm using latest F-Droid version of Vanilla Music on Android 7.1.2 and SLS is not even scrobbling music I listen to

**Comment by inverse** [comment]
Hmm - I've not got experience with Vanilla Music but with Pulsar I've not had any issues on 7.1

**Comment by airon90** [comment]
Could it be just a problem of Vanilla Music?

**Comment by abn-volk** [comment]
You could try enabling "Emulate stock broadcast" in Vanilla's settings.

**Comment by airon90** [comment]
Now it works, thank you. Anyway, is it a workaround (and keep this BR open) or should I have toggled that option before (and close this BR)?

**Comment by abn-volk** [comment]
IMO it's still a bug because Vanilla uses ScrobbleDroid's API and it should work with SLS.
