### ISSUE TITLE
Not finding Rocket Player on Oneplus 5T

### ISSUE THREAD

**Issue by iambears** [tgwizard/sls#412]
I just switched from a Nexus 5X running android 8.x to the OnePlus 5T running android 7.1.

I use Rocket Player by JRT Studio and simple last.fm would find the player on my 5X but now it won't on my 5T. Any suggestions on how to make this work?

**Comment by Gaardb** [comment]
In Rocket Player, go to **Settings > Sound > Installed Scrobbler**. Select Simple Last.fm. Start a music, and now SLS will detect Rocket Player.
