### ISSUE TITLE
Use resConfigs in build.gradle to reduce size and support multiple locales

### ISSUE THREAD

**Issue by abn-volk** [tgwizard/sls#416]
According to [this blog post](https://blog.egorand.me/a-curious-case-of-multiple-locales/), using `resConfigs` in the app's `build.gradle` helps remove unsupported language resources introduced by external libraries (most likely the AppCompat and support libraries) and support Android Nougat's multiple locales feature. For example, if the user's languages are Swahili, French and English, the app will be shown in French instead of English (due to incomplete Swahili resources in the support library).

This is a small but very nice change for multiple-locale users like me, and there are no drawbacks to it.

**Comment by G00fY2** [comment]
Actually a real benefit would be just using proguard which also optimizes the code. I am not sure why it is disabled in this app. I am using a self compiled apk using proguard and apk size decreased by about 40%.

**Comment by a93-39a** [comment]
Certainly on my to-do list,
I might do a new release first however.

**Comment by a93h** [comment]
The next release should have these features.
Thanks @G00fY2
