### ISSUE TITLE
Feature request: remember scrobble edits

### ISSUE THREAD

**Issue by borealissw** [tgwizard/sls#422]
Probably the best feature on SLS is the ability to edit the scrobbles (typically to remove the " - XYZ remastered version" that Spotify, Google Play et al add to many many albums).

What would make it even better would be the ability to remember these changes and reapply them automatically in the future.

NB: I may be able to work on this myself once I have some spare time - I'll check in on this in the future.

**Comment by a93-39a** [comment]
@4-Eyes added this in a pull request.
Should be in the next update.
Thanks.

**Comment by borealissw** [comment]
Thanks for this
