### ISSUE TITLE
App Icon Dark Gray Background

### ISSUE THREAD

**Issue by codysherman** [tgwizard/sls#426]
On a Pixel XL 2, but I'm assuming all Pixel Launcher phones, SLS icon in the app drawer has an ugly dark gray background.
![screenshot_20180219-134954](https://user-images.githubusercontent.com/371608/36394859-d67265e0-157b-11e8-90af-a5b6f1fbe623.png)

**Comment by G00fY2** [comment]
Thats the general app icon design: https://github.com/tgwizard/sls/blob/master/app/src/main/res/mipmap-xxxhdpi/ic_launcher.png

Not sure what issue you have with that? Design is always individual taste. If you'd like to see a circle shape to fit Googles current design I would agree.

**Comment by codysherman** [comment]
Oh wow I'm sorry if the gray was an intended choice, I thought it was a bug since it doesn't match the icon in the Play Store.

Let me add my argument: I think that the gray background is too similar to the red of the icon, I'd recommend using a much lighter, or even white background, for the rectangle or circle behind the logo. The gray and the red are much to similar and the icon really gets lost into it. This is magnified on the Pixel 2 screens especially since they use the more flat RGB colors.

Please just consider lightening up whichever color you decided to use for the background, to make the "as" really pop out more.

**Comment by a93-39a** [comment]
![web_hi_res_512](https://user-images.githubusercontent.com/8563086/62823183-6953dd80-bb5c-11e9-84b6-4e6851f9e29a.png)
