### ISSUE TITLE
SLS can't scrobble the same track played consecutively in the default player

### ISSUE THREAD

**Issue by tgwizard** [tgwizard/sls#44]
This is due to the fact that the default player only sends one* kind of event: "Something has changed". It is therefore impossible to determine if the track has been paused, resumed, started, stopped, started again, etc. Also, the intent doesn't contain the track duration, so the play state info cannot be deduced from that.

*there is another kind of intent sent when an entire playlist finishes. So, a playlist with only one track set on repeat works fine.

**Comment by HumbleBeeBumbleBee** [comment]
Triplicate continue discussion in #155
