### ISSUE TITLE
n7player huge error

### ISSUE THREAD

**Issue by skolopendrzak** [tgwizard/sls#440]
Hi, hope to find some help here,
each time I use n7player to scrobble any song, this happens: 

https://www.youtube.com/watch?v=FPMZ3fP7Gs4

and the songs are not scrobbling to my account. Sometimes Last.Fm tab can't dissappear even when the player is off and I have to stop the app on Settings menu.
Scrobbler works on Google Play Music and other apps, but I'm not that satisfied of them, so I wouldn't wanna change it. Do U guys know what is that and how can I resolve it? 

I've got Huawei P10, I used Huawei P9 before and the same thing happend. 
Simple Last.Fm Scrobbler also doesn't scrobble anything from n7player and the creators of the player doesn't responde my messages. :1st_place_medal:

**Comment by a93-39a** [comment]
Hello friend,
I am looking into your issue right now.
Thanks for the post.

**Comment by a93-39a** [comment]
Is this an n7 bug or n7+ bug?

**Comment by a93-39a** [comment]
I tested the app.
The seems to be an issue with n7 and n7 developers.
Unfortunately this is outside the scope of Simple Last.fm Scrobbler.
I'm sorry to hear this news.
I'm closing until further notice.
