### ISSUE TITLE
Not scrobbling, after resume playback

### ISSUE THREAD

**Issue by Offerel** [tgwizard/sls#443]
Most of my tracks are longer DJ-mixes with playtimes more than 1hour. If i pause the playback for a while and resume playback after some time (1 - 3hours later), the track isn't recognized again and not scrobbled. However the now-playing was working, when the track started. Also, when i skip the track and play the next title in the playlist, this new song appears in the now-playing category.

**Comment by a93h** [comment]
Sorry for the delay,
Can yous hare the app name and some information about your settings in Simple Last.fm Scrobbler.
Did you optimize battery and did you enable OnGoing?
