### ISSUE TITLE
Amazon Music - doesn't update when songs change

### ISSUE THREAD

**Issue by dufferzafar** [tgwizard/sls#446]
**Bug:** SLS doesn't scrobble all Amazon Music tracks.

**Test Plan:**

1. Play a song on Amazon Music.
2. Check that SLS shows phone notification & begins to scrobble.
3. Wait for the song to end and for Amazon Music to automatically switch to the next one.
4. See that the SLS notification still shows the last song.

**Expected:** SLS should discover that the song has been changed & scrobble it.

**Workaround:** Pausing - Playing the Amazon Music app a bunch of times results in the song being detected by SLS.

**Comment by dufferzafar** [comment]
Scroball works: https://github.com/peterjosling/scroball

But requires notification access :cry:

**Comment by MartinL0815** [comment]
Amazon Music didn't work for me, too.
After since tracks the delay in scribbling increases untill the synchronization is completely broken since SLS send to get slower more and more.
What helps is to force termination of both apps … for a whine.
Other apps, seldom used, like BubbleUPnP work fine.

**Comment by a93-39a** [comment]
Please see my comment here. [Issue 447](https://github.com/tgwizard/sls/issues/447)
