### ISSUE TITLE
Accidentally pressed "Clear List" on "Enabled Apps", now it doesn't detect any music apps.

### ISSUE THREAD

**Issue by j2nik** [tgwizard/sls#451]
As the title says pretty much

(I've reinstalled a dozen time)

**Comment by inverse** [comment]
@Rocksteady18 this app is maintained by people in their spare time for non-profit.

Feel free to contribute.

**Comment by Rocksteady18** [comment]
The thing is, it's not being maintained at all for at least a year.

No need for sarcasm. 

If I was a programmer I could make something that worked. 

But for now I'll just uninstall. 

🙄

**Comment by a93-39a** [comment]
Hello everyone,
Is there any more information you could share on the situation?
A bit more data would be helpful, but I can check the code also.
Thanks,
Austin

**Comment by a93-39a** [comment]
Never mind, found it.

**Comment by a93-39a** [comment]
[We have a missing close database here](https://github.com/tgwizard/sls/blob/master/app/src/main/java/com/adam/aslfms/receiver/MusicAPI.java#L197-L202)
Can cause database corruption.
Most likely you should be able to clear the cache and the app should work again.
You will need to re-login after clearing the cache.

**Comment by a93-39a** [comment]
The next update will provide the correct fix.

**Comment by j2nik** [comment]
> The next update will provide the correct fix.

ETA on update release? the rest of the scrobble apps suck

**Comment by a93-39a** [comment]
@j2nik 

Potential fixes, delete the application cache & login again,
Once logged in please refrain from pressing the clear music app cache.
I found the bug, so if you don't hit the evil button, it should not ruin the database.
It's a fun little feature, a mini-game inside the app.
I should have made text, "Hit this button, and you detonate the functionality of SLS."
Game Over button.. terrible.
lol, anyways you get the idea.

OR

I can provide you with the debug version like this one right here.
[app-debug.zip](https://github.com/tgwizard/sls/files/3326914/app-debug.zip)

Short Version :: as soon as God permits and tgwizard gives me the keys and access to the google dev console.

Long Version :: I was in a coma for two weeks and almost another recently.
I got all spiritual in the meantime, but also forgot some of my passwords.
I built my own Scrobbler that is about 1/3 ready to be put on Github, and thousand times more functional and cool than anything else out there.
Problem is I am going to go all out and maybe make my own API/protocol for metadata recording.

I got lazy and decided to help this more popular app get better.
I just started coding again recently, and built a few websites in a few days to get my bearings again.

As soon as tgwizard sees it is really me, his "terrible" right hand developer for simple last.fm scrobbler.
He'll give me access to rebuild, fix, refactor and so on.

**Comment by j2nik** [comment]
Wow what a story, I certainly did not expect this. The app started to randomly work a few months ago, but for a week it just stopped working after re-enabling the spotify app in SLS settings.

Lord have mercy I will pray for you

**Comment by j2nik** [comment]
I tried the debug version and it didn't work. It does recognize other music players but not Spotify. (I am using a older verison of Spotify because their recent update was terrible.. So I'm on 8.5.2.759

**Comment by a93-39a** [comment]
@j2nik Did you remember to enable broadcast setting inside of Spotify?
Sometimes updates disable stuff.

**Comment by j2nik** [comment]
> @j2nik Did you remember to enable broadcast setting inside of Spotify?
> Sometimes updates disable stuff.

Oh it looks like it was off! Works perfect now

**Comment by a93-39a** [comment]
Great, I will close this issue once @tgwizard  gives me the keys again...(i hope)

**Comment by a93h** [comment]
Have the keys but the biggest issue is now SDK Version.

If you know what F-Droid is, I might suggest using a build from F-Droid first.

**Comment by a93h** [comment]
Play Store has restrictions on it's SDK Version which will break the majority of SLS functionality.
