### ISSUE TITLE
Amazon Music on FireTV not recognized anymore

### ISSUE THREAD

**Issue by drjobec** [tgwizard/sls#453]
Hi,
Earlier SLS recognized Amazon Music on FireTV just fine and scrobbled happily the plays. At some point, which I don't know exactly when, the co-operation ended. I tried to update SLS to the most recent version, but it still doesn't recognize Amazon Music as a player app. My guess would be that Amazon changed something in the Music app or FireOS itself. Still, it would be great if the functionality can be recovered. 
As an additional feature: also scrobbling the songs played via "Alexa, play XX YY".

Best,
  Jouni

**Comment by a93-39a** [comment]
Please see my comment here. [Issue 447](https://github.com/tgwizard/sls/issues/447)
