### ISSUE TITLE
MusicPiped app support

### ISSUE THREAD

**Issue by john3voltas** [tgwizard/sls#458]
https://github.com/deep-gaurav/MusicPiped
This is a great way to listen to music from youtube. Apparently based on the excellent NewPipe app.
Could I interest you in adding support to both apps?
Thanks in advance.
Cheers

**Comment by 97carmine** [comment]
With version 1.0.7 of MusicPiped it works without problems

**Comment by john3voltas** [comment]
> 
> 
> With version 1.0.7 of MusicPiped it works without problems

Indeed, it does. It didn't at the time that I wrote the post here, though.
Apparently it needed development that got committed into MusicPiped on the very same day that I posted here.
This issue can now be closed.
Thanks a bunch, though.
Cheers
