### ISSUE TITLE
Spotify not detected in SLS

### ISSUE THREAD

**Issue by adityasubathu** [tgwizard/sls#460]
SLS isn't detecting Spotify and hence not scrobbling anything to Libre.fm. Works fine for offline players and Amazon Prime Music.

Device Details:
Lineage OS 16 based on Android Pie, March Security Patch
SLS Version: 1.5.7
Spotify Version: 8.4.96.953

**Comment by adityasubathu** [comment]
Never mind. Worked after I enabled Device Broadcast Status in Spotify. Dumb me

**Comment by a93-39a** [comment]
Nope. I didn't know about the setting either first time. Not dumb.
Just not clicky :)
Internet is clicky.
