### ISSUE TITLE
License Problem

### ISSUE THREAD

**Issue by dalb8** [tgwizard/sls#49]
There is a problem with the license because it cannot be released under the Apache 2 license and still contain GPL code.

**Comment by HumbleBeeBumbleBee** [comment]
Is there anyway to put SLS under an Apache License?
For now I am changing the About information to GNU General Public License v3.0

**Comment by tgwizard** [comment]
So, the only code requiring GPL v3 is https://github.com/tgwizard/sls/blob/master/app/src/main/java/com/adam/aslfms/util/MD5.java. If we can rewrite the code to not use that MD5 copy-pasted lib, and remove that file, then we can go to the Apache License.

@HumbleBeeBumbleBee do you or someone else want to look into that?

**Comment by inverse** [comment]
could use a solution such as what's outlined here: http://stackoverflow.com/a/4846511/50913
