### ISSUE TITLE
add support for Slacker Radio

### ISSUE THREAD

**Issue by vash1122** [tgwizard/sls#51]
Hi,

I was wonder if it would be possible to add support for slacker radio:
https://play.google.com/store/apps/details?id=com.slacker.radio&hl=en

Thanks.

**Comment by HumbleBeeBumbleBee** [comment]
I will try to work on this. :)

**Comment by HumbleBeeBumbleBee** [comment]
I have sent an email to support-android@slacker.com requesting they broadcast song information so SLS can scrobble music played in Slacker Radio.

**Comment by HumbleBeeBumbleBee** [comment]
Their response.
>Thank you for your suggestion. We will forward this on to our development team for future considerations.
