### ISSUE TITLE
Songs scrobbling twice

### ISSUE THREAD

**Issue by goodevilgenius** [tgwizard/sls#52]
I'm using the "Play Music" (Google Music) app on my Kindle Fire, and I'm seeing songs show up twice on both my libre.fm and last.fm profiles.

**Comment by HumbleBeeBumbleBee** [comment]
This pull https://github.com/tgwizard/sls/pull/149 may be your solution. Check it out!

**Comment by goodevilgenius** [comment]
It's worth noting that I'm using a new device (Nexus 6) now with the same app, and that no longer happens.

I don't know if updates to Play Music fixed it, or if switching to a new device fixed it.

**Comment by HumbleBeeBumbleBee** [comment]
Is anybody else still having problems?
You can probably CLOSE this issue then @goodevilgenius
