### ISSUE TITLE
add support for Plex

### ISSUE THREAD

**Issue by claytron** [tgwizard/sls#53]
I would like to be able to scrobble songs from the Plex media center when it is playing music.

**Comment by HumbleBeeBumbleBee** [comment]
I will try to get this working.

**Comment by HumbleBeeBumbleBee** [comment]
Hi @claytron, do you know how to use adb such as `adb shell dumpsys activity broadcasts` while plex is running to see if it broadcasts song information?
I don't have plex and don't really plan on getting it...

**Comment by HumbleBeeBumbleBee** [comment]
I have sent an email to support@plex.tv requesting they broadcast song information so SLS can scrobble music played in Plex.

**Comment by HumbleBeeBumbleBee** [comment]
The instant response referred me to their forums.
It appears the question is being asked there too.
http://forums.plex.tv/discussion/28286/scrobbling-to-last-fm

and there is no official solution.

Possibly there is server side scrobbling though.

**Comment by ibrokemypie** [comment]
there is server side scrobbling. i see there has been no reply about the adb broadcasts so i will take a look when i can
