### ISSUE TITLE
add support for Songza

### ISSUE THREAD

**Issue by goodevilgenius** [tgwizard/sls#55]
com.ad60.songza

**Comment by HumbleBeeBumbleBee** [comment]
I will try and work on this. :)

**Comment by HumbleBeeBumbleBee** [comment]
Turns out Songza doesn't really broadcast their intents. I have tried a couple of things.
No luck...
I did fire out an email to them.
- Bumble

**Comment by HumbleBeeBumbleBee** [comment]
Sorry. Songza has been discontinue and purchased by Google Play Music.
