### ISSUE TITLE
Support scrobbling streams

### ISSUE THREAD

**Issue by quasar** [tgwizard/sls#56]
Any plans to support scrobbling streams? I listen to di.fm a lot, that would be cool. Last.fm app has streaming scrobbling

**Comment by HumbleBeeBumbleBee** [comment]
Is this a request for supporting the application [Digitally Imported Radio](https://play.google.com/store/apps/details?id=com.audioaddict.di) ?

**Comment by HumbleBeeBumbleBee** [comment]
Please continue discussion in #96, or let me know if this issue should be reopened.
