### ISSUE TITLE
Winamp support

### ISSUE THREAD

**Issue by Cisownik** [tgwizard/sls#58]
Hi, after downloading v1.4.4 the app stopped seeing Winamp and wouldn't scrobble from it. I also tried JRTStudio app and it worked. Thanks

**Comment by HumbleBeeBumbleBee** [comment]
@Cisownik  @StErMi @petesimon @sturek82 @mmrose 
Are any of you still using WinAmp for Android?
I can't find any reliable sources for the newest version of WinAmp...
We can't really support an application (.apk) we cannot find or trust.

**Comment by mmrose** [comment]
I do not use it anymore.

**Comment by HumbleBeeBumbleBee** [comment]
WinAmp is deprecated, I think I'll be closing all of it's related issues unless a reliable new version is released from nullsoft.
