### ISSUE TITLE
Doesn't detect or scrobble default musicapp. LG Optimus X2

### ISSUE THREAD

**Issue by rezs** [tgwizard/sls#62]
I'm having problems with detecting and scrobbling music from the default music player through SLS. Also, it says Android music player (and other players) isn't installed, though it scrobbles other players. I've also tried using Scrobbledroid and the default Last.FM-app and that doesn't work either. Downloaded players like Winamp, Poweramp, PlayerPro and so on scrobbles just fine.

Model: LG-P990
Android version: 2.3.4
Baseband: 1035.21_20120521
Kernel: 2.6.32.9
LG version: LGP990-V20s

**Comment by HumbleBeeBumbleBee** [comment]
@rezs Is this still a problem or no?

**Comment by rezs** [comment]
Hi. I'm sorry, I don't have a LG anymore.
Den 1 maj 2015 18:58 skrev "HumbleBeeBumbleBee" <notifications@github.com>:

**Comment by HumbleBeeBumbleBee** [comment]
Thanks! Hopefully this is fixed.
It's an old post so I'll be closing it.
