### ISSUE TITLE
add support for Cloudskipper

### ISSUE THREAD

**Issue by elwayman02** [tgwizard/sls#63]
I'd like there to be support added for the Cloudskipper media player app.

https://play.google.com/store/apps/details?id=cloudtv.cloudskipper&hl=en

This would be greatly appreciated!

Thanks Adam for directing me here to open the issue.

**Comment by HumbleBeeBumbleBee** [comment]
I have sent an email to cloudskipper-feedback@cloud.tv requesting they broadcast song information so SLS can scrobble music played in Cloudskipper.
