### ISSUE TITLE
Does not support Samsung Music Player in Galaxy S3

### ISSUE THREAD

**Issue by Leonidas-from-XIV** [tgwizard/sls#65]
Hi,

SLS does not detect the stock TouchWiz music player in the Galaxy S3. As this player it integrated pretty well into the UI, I'd like to keep using it with SLS.

The process seems to be named com.sec.adnroid.app.music, please let me know what data is required to add support for this player. I'd send a pull request if you'd let me know how to add support for it.

Thanks!

**Comment by HumbleBeeBumbleBee** [comment]
That URL is dead.
I also have a Samsung Galaxy S3 and the stock TouchWiz music player.
I have testing two Samsung Galaxy S3's and the SLS application works on both.
Maybe you could try debugging your phone with `adb`, unless you've resolved the issue.

**Comment by Leonidas-from-XIV** [comment]
I've stopped using the stock player and migrated to CyanogenMod, so I can neither confirm nor deny it being fixed.

**Comment by HumbleBeeBumbleBee** [comment]
Apologies, maybe the URL is a region thing.
