### ISSUE TITLE
Support for Sony Music Unlimited

### ISSUE THREAD

**Issue by k-arttu** [tgwizard/sls#66]
Any chance for getting support for Sony's Music Unlimited player?  I can help in testing and debugging, if possible.

**Comment by HumbleBeeBumbleBee** [comment]
@k-arttu  @soustruh 
I can try and help with this, but I don't have the devices you have. Maybe I will try and contact the developers.

**Comment by k-arttu** [comment]
Don't bother, Sony just discontinued Music Unlimited.
