### ISSUE TITLE
Add support for Tune in Radio

### ISSUE THREAD

**Issue by urbels** [tgwizard/sls#68]
Add support please! ;)

**Comment by HumbleBeeBumbleBee** [comment]
I will try to work on this. :)

**Comment by HumbleBeeBumbleBee** [comment]
I have fired out an email to Tunein about sharing their broadcasts or enabling support for SLS some how.
Hopefully they add support in their next release. :)

**Comment by HumbleBeeBumbleBee** [comment]
duplicate #15

**Comment by samosfator** [comment]
@HumbleBeeBumbleBee  so did they?

**Comment by HumbleBeeBumbleBee** [comment]
Hi @samosfator. 
I have sent an email to Tune In [android-support@tunein.com](mailto:android-support@tunein.com).
When I receive a response I will display it in #15.
As of now, no, tunein has not yet been supported.
The discussion regarding 'Tune In' has been moved to #15 
Thanks.
