### ISSUE TITLE
Should scrobble once listened to a track, not at the begining of the next track

### ISSUE THREAD

**Issue by dror3go** [tgwizard/sls#69]
I'm listening to music using Songbird (v2.6) with Samsung Galaxy S3, and I've noticed that each time I listen to an album - its last song isn't scrobbled to last.fm.
I found that once I start listening to another song - the last song from the previous album is scrobbled. Usually this is ok, but if I don't start listen to a different track and close Songbird - the last listened song won't get scrobbled to last.fm.

**Comment by HumbleBeeBumbleBee** [comment]
I will try and work on this. :)
This may be your solution. https://github.com/tgwizard/sls/pull/149 Check it out!

**Comment by HumbleBeeBumbleBee** [comment]
@dror3go 
If you know how download and build the .apk
Please use this branch https://github.com/tgwizard/sls/tree/testing-149
Otherwise you can use the latest .apk here.
https://drive.google.com/file/d/0B9lPaMaVVtiJLVlLendjSmxRZDA/view

**Comment by HumbleBeeBumbleBee** [comment]
@dror3go
https://drive.google.com/file/d/0B9lPaMaVVtiJYTVVVDR4YkU1QUU/view?usp=sharing
This is a beta testing version. Let me know if it solves your problem.
It has a different key so you'll have to uninstall and setup SLS again.

**Comment by HumbleBeeBumbleBee** [comment]
Hello @dror3go 

There are two major issues with doing this and two major compatibility. 

SLS provides support for a variety of applications.
OR
SLS provides support for single track repeat and more structured scrobbling.

Some of these applications don't share track duration (well).
and
Some of these applications don't tell SLS when the track is paused or completed, so SLS cannot find out when the track officially started or finished.

I am manually going through all the applications to see which ones don't work with a more compatible scrobbling service.

**Comment by HumbleBeeBumbleBee** [comment]
This is a known issue that will take some time to find a solution.
I will close this issue for now.
