### ISSUE TITLE
Please add support for GrooveMobile

### ISSUE THREAD

**Issue by neyel8r** [tgwizard/sls#71]
Please add scrobbling support for GrooveMobile, a very awesome app that allows you to play songs from Grooveshark on your android for free!

**Comment by HumbleBeeBumbleBee** [comment]
@neyel8r could you please provide an updated link to the GrooveMobile application so that I may test it.
I am not sure if the app is still in use.
Otherwise this issue is CLOSED.

**Comment by HumbleBeeBumbleBee** [comment]
http://grooveshark.com/ is closing down. This issue is now CLOSED.
