### ISSUE TITLE
Scrobbles not appearing on last.fm

### ISSUE THREAD

**Issue by xzenx** [tgwizard/sls#73]
Hi,
I have the same problem as were explained here:
https://github.com/tgwizard/sls/issues/16
https://github.com/tgwizard/sls/issues/67

I'm on Sony Xperia Ray and using Last.FM Scrobbler for Xperia for enabling the sony music player to be used with SLS. The music player is detected in SLS and the tracks and now playing info is also appearing and correct.

SLS scrobble stats show last scrobble's and now playing notifications sent and the totals are growing as well, but the scrobbles and now playing info are not appearing on my last.fm profile.

What can be the problem?

In the previous posts Last.FM Scrobbler for Xperia was "blamed", but it's only purpose is to enable scrobbling for xperia and give the info to SLS -> and that IS working.

**Comment by HumbleBeeBumbleBee** [comment]
Hi, I don't have that phone. Do you know if the music player is stock or if it can be found on google play or downloaded as an .apk ?
If I could get a hold of the music player I could definitely help. I am not so sure I can go out and buy the phone.

**Comment by HumbleBeeBumbleBee** [comment]
Continue discussion of this problem in #16
