### ISSUE TITLE
Won't scrobble from the Rhapsody App

### ISSUE THREAD

**Issue by wakeupgetdown** [tgwizard/sls#76]
Hi, on the google playstore, you have Rhapsody Android listed as a supported app, but it will not recognize the app when playing music so I can't scrobble from it.

I've heard people say that it used to work with the Rhapsody Beta app, but I am currently running version 3.0.1.89 on an ASUS tablet with Android Ice Cream Sandwich.

If you could fix this issue, it would be greatly appreciated, as Rhapsody is the only device I use for listening to music.

Thank you,
Janice

**Comment by HumbleBeeBumbleBee** [comment]
Hi @wakeupgetdown, please refer to #20 for continued discussion.
