### ISSUE TITLE
add support for Droidsound

### ISSUE THREAD

**Issue by SHMAUS-Carter** [tgwizard/sls#77]
as a listener of chiptunes It would be nice if droidsound scrobbled

**Comment by HumbleBeeBumbleBee** [comment]
Could you please share a link of exactly which droidsound application you are referring to?
I have found 
https://play.google.com/store/apps/details?id=com.ssb.droidsound
and
https://play.google.com/store/apps/details?id=com.droidmjt.droidsounde

**Comment by SHMAUS-Carter** [comment]
Droidsound-E is a derivative / continuation of the original Droidsound. 
so in short https://play.google.com/store/apps/details?id=com.ssb.droidsound is the app i use from time to time to listen to chiptunes that said given that https://play.google.com/store/apps/details?id=com.droidmjt.droidsounde seems to be by the same creators I might be switching to that some time down the road as it seems they have stopped updating the old version.

**Comment by HumbleBeeBumbleBee** [comment]
I have sent an email to sasq64@gmail.com requesting they broadcast song information so SLS can scrobble music played in Droidsound.

**Comment by HumbleBeeBumbleBee** [comment]
I have sent an email to droidmjt@gmail.com requesting they broadcast song information so SLS can scrobble music played in Droidsound-E.

**Comment by droidmjt** [comment]
Droidsound-E is maintained by me. Anyway, I can include this scrobble thingy if it doesn't require tons of changes here and there :)

**Comment by HumbleBeeBumbleBee** [comment]
Hi @droidmjt thanks for such a quick response!

**Comment by HumbleBeeBumbleBee** [comment]
Vanilla Music has a builtin scrobbler, open source shown [here](https://github.com/vanilla-music/vanilla/blob/master/src/ch/blinkenlights/android/vanilla/PlaybackService.java#L1060).

**Comment by HumbleBeeBumbleBee** [comment]
[Scrobble Droid API for SLS](https://github.com/tgwizard/sls/blob/master/app/src/main/java/com/adam/aslfms/receiver/ScrobbleDroidMusicReceiver.java)

**Comment by droidmjt** [comment]
This feature has been added to Droidsound-E and will be availabe in next version (1.664). I will soon release unofficial build for those who can't wait :)

**Comment by HumbleBeeBumbleBee** [comment]
It seems to work.
