### ISSUE TITLE
Poweramp: Only updating "now playing" but no scrobbling

### ISSUE THREAD

**Issue by k0pernikus** [tgwizard/sls#78]
Simple Last.fm Scrobler has become unreliable. As of now, it most of the time will only update the "now playing" track information, but will never scroble the track after its ending.

Scrobble Status even showcase this:

Last Scrobble submitted at:
15.03.2013, 21.44

Last Now Playing notification submitted at:
15.03.2013, 23:50

Scrobble Cache is shown to be zero.

I rechecked the settings in both Poweramp and Simple Last.fm Scrobler.

Poweramp Version: 2.0.8-build-525 Full Version
Simple Last.fm Scrobler: 1.4.5 (latest from PlayStore)
Device: Huawei Honor ICS 4.0.3

**Comment by HumbleBeeBumbleBee** [comment]
Has this been resolved @k0pernikus or no?

**Comment by HumbleBeeBumbleBee** [comment]
I have tested the latest version of PowerAmp, everything is working.
I will close this issue unless somebody has a similar problem.

**Comment by 4679** [comment]
![img](http://i.imgur.com/xvfVrSR.png)
Same problem
Poweramp version:alpha-build-703-uni

**Comment by Danacus** [comment]
Same for me

**Comment by felipecalvo** [comment]
I'm having the same issue on Android 6.0.1.

**Comment by a93-39a** [comment]
If anybody has this problem, please create a new issue.
Closing as out of date.
