### ISSUE TITLE
Randomly scrobbles a particular track

### ISSUE THREAD

**Issue by najones13** [tgwizard/sls#79]
The app seemed to be working fine until I checked my last.fm to find that it had been scrobbling a particular song whenever it felt like it. I've played the song once in the last 7 days yet it's been scrobbled 16 times. I have no idea why this is happening, my music player is not running yet I go into simple scrobbler stats to find it now playing the song.

I've tried uninstalling, restarting and reinstalling the app but having the same issue with the same song. Everything else scrobbles perfectly except the one song and it's messing up my last.fm with all the extra scrobbles.

Samsung Galaxy sII. 4.1.2
Using Player Pro as my music player

**Comment by HumbleBeeBumbleBee** [comment]
Has this been resolved @najones13 or no?

**Comment by HumbleBeeBumbleBee** [comment]
>@bannus writes
>I've been using this app for several years, and I've noticed a strange bug. A certain track (Saint Christopher by Bibio) gets scrobbled at random times when I'm not listening to music. I would guess it happens once every few weeks. Unfortunately, I had built up so many plays of this song (~50?) that I deleted most of the scrobbles from [my last.fm](http://www.last.fm/user/bannusv/library/music/Bibio/_/Saint+Christopher).

>It just happened again this morning before I woke up. Are there any logs I can find to see why SLS thinks this track should be scrobbled?

>@inverse writes
>I've noticed this too sometimes with a different [track][0]. 

[0]: http://www.last.fm/user/inverse.chi/library/music/%231/_/21+GOLD+LEGS+8+(with%2392E4A3C

**Comment by b-gergely** [comment]
Same problem here. It is very annoying, as it completely messed up my Last.fm statistics by scrobbling some random track (I have listened to once) again and again at random times. Then I listen to something else, and it happens again with another tracks. I have no idea how much time it is going on now. I considered deleting my whole Last.fm profile because of this. I am using the built in Music app of Samsung Galaxy phones (as someone else as well in a duplicate issue).

**Comment by najones13** [comment]
I found that unchecking the android music player in enabled apps completely stopped any spontaneous scrobbling. I use rocket player and Google music now and both scrobble correctly

**Comment by jamesonuk** [comment]
Have this too.  Caught it today with song sat in cache.  Interestingly it said it was via android music app but on the enabled apps screen it says this is not installed (HTC phone with their music app)

**Comment by chreekat** [comment]
Following @najones13's idea, I disabled the "LG music player" on my T-Mobile LG-G2. It appears this solution will work for me. No more 500 "listens" to one song in a single month!

**Comment by HumbleBeeBumbleBee** [comment]
Please disable Neutron Player if you can.

**Comment by HumbleBeeBumbleBee** [comment]
There are two major issues with doing this and two major compatibility issues.

SLS provides support for a variety of applications.
OR
SLS provides support for single track repeat and more structured scrobbling.

Some of these applications don't share track duration (well).
and
Some of these applications don't tell SLS when the track is paused or completed, so SLS cannot find out when the track officially started or finished.

I am manually going through all the applications to see which ones don't work with a more compatible scrobbling service.

The Queue method works for now.

**Comment by HumbleBeeBumbleBee** [comment]
There is an issue with some music apps continuely updated track information when the track is in pause mode.

**Comment by HumbleBeeBumbleBee** [comment]
Please try this version.

https://drive.google.com/open?id=0B9lPaMaVVtiJaGwwdkt0UjBNVHc
