### ISSUE TITLE
Support for n7player

### ISSUE THREAD

**Issue by zeyuri** [tgwizard/sls#82]
Description of the new feature:

Please add support for n7player:
https://play.google.com/store/apps/details?id=com.n7mobile.nplayer&feature=search_result#?t=W251bGwsMSwxLDEsImNvbS5uN21vYmlsZS5ucGxheWVyIl0.

**Comment by HumbleBeeBumbleBee** [comment]
I will try to work on this. :)

**Comment by HumbleBeeBumbleBee** [comment]
Duplicate #14 
n7player supports scrobbling
`Options>Playback` `Turn on scrobbling (check)`
`Options>Playback>Choose scrobbler>Simple Last.fm`
