### ISSUE TITLE
Updated support for MIUI music player

### ISSUE THREAD

**Issue by iparr** [tgwizard/sls#83]
Chinese rom MIUI used to have great support and work very well with SLS.

However, since updating to v5 of this rom, SLS no longer works with MIUI music player.

I'm on MIUI-3.4.26 and SLS seems to have detected a music player 'MIUI Music Player' but last submitted a scrobble on the 15th of March, 2013 (I use the music player on this phone daily).

I presume that the updated player works differently to the previous version. Otherwise, keep up the great work!

**Comment by HumbleBeeBumbleBee** [comment]
I am going to close this issue please use #72.
