### ISSUE TITLE
does not work in my LG Optimus L9 (LG P768) default music Player

### ISSUE THREAD

**Issue by mahdiit** [tgwizard/sls#85]
app does not work with Lg Optimus L9 default music player nothing happen 
also last.fm and other also does not work.

i do not know it is because of default player or this app

**Comment by HumbleBeeBumbleBee** [comment]
Has this been resolved @mahdiit or no?

**Comment by mahdiit** [comment]
yes, it resolved two years a go, i commented on 2013, you ask me in 2015! 
i am now have another android phone
