### ISSUE TITLE
add support for Pandora

### ISSUE THREAD

**Issue by myano** [tgwizard/sls#87]
I would like the ability to scrobble songs from Pandora's android app. I didn't see an issue currently existing that covered this.

This is the original "issue" from the Google Code site, https://code.google.com/p/a-simple-lastfm-scrobbler/issues/detail?id=20

**Comment by CardcaptorRLH85** [comment]
Pandora doesn't pass Now Playing information.  In fact, there's a thread from years ago on Pandora's support forum asking them to add scrobble support.  The general assumption is that they won't add support since that would make it easier for others to duplicate their algorithm.

**Comment by myano** [comment]
Aww, yet they let you share your listening patterns out to Facebook. :-\

**Comment by HumbleBeeBumbleBee** [comment]
Rdio works though...
I am currently working on Spotify support, but I don't know how soon it will be added since @tgwizard hasn't been around for a long while.

Maybe they feel Facebook will help conceal their algorithm.
However somebody could try contacting the developers and see if they'll budge based on what @myano says and that Rdio and Spotify provide their intents openly.

**Comment by HumbleBeeBumbleBee** [comment]
I fired out an email to developer email requesting they share their intents.

**Comment by HumbleBeeBumbleBee** [comment]
Pandora respectfully declines, they have other plans to worry about,
but maybe there is still hope! (at least for Android 4.3+) ... kinda unfair to < 4.3
```
bhb192 commented on Nov 29, 2014

I was able to get SoundCloud track data from the notifications it posts by using the new notifications API introduced in Android 4.3 by pulling the extras android.title for the song and android.text for the artist. This also works with Pandora as another user reported but not iHeartRadio for some reason.
```
I don't think I'll be adding support for Pandora via this technique, but if somebody else wants to try it, go ahead!

**Comment by myano** [comment]
Also, there are unofficial Pandora apps that exist that support scrobbling, such as Pithos, https://pithos.github.io/
