### ISSUE TITLE
Pocket Casts - Scrobbles under "Android Music Player"

### ISSUE THREAD

**Issue by palodich** [tgwizard/sls#88]
Pocket Casts is not listed in the list of apps in Simple Last.fm Scrobbler, but I am seeing the podcasts I listen to scrobbled by SLS, which I don't want. Unchecking "Android Music Player" stopped Pocket Casts from scrobbling, but then this will stop scrobbling from Google Play Music.

Is it possible to separate Pocket Casts into its own checkbox that can be toggled?

**Comment by HumbleBeeBumbleBee** [comment]
Please continue discussion in #200.
