### ISSUE TITLE
add support for HikiPlayer & HikiPlayer Pro

### ISSUE THREAD

**Issue by excyd** [tgwizard/sls#89]
Hi! I used HikiPlayer with Simple Last.fm Scrobller for a long time and everything was ok until  march 2013. HP was recognized by SLS as supported app. Then SLS stopped scrobbling. I thought that it's a problem with HP and tried to buy HikiPlayer Pro but Pro version isn't even recognized by SLS as supported app.
Also I tried reinstalling all apps.
I wrote to HP & HPP developed and he said that this is a problem with SLS.
## Please comment this situation. Thanks.

wbr, Evgeniy

**Comment by HumbleBeeBumbleBee** [comment]
I will try to work on this. :)

**Comment by HumbleBeeBumbleBee** [comment]
I have sent an email to kazufukurou@gmail.com requesting they broadcast song information so SLS can scrobble music played in HikiPlayer.

**Comment by kazufukurou** [comment]
Sorry for late response, I've checked last version and it works with SLS.
