### ISSUE TITLE
Music Player from Optimus L7

### ISSUE THREAD

**Issue by lirtm** [tgwizard/sls#90]
I used this app on my LG Optimus Black. It's not scrobbled by nothing.
Already I once wrote to you, just about the LG-player previous version.

Apps, screenshots in attached.
![screenshot_2013-06-22-16-48-19](https://f.cloud.github.com/assets/4773960/690808/18f2db10-db3a-11e2-93d2-791a2bf51745.png)
![screenshot_2013-06-22-16-47-36](https://f.cloud.github.com/assets/4773960/690809/18f7cd14-db3a-11e2-86c0-61d5973c3319.png)
Apps — https://www.dropbox.com/s/8au3nylcllssvlq/Musicbin.apk

Thanks!

**Comment by HumbleBeeBumbleBee** [comment]
Is everything working @lirtm ? If so, could you CLOSE this issue?
