### ISSUE TITLE
Crash in reciever when sending enums by mistake

### ISSUE THREAD

**Issue by willlunniss** [tgwizard/sls#91]
I setup an enum for managing the state and put the raw enum in the extra bundle rather than calling state.ordinal() (my bad) and this caused SLFS to crash. Looking at the report it could have protection against this sort of mistate at https://github.com/tgwizard/sls/blob/master/app/src/main/java/com/adam/aslfms/receiver/SLSAPIReceiver.java#L55

**Comment by HumbleBeeBumbleBee** [comment]
Could you explain this in more detail?

**Comment by HumbleBeeBumbleBee** [comment]
You just need a try catch block?

**Comment by HumbleBeeBumbleBee** [comment]
Ok. I will patch it.
