### ISSUE TITLE
If there are no user credentials, save scrobbles to cache.

### ISSUE THREAD

**Issue by gausie** [tgwizard/sls#92]
This'd be useful!

**Comment by HumbleBeeBumbleBee** [comment]
Similar problem as https://github.com/tgwizard/sls/issues/36

**Comment by HumbleBeeBumbleBee** [comment]
For now if no credentials are entered, a Toast notification will appear to let the user know that credentials are required.

**Comment by HumbleBeeBumbleBee** [comment]
I think I am happy with using the Toast notification for now.
