### ISSUE TITLE
Adding songs in loop in cache when Music Player is paused

### ISSUE THREAD

**Issue by Rakanishuuuu** [tgwizard/sls#93]
Hi,

First: sorry for my non-perfect-english, it's not easy to talk about bugs :)

So, as the title say, when I pause a song on the Android Music Player (via the widget as well as via the app), the songs keeps being added in the Simple Last FM cache : http://imgur.com/SW25m6K. Yeah I like that song but NOT THAT MUCH.

I find it weird that no-one talked about this earlier, I'm suddenly afraid that I've done something on my Phone (a Nexus 4) leading to this bug.

Any idea how to fix this, or any fix planned?

Thank you!

**Comment by HumbleBeeBumbleBee** [comment]
Here's a potential solution https://github.com/tgwizard/sls/pull/149. Check it out!

**Comment by HumbleBeeBumbleBee** [comment]
@Rakanishuuuu 
@bmos 
If you know how download and build the .apk
Please use this branch https://github.com/tgwizard/sls/tree/testing-149
Otherwise you can use the latest .apk here.
https://drive.google.com/file/d/0B9lPaMaVVtiJLVlLendjSmxRZDA/view

**Comment by Rakanishuuuu** [comment]
Thank you for the Google Drive link! I had no idea how to get it, I'm always a bit lost on github.

I'll try it soon :)

**Comment by bmos** [comment]
I switched to another scrobbling app a while back since it was more in line with Google's design guidelines. I appreciate that you're moving ahead with this project, however.

**Comment by HumbleBeeBumbleBee** [comment]
@Rakanishuuuu 
https://drive.google.com/file/d/0B9lPaMaVVtiJYTVVVDR4YkU1QUU/view?usp=sharing
This is a beta testing version. Let me know if it solves your problem.
It has a different key so you'll have to uninstall and setup SLS again.

**Comment by Rakanishuuuu** [comment]
Hi!

Still not:p http://i.imgur.com/vockiGd.png

Maybe is it because I switch between my music player (the standard Google one) and my podcast app (Podcast Addict)? But you can see that when I unleashed the pause for those apps, it scrobbled them (after a certain delay I think, but can't say for sure).

**Comment by HumbleBeeBumbleBee** [comment]
The latest version can be found here https://github.com/tgwizard/sls/releases/

**Comment by HumbleBeeBumbleBee** [comment]
If anybody has this problem and they'd like to test it please let me know.
I have updated the SLS somewhat. I can provide an APK.
I do support and maintenance on SLS for the lead developer.

**Comment by HumbleBeeBumbleBee** [comment]
There are two major issues with doing this and two major compatibility issues.

SLS provides support for a variety of applications.
OR
SLS provides support for single track repeat and more structured scrobbling.

Some of these applications don't share track duration (well).
and
Some of these applications don't tell SLS when the track is paused or completed, so SLS cannot find out when the track officially started or finished.

I am manually going through all the applications to see which ones don't work with a more compatible scrobbling service.

The Queue method works for now.

**Comment by HumbleBeeBumbleBee** [comment]
This version should solve your problems.

https://drive.google.com/open?id=0B9lPaMaVVtiJaGwwdkt0UjBNVHc
