### ISSUE TITLE
Google Play Music listed as not installed in Music Apps Activity

### ISSUE THREAD

**Issue by grodin** [tgwizard/sls#94]
The Google Play Music app shows up in the list of music apps as Android Music Player (I think because it uses the same intents), however, at least on my Nexus One it is listed as not installed. I think this is because even though the _intents_ are the same as the Android Music Player, the actual package name of the app is not.

Thus, when you use Util.checkForInstalledApp in MusicAppsScreen.java, it's looking for the wrong package name.

Scrobbling works fine, it's just a UI bug as far as I can tell.

Obviously, this is a fairly minor bug, but it had me confused for a while. I'll have a see if I can do anything about it, but I thought I'd raise it as an issue in any case.

**Comment by HumbleBeeBumbleBee** [comment]
Please continue discussion in #200
