### ISSUE TITLE
Scrobbling Songs I Have Not Listened To

### ISSUE THREAD

**Issue by rhartman93** [tgwizard/sls#95]
I am using the Simple Last FM scrobbler on my Galaxy S4 running Android 4.2.2 Jelly Bean and the latest version of TouchWiz. The device is not rooted or modified in any way.

Primarly I listen to music with Google Play Music. I noticed in the last week that a bunch of songs have been scrobbled to my account that I have not listened to. They are popular songs, Artists including Maroon 5, Rhianna, Brittany Spears, and Trey Songz. I don't listen to these artists nor have I listened to them on my phone at all let alone recently. 

There doesn't seem to be any rhyme or reason to when the songs are scrobbled, that I can tell at least. Different artists at different times sometimes close to one another sometimes spread out.

Any help in this area would be greatly appreciated

**Comment by HumbleBeeBumbleBee** [comment]
Is this still  a problem @rhartman93 ? If not, could you please CLOSE this issue.

**Comment by HumbleBeeBumbleBee** [comment]
@rhartman93 Please continue discussion in #145
