### ISSUE TITLE
add support for DI.FM

### ISSUE THREAD

**Issue by damariei** [tgwizard/sls#96]
DI.FM is a very popular music app which is unfortunately is not supported by SLS.

It would be great if support could be added for it.

**Comment by HumbleBeeBumbleBee** [comment]
I have sent an email to support@radiotunes.com requesting they broadcast song information so SLS can scrobble music played in Radio Tunes.

**Comment by HumbleBeeBumbleBee** [comment]
I have sent an email to mobileapps@di.fm requesting they broadcast song information so SLS can scrobble music played in Digitally Imported Radio.

**Comment by HumbleBeeBumbleBee** [comment]
Sky.fm
>We dont have any plans yet to have this feature.

>I will forward to the Devs team for them to have in mind your suggestions.

Di.fm 
>We dont have any plans yet to scrobble.

>I will forward to the devs team for them to check your note
