### ISSUE TITLE
Track played multiple times, but scrobble only one time

### ISSUE THREAD

**Issue by SAOPP** [tgwizard/sls#99]
Hello!

In my device (Galaxy Mega 5.8 + default player), when I played track multiple times, data is sent only one playing. Why? 

Thanks u in advance!

**Comment by HumbleBeeBumbleBee** [comment]
@SAOPP 
@Pichu0102 
If you know how download and build the .apk
Please use this branch https://github.com/tgwizard/sls/tree/testing-149
Otherwise you can use the latest .apk here.
https://drive.google.com/file/d/0B9lPaMaVVtiJLVlLendjSmxRZDA/view

**Comment by HumbleBeeBumbleBee** [comment]
Triplicate continue discussion in #155

**Comment by HumbleBeeBumbleBee** [comment]
@SAOPP 
@Pichu0102 
https://drive.google.com/file/d/0B9lPaMaVVtiJYTVVVDR4YkU1QUU/view?usp=sharing
This is a beta testing version. Let me know if it solves your problem.
It has a different key so you'll have to uninstall and setup SLS again.

**Comment by SAOPP** [comment]
Hi. Thanks u for continue developing... 4 me this problem is not actual, coz I use Poweramp. With this player scrobling working is ok. So thank u again. My old request need to test. Peace.
